udecode/plate

- .storybook/config.js
It seems there is a missing import in this file, this re-adds it 😊
> Add missing import

- packages/slate-plugins/src/elements/list/transforms/toggleList.ts
- packages/slate-plugins/src/elements/list/transforms/unwrapList.ts
This fix attempt to solve issues with list toggle:
* make sure list item is removed when unwrapping
* if multiple paragraphs are selected when pressing toggle - they should end up as separate list items..
> Toggle list fixes

- packages/slate-plugins/src/index.ts
- packages/slate-plugins/src/soft-break/SoftBreakPlugin.ts
- packages/slate-plugins/src/soft-break/index.ts
- packages/slate-plugins/src/soft-break/onKeyDownSoftBreak.ts
- stories/config/initialValues.ts
- stories/plugins/playground.stories.tsx
- stories/plugins/soft-break.stories.tsx
create a new plugin: Soft break plugin
solves #85
> Feat(new-plugin): Soft break plugin

- CHANGELOG.md
- packages/slate-plugins/src/elements/list/transforms/toggleList.ts
> fix: iterable

- CHANGELOG.md
- packages/slate-plugins/src/elements/image/withImage.ts
- packages/slate-plugins/src/elements/index.ts
- packages/slate-plugins/src/elements/link/withLink.ts
- packages/slate-plugins/src/elements/mention/withMention.ts
- packages/slate-plugins/src/elements/video/components/VideoElement.tsx
- packages/slate-plugins/src/elements/video/withVideo.ts
- packages/slate-plugins/src/elements/withInline.ts
- packages/slate-plugins/src/elements/withVoid.ts
- packages/slate-plugins/src/index.ts
- packages/slate-plugins/src/withNodeID.ts
- stories/basic/editable-voids.stories.tsx
- stories/basic/editable-voids/withEditableVoids.ts
- stories/plugins/marks.stories.tsx
- stories/plugins/playground.stories.tsx
- stories/plugins/video.stories.tsx
> Migrate 0.57.2

- packages/slate-plugins/src/index.ts
Export deserializers - as it's quite handy for testing purposes
> Export deserializers

- packages/slate-plugins/src/__tests__/deserializers/deserialize-html/htmlDeserialize/all-deserialize.spec.tsx
Self-explanatory.
We should probably wait for the pipelines to pass before merging next time :-)
> Fix broken test sup/sub

- packages/slate-plugins/src/__tests__/elements/mention/useMention/default.spec.tsx
- packages/slate-plugins/src/elements/mention/types.ts
Issue:
fixes #142 
Readded index type with any
> add removed arbitrary fields for mention data

- packages/slate-plugins/src/elements/paragraph/renderElementParagraph.ts
> Render paragraph as <p> tag

- packages/slate-plugins/src/index.ts
Hmm, I forgot about exporting the folder.
@zbeyens Could you please do another release?
> Export serializers

- packages/slate-plugins/src/__tests__/serializers/serialize-html/htmlSerialize.spec.ts
- packages/slate-plugins/src/serializers/serialize-html/htmlSerialize.ts
I have improved the plugin identification and also added a branch for missing types in top levels.
This should resolve #158 and another problem which is explicitly in the test case provided.
> Fix html serialization issues

- packages/slate-plugins/src/marks/bold/renderLeafBold.tsx
- packages/slate-plugins/src/marks/code/renderLeafCode.tsx
- packages/slate-plugins/src/marks/highlight/renderLeafHighlight.tsx
- packages/slate-plugins/src/marks/italic/renderLeafItalic.tsx
- packages/slate-plugins/src/marks/strikethrough/renderLeafStrikethrough.tsx
- packages/slate-plugins/src/marks/subscript/renderLeafSubscript.tsx
- packages/slate-plugins/src/marks/superscript/renderLeafSuperscript.tsx
- packages/slate-plugins/src/marks/underline/renderLeafUnderline.tsx
- stories/config/initialValues.ts
Empty mark tag can appear .
Fixes:
Check for text before rendering mark tag
Check for text before rendering mark tag
Add information in basic marks story to inform user empty mark are ignored
> check for text before rendering mark component

- packages/slate-plugins/src/common/utils/getRenderElement.tsx
> fix: attributes

- packages/slate-plugins/src/dnd/components/getSelectableElement.tsx
- stories/config/initialValues.ts
- stories/examples/dnd.stories.tsx
- Created new story for DnD functionality
- Reverted the changes to initialValues & playground story so it doesn't break other the stories.
- Adds `filter` function & `level` functionality to `getSlectableElement`
Happy to incorporate any feedback
> New DnD story

- packages/slate-plugins/package.json
- packages/slate-plugins/src/dnd/__tests__/selectable.spec.tsx
- yarn.lock
- Test that Selectable wraps the element
- Test that Selectable doesn't wrap element if `level` doesn't match
Happy to change or incorporate any feedback.
> Add render tests for getSelectableElement 

- packages/slate-plugins/src/deserializers/deserialize-md/utils/parseMD.ts
Reverts udecode/slate-plugins#313
> Revert "Fixes blockquote MD deserialization"

- stories/elements/mention.stories.tsx
Story was out of date after a refactor.
Updated the story, the mention options shape is updated.
> fix mention story

- stories/examples/playground.stories.tsx
https://slate-js.slack.com/archives/C013QHXSCG1/p1613572640099200
Fixed Playground story to match configuration in Mention story.
Apparently, story didn't match prettier / linter config. Highlighted interesting lines with comments
> 🐛 fix broken mention part of playground story

- packages/placeholder/.npmignore
- packages/placeholder/README.md
- packages/placeholder/package.json
- packages/placeholder/src/components/Placeholder.styles.ts
- packages/placeholder/src/components/Placeholder.tsx
- packages/placeholder/src/components/Placeholder.types.ts
- packages/placeholder/src/components/getPlaceholderElement.tsx
- packages/placeholder/src/components/index.ts
- packages/placeholder/src/index.ts
- packages/placeholder/tsconfig.build.json
- packages/placeholder/tsconfig.json
- packages/slate-plugins/package.json
- packages/slate-plugins/src/index.tsx
- stories/elements/placeholder.stories.tsx
> Block placeholder

- stories/examples/tag/components/TagCombobox.tsx
> fix: combobox popup quick fix

- packages/dnd/src/components/Draggable.tsx
- packages/dnd/src/components/Draggable.types.ts
- packages/dnd/src/components/withDraggable.tsx
- stories/config/withStyledDraggables.tsx
> feat(dnd): drag button customization

- docs/docs/getting-started/basic-plugins.mdx
- docs/src/components/Home/Header.tsx
#646 
- fixes #646 
- remove unused elements in the basic plugins page (subscript, superscript and kdb sample elements)
> Fix documentation minor issues

- docs/docs/guides/configuration.mdx
> typo: createSlatePluginsComponents -> createSlatePluginsOptions

- .changeset/core-major-1.md
Reverts udecode/slate-plugins#685
> Revert "multi-editor"

- .changeset/nervous-scissors-sneeze.md
- packages/marks/basic-marks/src/strikethrough/createStrikethroughPlugin.ts
- packages/marks/basic-marks/src/subscript/createSubscriptPlugin.ts
- packages/marks/basic-marks/src/superscript/createSuperscriptPlugin.ts
I noticed that other mark plugins are broken too.
> Fix deserialization of multiple mark plugins

- docs/docusaurus.config.js
This PR updates the latest credentials provided by the amazing DocSearch team.
Maininers: Please tag your pull request with at least one of the following:
`["documentation"]`
resolves #884
> docs(search): update DocSearch credentials

- packages/dnd/package.json
- packages/plate/package.json
> fix-vendor

- docs/docs/plugins/font.mdx
Add ast deserializer for font example so that copy/paste work as expected.
**Issue**
Fixes: #865
**Example**
--fix`.)
> ast serializer for font example, fixes #865

- .changeset/nervous-toys-camp.md
- packages/dnd/package.json
- packages/elements/mention/package.json
- packages/serializers/html-serializer/package.json
- packages/ui/styled-components/package.json
> vendor-peerDeps

- .changeset/ten-apricots-hang.md
- docs/package.json
- docs/yarn.lock
- package.json
- yarn.lock
Upgrade styled-components to fix https://github.com/udecode/plate/issues/943
https://github.com/udecode/plate/discussions/911#discussioncomment-1233244
**Issue**
Fixes: #943 
--fix`.)
> Upgrade styled-components

- .changeset/lucky-chefs-whisper.md
- packages/marks/font/src/getFontDeserialize.ts
Fixes the font size deserializer to pull in the correct options
> fix: font size deserializer options

- docs/docs/examples/multi-editors.mdx
- docs/sidebars.js
- docs/src/live/config/values/values.tsx
New example with a huge multi editor scenario to illustrate the latency on first load
--fix`.)
> add huge multi editor example

- .changeset/afraid-carrots-tease.md
- packages/core/src/plugins/createInsertDataPlugin.ts
- packages/core/src/plugins/html-deserializer/createDeserializeHtmlPlugin.spec.tsx
- packages/core/src/plugins/withPlate.spec.ts
- packages/core/src/utils/setPlatePlugins.ts
- packages/nodes/code-block/src/createCodeBlockPlugin.spec.tsx
> Swap ast and html plugin order

- .changeset/afraid-months-grow.md
- packages/core/src/common/hoc/index.ts
- packages/core/src/common/hoc/withHOC.tsx
- packages/core/src/components/EditorProvider.tsx
- packages/core/src/components/index.ts
- packages/ui/nodes/alignment/src/AlignToolbarButton/AlignToolbarButton.tsx
- packages/ui/nodes/code-block/src/CodeBlockToolbarButton/CodeBlockToolbarButton.tsx
- packages/ui/nodes/font/src/ColorPickerToolbarDropdown/ColorPickerToolbarDropdown.tsx
- packages/ui/nodes/line-height/src/LineHeightToolbarButton/LineHeightToolbarDropdown.tsx
- packages/ui/nodes/link/src/LinkToolbarButton/LinkToolbarButton.tsx
- packages/ui/nodes/list/src/ListToolbarButton/ListToolbarButton.tsx
- packages/ui/nodes/table/src/TableToolbarButton/TableToolbarButton.tsx
- packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.tsx
- packages/ui/toolbar/src/BalloonToolbar/useBalloonToolbarPopper.ts
- packages/ui/toolbar/src/BlockToolbarButton/BlockToolbarButton.tsx
- packages/ui/toolbar/src/MarkToolbarButton/MarkToolbarButton.tsx
> Fix Balloon Toolbar

- .changeset/wild-socks-worry.md
- packages/core/package.json
- packages/editor/combobox/package.json
- yarn.lock
> Upgrade zustood

- .changeset/dry-moons-happen.md
- docs/docs/plugins/serializing-docx.mdx
- docs/src/live/live.tsx
- packages/nodes/indent/src/createIndentPlugin.ts
- packages/nodes/indent/src/createTextIndentPlugin.ts
- packages/nodes/indent/src/index.ts
- packages/serializers/docx/src/deserializer/__tests__/legal-in.spec.tsx
- packages/serializers/docx/src/deserializer/__tests__/legal.spec.tsx
- packages/serializers/docx/src/deserializer/createDeserializeDocxPlugin.ts
- packages/serializers/docx/src/docx-cleaner/utils/getDocxIndent.ts
Similar to the indent plugin, using `textIndent` prop instead of `indent`
> Feat: new textIndent plugin

- .changeset/purple-chicken-decide.md
- docs/src/live/live.tsx
- packages/core/src/components/PlateProvider.tsx
- packages/core/src/hooks/usePlate/useSlateProps.ts
- packages/core/src/hooks/usePlatesStoreEffect.ts
- packages/core/src/stores/plate/platesStore.ts
> Fix PlateProvider

- .changeset/seven-students-change.md
- packages/core/src/components/PlateProvider.spec.tsx
- packages/core/src/components/PlateProvider.tsx
> Fix: PlateProvider

- .changeset/wild-horses-kick.md
- packages/ui/combobox/src/Combobox.tsx
- packages/ui/nodes/mention/src/MentionCombobox/MentionCombobox.tsx
> Fix MentionCombobox props

- .changeset/proud-lions-arrive.md
- packages/ui/combobox/src/Combobox.tsx
Fix maxSuggestions and filter not passed to the comboboxStore.
> Fix combobox not passing all props to store

- .changeset/curvy-paws-complain.md
- docs/docs/plugins/indent-list.mdx
- packages/nodes/indent-list/src/__tests__/indentListPluginPage.ts
- packages/nodes/indent-list/src/normalizers/normalizeIndentListStart.spec.tsx
- packages/nodes/indent-list/src/normalizers/normalizeIndentListStart.ts
- packages/nodes/indent-list/src/transforms/setIndentListNode.ts
- packages/nodes/indent-list/src/transforms/setIndentListNodes.ts
- packages/nodes/indent-list/src/transforms/toggleIndentList.spec.tsx
- packages/nodes/indent-list/src/transforms/toggleIndentList.ts
- packages/nodes/indent-list/src/transforms/toggleIndentListSet.ts
- packages/nodes/indent-list/src/transforms/toggleIndentListUnset.ts
- packages/nodes/indent-list/src/withIndentList.spec.tsx
- packages/nodes/indent-list/src/withIndentList.ts
- packages/nodes/indent/src/transforms/setIndent.ts
> fix indent list

- .changeset/loud-pugs-fly.md
- packages/serializers/md/src/deserializer/utils/deserializeMd.ts
> Deserialization of markdown horizontal rule

- .changeset/fast-pumpkins-grab.md
- packages/ui/popover/package.json
> add styled-components peerDep to plate-ui-popover

- .changeset/rude-parrots-yell.md
- docs/yarn.lock
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.fixtures.tsx
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.spec.tsx
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.styles.ts
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.tsx
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.types.ts
See changesets. Also added tests for Table Element
> Restricted table cell resize in readOnly mode

- .changeset/proud-ghosts-study.md
- packages/core/src/types/plugins/PlatePlugin.ts
> fix: types

- .changeset/slow-walls-rush.md
- packages/core/src/slate/editor/TEditor.ts
> type: add default generic for TEditor

- docs/docusaurus.config.js
- docs/plugins/source-maps/index.js
> Fixes source maps

- .changeset/nervous-queens-bow.md
- packages/nodes/table/src/transforms/moveSelectionFromCell.ts
> fix table navigation

- .changeset/perfect-baboons-listen.md
- docs/docs/plugins/table.mdx
- docs/plugins/module-alias/index.js
- docs/src/live/config/components/Toolbars.tsx
- docs/src/live/live.tsx
- packages/nodes/table/src/createTablePlugin.ts
- packages/nodes/table/src/queries/getTableGridByRange.ts
- packages/nodes/table/src/transforms/addColumn.ts
- packages/nodes/table/src/transforms/addRow.ts
- packages/nodes/table/src/transforms/index.ts
- packages/nodes/table/src/transforms/insertTable.ts
- packages/nodes/table/src/transforms/insertTableColumn.spec.tsx
- packages/nodes/table/src/transforms/insertTableColumn.ts
- packages/nodes/table/src/transforms/insertTableRow.spec.tsx
- packages/nodes/table/src/transforms/insertTableRow.ts
- packages/nodes/table/src/types.ts
- packages/nodes/table/src/utils/getEmptyCellNode.ts
- packages/nodes/table/src/utils/getEmptyRowNode.ts
- packages/nodes/table/src/utils/getEmptyTableNode.ts
- packages/nodes/table/src/withInsertFragmentTable.spec.tsx
- packages/nodes/table/src/withInsertFragmentTable.ts
- packages/nodes/table/src/withTable.ts
- packages/ui/nodes/table/src/TableToolbarButton/TableToolbarButton.types.ts
> Expand table when inserting cells

- .changeset/little-bears-clean.md
- packages/ui/dnd/src/hooks/useDndBlock.ts
Adding support of preview element to useDndBlock
> DnD: Enable preview element useDndBlock

- .changeset/wild-dingos-flash.md
- .github/CODEOWNERS
- packages/headless/src/index.tsx
> fix juice export

- .changeset/swift-pillows-tell.md
- docs/docs/guides/Plate.md
- docs/docs/guides/store.mdx
- docs/docs/guides/styling.mdx
- packages/core/src/components/EditorRefEffect.tsx
- packages/core/src/components/Plate.tsx
- packages/core/src/stores/plate/createPlateStore.ts
- packages/core/src/types/PlateStore.ts
> fix: Plate children

- .changeset/many-timers-poke.md
- packages/nodes/table/src/types.ts
- packages/nodes/table/src/withTable.ts
Addition of generics for Table was missing E.
> Table generics

- .changeset/eighty-eagles-promise.md
- packages/nodes/table/src/types.ts
- packages/nodes/table/src/withInsertFragmentTable.ts
- packages/nodes/table/src/withTable.ts
> fix: table generics

- .changeset/five-hotels-allow.md
- packages/nodes/mention/src/withMention.spec.tsx
- packages/nodes/mention/src/withMention.ts
- packages/test-utils/src/createDataTransfer.ts
- packages/test-utils/src/index.ts
> Fix paste into mentions

- .changeset/silver-impalas-notice.md
- packages/editor/combobox/src/combobox.store.ts
- packages/ui/combobox/src/Combobox.tsx
> Add sorting to combobox

- .changeset/stupid-tomatoes-return.md
- packages/nodes/code-block/src/insertDataCodeBlock.spec.tsx
- packages/nodes/mention/src/withMention.spec.tsx
- packages/nodes/mention/src/withMention.ts
- packages/test-utils/src/createDataTransfer.ts
> Fix cases around newlines and whitespace

- .changeset/strong-donuts-shake.md
- packages/editor/combobox/src/combobox.store.ts
- packages/ui/combobox/src/Combobox.tsx
- packages/ui/combobox/src/Combobox.types.ts
Allows us to highlight/pin full text matches, highlight matched parts of
items etc...
> Pass search to combobox props

- CONTRIBUTING.md
Fixed typo.
```
Github -> GitHub
```
> chore; update CONTRIBUTING.md

- .changeset/forty-windows-admire.md
- docs/docs/guides/plugins.mdx
- packages/core/src/hooks/plate/useSlateProps.ts
- packages/core/src/types/plugin/PlatePlugin.ts
- packages/core/src/utils/plate/index.ts
- packages/core/src/utils/plate/normalizeInitialValue.spec.tsx
- packages/core/src/utils/plate/normalizeInitialValue.ts
> normalizeInitialValue

- .changeset/odd-timers-wait.md
- packages/ui/nodes/media-embed/src/MediaEmbedElement/utils/parseEmbedUrl.ts
add EmbedProviders type for `EmbedUrlData` type. It was incomplete
solves #1681
> add embedProviders union Type

- .changeset/many-suits-marry.md
- packages/core/src/hooks/plate/usePlateEffects.ts
- packages/core/src/hooks/plate/useSlateProps.ts
- packages/core/src/stores/plate/createPlateStore.ts
- packages/core/src/types/plate/PlateStore.ts
- yarn.lock
> fix Plate normalizeInitialValue

- .changeset/sharp-humans-love.md
- packages/nodes/link/src/transforms/upsertLink.ts
> fix copy/paste when using link plugin

- .changeset/eight-bulldogs-admire.md
- packages/ui/nodes/list/src/TodoListElement/TodoListElement.tsx
> Prevent changing to-do list items in readOnly mode

- .changeset/popular-spiders-chew.md
- packages/nodes/image/src/createImagePlugin.ts
> Fix insert image embed

- docs/docs/guides/typescript.mdx
Updated documentation to point to correct typescript example. 
> documentation: Typescript example URL fixed

- .changeset/brown-eggs-attend.md
- .changeset/proud-kiwis-cry.md
- packages/editor/combobox/src/combobox.store.ts
- packages/ui/combobox/src/Combobox.tsx
- packages/ui/combobox/src/Combobox.types.ts
> Combobox floatingOptions

- .changeset/twenty-feet-lay.md
- packages/ui/nodes/table/src/TableElement/TableElement.tsx
- packages/ui/nodes/table/src/TableElement/TableElement.types.ts
> Table: popover props

- .changeset/spotty-hotels-happen.md
- examples/apps/next/src/pages/_app.tsx
- examples/src/PlaygroundApp.tsx
- examples/src/styles.css
- packages/nodes/list/src/onKeyDownList.ts
- packages/nodes/list/src/transforms/toggleList.spec.tsx
- packages/nodes/list/src/transforms/toggleList.ts
- packages/nodes/list/src/transforms/unwrapList.ts
- yarn.lock
> fix: `toggleList` with `validLiChildrenTypes`

- .changeset/great-schools-train.md
- packages/nodes/table/src/withNormalizeTable.spec.tsx
- packages/nodes/table/src/withNormalizeTable.ts
> fix: unwrap nested tables

- .changeset/few-pillows-punch.md
- .changeset/few-pillows-punchh.md
- packages/nodes/table/src/transforms/deleteColumn.ts
- packages/nodes/table/src/transforms/insertTableColumn.ts
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.tsx
- packages/ui/nodes/table/src/hooks/useTableColSizes.ts
> Fix: table column resize

- .changeset/popular-hairs-watch.md
- packages/serializers/html/package.json
- yarn.lock
Fixes a missing peer dependency in the `plate-serializer-html` package.
> Fix missing peer dep in `plate-serializer-html`

- .changeset/perfect-feet-turn.md
- packages/nodes/table/src/types.ts
- packages/ui/nodes/table/src/hooks/useTableColSizes.ts
> Table single column width fix

- packages/ui/dnd/src/components/Draggable.styles.ts
- packages/ui/dnd/src/components/Draggable.tsx
> Fix: draggable selection

- .changeset/brown-beers-smell.md
- packages/nodes/list/src/transforms/moveListItemDown.ts
- packages/nodes/list/src/transforms/moveListItems.ts
> moveListItems should return boolean

- .changeset/clean-papayas-bow.md
- docs/docs/sandpack/files/typescript/code-plateTypes.ts
- examples/src/typescript/plateTypes.ts
- packages/nodes/indent-list/src/createIndentListPlugin.ts
- packages/nodes/indent-list/src/normalizers/normalizeIndentListStart.spec.tsx
- packages/nodes/indent-list/src/normalizers/normalizeIndentListStart.ts
Add `listRestart` option for indentList plugin.
> [Proposal] listRestart option for indent-list plugin

- .changeset/twenty-jobs-leave.md
- packages/nodes/link/src/transforms/upsertLink.ts
> fix(link-plugin): set nodes also if only the link target changed

- .changeset/violet-candles-mix.md
- docs/BREAKING_CHANGES.md
- packages/core/CHANGELOG.md
- packages/core/src/atoms/createAtomStore.ts
- packages/core/src/components/plate/PlateProvider.tsx
- packages/core/src/hooks/plate/useEditableProps.ts
- packages/core/src/hooks/plate/usePlateStoreEffects.ts
- packages/core/src/hooks/plate/useSlateProps.ts
- packages/core/src/types/plate/PlateStore.ts
> Fix Plate 17

- .changeset/brave-otters-live.md
- docs/docs/plugins/BlockSelectionSandpack.tsx
- docs/docs/plugins/block-selection.mdx
- docs/docs/sandpack/code-deps.ts
- docs/docs/sandpack/plate-versions.ts
- examples/package.json
- examples/src/BlockSelectionApp.tsx
- examples/src/PlaygroundApp.tsx
- packages/headless/src/index.tsx
- scripts/plop/plop-version.js
- yarn.lock
> Block selection moved out from @udecode/plate

- .changeset/loud-coats-fail.md
- packages/nodes/indent-list/src/normalizers/normalizeIndentListNotIndented.ts
> fix: indent 0

- .changeset/giant-colts-travel.md
- .changeset/small-weeks-burn.md
- packages/nodes/table/src/transforms/deleteColumn.spec.tsx
- packages/nodes/table/src/transforms/deleteColumn.ts
- packages/ui/combobox/src/Combobox.tsx
> fix: deleteColumn

- .changeset/neat-buttons-notice.md
- packages/nodes/indent-list/src/queries/getSiblingIndentList.ts
> Fix indent 0

- .changeset/cool-pugs-sing.md
- packages/core/src/components/plate/Plate.spec.tsx
- packages/core/src/components/plate/PlateProvider.spec.tsx
- packages/core/src/stores/plate/createPlateStore.ts
> fix: nested plate

- .changeset/mean-guests-pay.md
- .changeset/nervous-keys-develop.md
- packages/nodes/indent-list/src/createIndentListPlugin.ts
- packages/nodes/indent-list/src/index.ts
- packages/nodes/indent-list/src/onKeyDownIndentList.spec.tsx
- packages/nodes/indent-list/src/onKeyDownIndentList.ts
- packages/nodes/indent-list/src/queries/getSiblingListStyleType.ts
- packages/nodes/indent-list/src/queries/index.ts
- packages/nodes/indent-list/src/transforms/toggleIndentListSet.ts
- packages/nodes/indent/src/transforms/setIndent.ts
> Indent list: enter, nested

- .changeset/gorgeous-spiders-help.md
- .changeset/gorgeous-spiders@-help.md
- packages/core/src/utils/slate/applyDeepToNodes.ts
- packages/editor/node-id/src/createNodeIdPlugin.spec.tsx
- packages/editor/node-id/src/withNodeId.ts
> fix: filter in node id plugin

- examples/src/link/linkPlugin.tsx
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkEdit.ts
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkEnter.ts
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkEscape.ts
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkInsert.ts
- packages/nodes/link/src/createLinkPlugin.ts
- packages/nodes/link/src/transforms/submitFloatingLink.ts
- packages/nodes/link/src/transforms/upsertLink.spec.tsx
- packages/nodes/link/src/transforms/upsertLink.ts
- yarn.lock
> Fix: link hotkeys

- docs/docs/guides/cloud.mdx
- examples/src/CloudApp.tsx
Improvements to the documentation for Plate Cloud.
- Improved installation instructions
- Improved description of usage of `apiKey` and `authToken`
> Improve documentation on Plate Cloud

- .changeset/rude-bears-fly.md
- packages/headless/package.json
- packages/ui/plate/package.json
- yarn.lock
> chore: added emoji package

- .changeset/fixed-deserialization-for-markdown.md
- packages/serializers/md/src/deserializer/createDeserializeMdPlugin.ts
Resolve #1812, see changesets. This commit is to revert some changes to PR #1616, is that OK?
> Fixed deserialization for markdown

- packages/media/src/media/parseMediaUrl.ts
> Fix: parseTwitterUrl

- .changeset/rude-chairs-wink.md
@zbeyens is this the way to add it?
> Added change set

- .changeset/beige-pianos-camp.md
- packages/ui/nodes/emoji/src/EmojiToolbarDropdown/EmojiToolbarDropdown.tsx
- packages/ui/nodes/emoji/src/index.ts
- yarn.lock
Emoji plugin update.
Changed settings prop
Exposed emoji picker Ui
> Updated emoji plugin

- .changeset/gold-monkeys-smoke.md
- packages/comments/src/components/CommentNewSubmitButton.tsx
> fix: onCommentAdd, lack of comment id when reply comment

- .changeset/fair-humans-wash.md
- packages/ui/combobox/src/Combobox.tsx
Combobox style prop
I guess to node classname prop is assigned wrong var and I updated that
> combobox: fix classname prop

- .changeset/smooth-cobras-mix.md
- packages/serializers/md/src/deserializer/createDeserializeMdPlugin.ts
> Revert "Remove unnecessary query in deserialize markdown"

- .changeset/olive-taxis-join.md
- packages/core/src/transforms/removeSelectionMark.ts
> fix: use `removeEditorMark`

- examples/src/exit-break/exitBreakPlugin.ts
> Fix exit break demo options #2154

- .changeset/red-jokes-think.md
- packages/core/src/slate/editor/getEditorString.ts
> fix: getEditorString

- .changeset/shiny-taxis-begin.md
- examples/src/SerializingHtmlApp.tsx
- packages/floating/src/components/ElementPopover.tsx
- packages/ui/combobox/src/Combobox.tsx
- packages/ui/placeholder/src/components/Placeholder.tsx
- packages/ui/toolbar/src/BalloonToolbar/useFloatingToolbar.ts
> fix: replace `useEditorState` by `usePlateEditorState`

- .changeset/bright-timers-carry.md
- packages/core/src/atoms/elementAtom.tsx
- packages/core/src/atoms/index.ts
- packages/core/src/atoms/useElement.ts
> fix: `useElement`

- .changeset/flat-rats-perform.md
- docs/docs/plugins/tabbable.mdx
- packages/editor/tabbable/README.md
- packages/editor/tabbable/src/types.ts
> Fill in README for Tabbable plugin

- .changeset/fifty-flowers-attack.md
- .changeset/silent-papayas-itch.md
- docs/docs/plugins/link.mdx
- packages/comments/src/createCommentsPlugin.ts
- packages/comments/src/types.ts
- packages/core/package.json
- packages/media/src/media/FloatingMedia/FloatingMediaUrlInput.tsx
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkEnter.ts
- packages/nodes/link/src/components/FloatingLink/useFloatingLinkEscape.ts
- packages/nodes/link/src/createLinkPlugin.ts
- yarn.lock
> Comments: support hotkey ctrl+shift+M

- .changeset/haealthy-yakqs-buy.md
- .changeset/healthy-yaaasks-buy.md
- .changeset/healthy-yaks-buy.md
- .changeset/healthy-yaks-buys.md
- examples/src/TableApp.tsx
- examples/src/table/tableValue.tsx
- packages/nodes/table/src/transforms/insertTableColumn.spec.tsx
- packages/nodes/table/src/transforms/insertTableColumn.ts
- packages/nodes/table/src/types.ts
- packages/nodes/table/src/withNormalizeTable.spec.tsx
- packages/nodes/table/src/withNormalizeTable.ts
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.styles.ts
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.tsx
- packages/ui/nodes/table/src/TableCellElement/TableCellElement.types.ts
- packages/ui/nodes/table/src/TableElement/TableElement.styles.ts
- packages/ui/nodes/table/src/TableElement/TableElement.tsx
- packages/ui/nodes/table/src/TableElement/TableElement.types.ts
- packages/ui/nodes/table/src/hooks/useTableColSizes.ts
- packages/ui/plate/src/utils/createPlateUI.ts
- yarn.lock
> Feat: fixed table column widths

- .changeset/rich-parrots-fetch.md
- packages/ui/cursor/src/queries/getSelectionRects.ts
> fix: Failed to execute 'selectNode' on 'Range': the given Node has no parent

- .changeset/breezy-windows-confess.md
- .changeset/wicked-islands-mate.md
- packages/nodes/table/src/components/TableCellElement/TableCellElementResizable.tsx
- packages/nodes/table/src/createTablePlugin.ts
- packages/nodes/table/src/transforms/insertTableColumn.spec.tsx
- packages/nodes/table/src/transforms/insertTableColumn.ts
- packages/nodes/table/src/types.ts
- packages/ui/nodes/table/src/PlateTableElement.tsx
> Shrink `colSizes` when total width exceeds `initialTableWidth`

- .changeset/twenty-kings-tan.md
- packages/floating/src/components/ElementPopover.tsx
- packages/floating/src/components/Popover.tsx
- packages/ui/nodes/media/src/ImageElement/ImageElement.tsx
- packages/ui/nodes/media/src/ImageElement/ImageElement.types.ts
- packages/ui/nodes/media/src/MediaEmbedElement/MediaEmbedElement.tsx
- packages/ui/nodes/media/src/MediaEmbedElement/MediaEmbedElement.types.ts
Added a prop to disable popover and make use of caption options on media embed element.
> Popover options

- .changeset/witty-geese-share.md
- packages/nodes/link/src/transforms/submitFloatingLink.ts
- packages/nodes/link/src/utils/triggerFloatingLinkEdit.ts
Changed target to _blank to be correctly read from AST tree.
> fix target for new tab

- .changeset/blue-cats-wave.md
- packages/dnd/src/components/Scroller/DndScroller.tsx
> Revert "fix: add delay to DnD scroller"

- .changeset/shaggy-ties-sin.md
- packages/editor/trailing-block/src/withTrailingBlock.ts
> 🐛 trailing-block type

- .changeset/old-books-deliver.md
- packages/media/src/image/withImageUpload.ts
- packages/media/src/video/parseVideoUrl.ts
> Fix media insertData

- .changeset/tame-chicken-bake.md
- packages/core/src/plugins/createDeserializeAstPlugin.ts
> 🐛 Fix test

- .changeset/dull-doors-taste.md
- packages/ui/toolbar/src/ToolbarDropdown/useDropdownControls.ts
> 🐛 open dropdown

- .changeset/balloon-toolbar.md
Added change set for Balloon toolbar
> Added changeset

- .changeset/afraid-pandas-argue.md
- docs/docs/plugins/link.mdx
- examples/src/link/linkPlugin.tsx
- packages/nodes/link/src/createLinkPlugin.ts
- packages/nodes/link/src/utils/getLinkAttributes.spec.ts
- packages/nodes/link/src/utils/getLinkAttributes.ts
- packages/serializers/html/src/__tests__/node-to-props.spec.ts
- packages/serializers/html/src/__tests__/with-attributes.spec.ts
Resolves https://github.com/udecode/plate/discussions/2378
> Make it possible to override link targets

- .changeset/popular-waves-relax.md
- packages/suggestion/src/transforms/acceptSuggestion.ts
- packages/suggestion/src/transforms/rejectSuggestion.ts
> 🐛 suggestion imports

- .changeset/spicy-monkeys-relax.md
- packages/nodes/mention/src/withMention.spec.tsx
- packages/nodes/mention/src/withMention.ts
It renders empty node tag at the beginning of the line.
> fix: mentions trigger

- .changeset/spicy-ramen.md
- packages/nodes/emoji/src/constants.ts
- packages/nodes/emoji/src/createEmojiPlugin.ts
- packages/nodes/emoji/src/handlers/getEmojiOnSelectItem.ts
- packages/nodes/emoji/src/handlers/getFindTriggeringInput.ts
- packages/nodes/emoji/src/types.ts
- packages/nodes/emoji/src/utils/EmojiTriggeringController.ts
- packages/nodes/emoji/src/utils/EmojiTriggeringController.types.ts
- packages/nodes/emoji/src/utils/IndexSearch/IndexSearch.ts
- packages/nodes/emoji/src/withEmoji.ts
Because of global use of combobox and emoji plugin was interfering with Mention plugin, I did some refactoring and added additional options to emoji plugin and it is more stable now.
The video is on playground with all plugins and show normal behaviour between mention and emoji.
https://www.loom.com/share/975b1193076a4598970ff3b24d4af1e9?sid=867cc0de-f2d6-47fb-9d46-f5227830c1e0
> fix: emoji plugin

- .changeset/silly-mugs-care.md
- docs/docs/plugins/link.mdx
- packages/nodes/link/src/createLinkPlugin.ts
- packages/nodes/link/src/utils/getLinkAttributes.spec.ts
- packages/nodes/link/src/utils/getLinkAttributes.ts
- packages/nodes/link/src/utils/validateUrl.ts
Added a optional option to skip link sanitations. this will make the link plugin easier to work with when it comes to internal links.
> Added option to skip link sanitation

- .changeset/poor-ears-exercise.md
- packages/nodes/link/src/createLinkPlugin.ts
- packages/nodes/link/src/withLink.spec.tsx
- packages/nodes/link/src/withLink.ts
Allow pasting links as urls.
https://github.com/udecode/plate/assets/39378793/f738fbaf-a507-482e-8289-eff0f453cacc
> [LinkPlugin] Allow pasting links as urls

- .changeset/thick-meals-melt.md
> [Changeset] Add changeset for copy single cell content

- packages/core/src/plugins/html-deserializer/utils/copyBlockMarksToSpanChild.ts
- packages/core/src/plugins/html-deserializer/utils/isHtmlTable.ts
Fixes pasting tables from docx into Safari.
**Before**
https://github.com/udecode/plate/assets/39378793/e73fc42f-3d10-4050-b44b-0989ed7fc81c
**After**
https://github.com/udecode/plate/assets/39378793/c1f51140-4412-4898-bf87-d96a8fc89855
> [HtmlDeserializer] Fix pasting tables into safari from docx

- .changeset/empty-mails-sip.md
- packages/comments/src/components/useCommentLeaf.ts
> Remove comment node when new comment form is closed

- apps/www/content/docs/accessing-editor.mdx
```ts
const tmpEditor = createPlateEditor({ plugins });
return deserializeHtml(editor, {
```
to
```ts
const tmpEditor = createPlateEditor({ plugins });
return deserializeHtml(tmpEditor, {
```
> 📝 Fix typo

- README.md
Moves the link to the contributing guide to a more prominent spot so it's easier to find
```diff
+ ## Running locally
+
+ To get started, check out our [contributing guide](CONTRIBUTING.md).
+
@@ -48,4 +52,4 @@ We'd love for you to join us! Whether it's through giving us a 🌟 star, making
[![Star History Chart](https://api.star-history.com/svg?repos=udecode/plate&type=Date)](https://star-history.com/#udecode/plate&Date)
- To get started, check out our [contributing guide](CONTRIBUTING.md). Need more help? Join us on [Discord](https://discord.gg/mAZRuBzGM3). We're always here to guide you.
+ Need more help? Join us on [Discord](https://discord.gg/mAZRuBzGM3). We're always here to guide you.
```
> Make contributing guide easier to find

- .changeset/green-avocados-kneel.md
- packages/core/src/plugins/createInlineVoidPlugin.ts
> 🐛 markable void

- apps/www/package.json
- apps/www/src/lib/plate/demo/values/mediaValue.tsx
- yarn.lock
Updated version fixes styling multi media issues
> update react tweet to fix multi media styles

- .changeset/modern-panthers-smile.md
- .changeset/polite-rivers-chew.md
- packages/link/package.json
- packages/node-id/src/createNodeIdPlugin.spec.tsx
- packages/node-id/src/createNodeIdPlugin.ts
- packages/node-id/src/withNodeId.ts
- yarn.lock
> ✨ override node id

- .github/ISSUE_TEMPLATE/bug.md
Algora uses a `##` for its Funding section
> Use H2s in issue template

- .changeset/wild-cups-heal.md
- packages/line-height/src/hooks/useLineHeightDropdownMenu.ts
> Fix: line height state

- .changeset/wet-ties-do.md
- packages/test-utils/src/jsx.ts
Blocking adding unit tests for a custom numbered list plugin.
> Add jsx element for nli element

- .changeset/two-avocados-hear.md
- apps/www/content/docs/api/core/plate.mdx
- apps/www/src/lib/plate/demo/plugins/emojiPlugin.ts
- packages/core/src/components/Plate.spec.tsx
- packages/core/src/stores/plate/createPlateStore.ts
- packages/core/src/types/slate-react/TEditableProps.ts
- templates/plate-playground-template/src/lib/plate/plate-plugins.ts
> Plate id prop string

- apps/www/package.json
- apps/www/src/components/counting-numbers.tsx
- apps/www/src/components/site-header.tsx
- apps/www/src/components/star-on-github.tsx
- turbo.json
- yarn.lock
> Star on github 

- .changeset/twenty-rockets-thank.md
- packages/code-block/src/decorateCodeLine.ts
> 🐛 Fix token import

- .changeset/forty-apes-teach.md
- packages/serializer-csv/src/deserializer/types.ts
- packages/serializer-csv/src/deserializer/utils/deserializeCsv.ts
> Fix import papaparse

- .changeset/chilled-candles-hunt.md
- .changeset/new-coins-suffer.md
- apps/www/src/registry/default/plate-ui/draggable.tsx
- packages/dnd/src/components/useDraggable.ts
- packages/plate-utils/src/hooks/usePlaceholder.ts
> Improve performance of placeholder and draggable HOCs

- apps/www/content/docs/components/comments-popover.mdx
Fix for a small typo in the documentation
> fix name of the comments-popover component in the doc

- .changeset/dirty-insects-obey.md
- packages/table/src/withInsertFragmentTable.ts
Fix for the issue https://github.com/udecode/plate/issues/2770
> Fix: insert table in paragraph

- apps/www/src/registry/default/plate-ui/toolbar.tsx
Fixed the style for toolbar not update when pressed
> fix: ToolbarButton not update the pressed style

- .changeset/slimy-suns-joke.md
- packages/table/src/merge/computeCellIndices.ts
- packages/table/src/merge/isTableRectangular.ts
- packages/table/src/merge/unmergeTableCells.ts
- packages/table/src/merge/useTableMergeState.ts
> [Table] fix unmerge

- .changeset/tasty-kiwis-raise.md
Add missed changesed for resizable related to table cells merging work
> Add changeset for resizable

- .changeset/angry-insects-hide.md
- packages/table/src/queries/getColSpan.ts
- packages/table/src/queries/getRowSpan.ts
- packages/table/src/types.ts
> 🏷️ table types

- .changeset/modern-ducks-kick.md
- packages/core/src/components/PlateContent.tsx
- yarn.lock
> Use JSX syntax for `render(Before|After)Editable`

- .changeset/pink-keys-battle.md
- apps/www/content/docs/components/theming.mdx
- packages/cli/src/commands/init.ts
- packages/cli/test/commands/init.test.ts
> 🔧 add @udecode/cn to cli init

- .changeset/fuzzy-cats-bow.md
- .eslintrc.cjs
- packages/suggestion/package.json
- packages/suggestion/src/internal/diff-match-patch-ts/LICENSE
- packages/suggestion/src/internal/diff-match-patch-ts/diff-match-patch.class.ts
- packages/suggestion/src/internal/diff-match-patch-ts/diff-op.enum.ts
- packages/suggestion/src/internal/diff-match-patch-ts/diff.type.ts
- packages/suggestion/src/internal/diff-match-patch-ts/index.ts
- packages/suggestion/src/internal/diff-match-patch-ts/patch-operation.class.ts
- packages/suggestion/src/slate-diff/internal/utils/dmp.ts
- yarn.lock
> diff-match-patch

- .changeset/proud-papayas-check.md
- packages/suggestion/src/slate-diff/internal/transforms/transformDiffTexts.ts
> fix slateTextDiff

- .changeset/curvy-mugs-taste.md
- apps/www/package.json
- config/aliases.js
- packages/plate/package.json
- packages/plate/src/index.tsx
- yarn.lock
> Add missing `@udecode/plate-diff` export to `@udecode/plate`

- .changeset/tiny-wolves-love.md
- apps/www/src/registry/default/example/version-history-demo.tsx
- packages/diff/src/computeDiff.spec.ts
- packages/diff/src/computeDiff.ts
- packages/diff/src/internal/transforms/transformDiffTexts.ts
- packages/diff/src/internal/utils/inline-node-char-map.spec.ts
- packages/diff/src/internal/utils/inline-node-char-map.ts
- packages/diff/src/internal/utils/unused-char-generator.spec.ts
- packages/diff/src/internal/utils/unused-char-generator.ts
> Add `lineBreakChar` option

- .changeset/silent-games-cover.md
- packages/link/src/components/FloatingLink/FloatingLinkUrlInput.tsx
Fix https://github.com/udecode/plate/issues/2526
> Fix link bug (#2526)

- .changeset/stupid-lions-doubt.md
- packages/table/src/withSetFragmentDataTable.ts
Resolves https://github.com/udecode/plate/issues/3025
> Add colSpan & rowSpan to copied fragment data (resolves issue #3025)

- .changeset/odd-ducks-provide.md
- packages/link/src/components/FloatingLink/useFloatingLinkInsert.ts
- yarn.lock
A few day ago I fix the bug #2526 , but I didn't notice this similar situation at the time.
The last time I updated the URL, but in certain situations, the text also needs updating.
before
https://github.com/udecode/plate/assets/66810611/a82b3d55-8262-46dd-8c65-5ec5c1df2312
after this pr 
https://github.com/udecode/plate/assets/66810611/82623f12-97c8-4397-a827-a4750fad829b
> Fix link bug

- apps/e2e-examples/package.json
- apps/www/package.json
- packages/excalidraw/package.json
- yarn.lock
> Dependabot/npm and yarn/npm and yarn security group 29ffd4c3ca

- .changeset/cuddly-clocks-behave.md
- packages/indent-list/src/injectIndentListComponent.tsx
> remove data-slate-void

- .changeset/quiet-squids-travel.md
- packages/dnd/src/components/useDraggable.ts
> Fix draggable type

- .changeset/clever-flowers-approve.md
- .changeset/tender-geckos-cover.md
- packages/slate-utils/src/transforms/toggleMark.ts
- packages/table/src/withMarkTable.tsx
- packages/table/src/withTable.ts
before 
https://github.com/udecode/plate/assets/164472012/a3d40efb-9dbc-4c70-9e7b-a87d0bd8ee00
> fix: table-marks

- config/turbowatch.config.ts
> Fix new version globSync usage

- apps/www/package.json
- yarn.lock
> Updated the slate version

- .changeset/cuddly-balloons-pretend.md
- packages/table/src/merge/computeCellIndices.ts
- packages/table/src/merge/insertTableColumn.ts
- packages/table/src/merge/insertTableRow.ts
- packages/table/src/merge/useTableMergeState.ts
> Add computeCellIndices fallback for table insert functions

- .changeset/swift-shoes-poke.md
- packages/heading/src/createHeadingPlugin.ts
> Revert changes in heading plugin to make hotkey work

- .changeset/cuddly-onions-relax.md
- .changeset/fluffy-rabbits-argue.md
- apps/www/src/components/plate-ui/playground-turn-into-dropdown-menu.tsx
- packages/floating/src/hooks/useFloatingToolbar.ts
- packages/mention/src/types.ts
> fix: turn-into-dropdown-menu losing focus

- .changeset/weak-games-relax.md
- packages/media/src/media/useMediaState.ts
> Fix: useMediaState

- packages/diff/README.md
> Link to correct LICENSE file in `packages/diff/README.md`

- .changeset/odd-carrots-notice.md
- packages/link/src/components/FloatingLink/FloatingLinkUrlInput.tsx
- packages/link/src/utils/encodeUrlIfNeeded.spec.ts
- packages/link/src/utils/encodeUrlIfNeeded.ts
- packages/link/src/utils/index.ts
- packages/link/src/utils/safeDecodeUrl.spec.ts
- packages/link/src/utils/safeDecodeUrl.ts
- packages/link/src/utils/validateUrl.ts
- yarn.lock
Continuation of #3307 by @beeant0512
> Fix: Cannot input an unencoded URL

- .changeset/metal-moose-prove.md
- packages/heading/src/toc/createTocPlugin.ts
- packages/heading/src/toc/hooks/useTocElement.ts
- packages/heading/src/toc/tocSideBar/useContentObserver.ts
- packages/heading/src/toc/tocSideBar/useTocSideBarState.ts
- packages/heading/src/utils/getHeadingList.ts
- packages/heading/src/utils/index.ts
This allows me to customize the heading I need
> Expose toc plugin queryHeading fuc

- .changeset/gentle-games-remain.md
- packages/heading/src/toc/hooks/useTocElement.ts
- packages/heading/src/toc/tocSideBar/useContentObserver.ts
- packages/heading/src/toc/tocSideBar/useTocSideBarState.ts
- packages/heading/src/utils/internal/getHeadingList.ts
> Queryheadings

- .changeset/plenty-students-collect.md
- packages/slate/src/interfaces/editor/TEditor.ts
https://github.com/ianstormtaylor/slate/pull/5295
> feat: add option parameter to normalizeNode following slate#5295

- .changeset/bright-walls-turn.md
- packages/alignment/src/client/useAlignDropdownMenu.ts
https://github.com/udecode/plate/pull/3209/files i created this PR some time back and i think it introduced a bug where everything is aligned to left default i am reverting it back to start now 
PR comment that highlights the bug https://github.com/udecode/plate/pull/3209/files#r1674793717
> Bug-fix-alignment-determination-logic for start logic

- .changeset/thick-bears-fetch.md
- packages/heading/src/toc/tocSideBar/useTocObserver.ts
Before:
https://github.com/user-attachments/assets/beb12871-3811-4ad7-8e4b-a06684f619f7
After:
https://github.com/user-attachments/assets/cf24a126-aa99-47cf-b82c-68d3d7e86ab2
> Make the heading item in the middle when there is a scroll bar

- .changeset/khaki-comics-remember.md
- packages/media/src/media-embed/parseTwitterUrl.ts
- yarn.lock
**Checklist**
regex in `parseTwitterUrl` did not accept x.com domains, that should be fixed by this
> feat: `parseTwitterUrl` accept x.com

- .changeset/copy-missing-style.md
- packages/core/src/shared/plugins/createDeserializeAstPlugin.ts
**Checklist**
**fix**
copy a table row and paste it, the row style will missing
> fix: cannot copy format when copy elements from the editor it self

- .changeset/little-doors-whisper.md
- packages/floating/src/libs/floating-ui.ts
> Export `FloatingArrow` from floating module

- .changeset/bright-papayas-fix.md
- apps/www/src/styles/globals.css
- packages/selection/src/components/BlockSelectionArea.tsx
- yarn.lock
> Playground selection

- .changeset/nervous-moons-report.md
- apps/www/content/docs/block-selection.mdx
- packages/selection/src/onKeyDownSelection.spec.tsx
> test & docs

- .changeset/heavy-rice-count.md
- packages/reset-node/src/createResetNodePlugin.ts
> fix: missing id will cause block selection not working and other issues

- .changeset/grumpy-moons-kiss.md
- packages/test-utils/src/jsx.ts
> Jsx equation

- .changeset/spotty-goats-whisper.md
- packages/normalizers/src/withNormalizeTypes.ts
> Use blockFactory to create elements in NormalizeTypes plugin

- .changeset/delete-table-when-delete-last-row.md
- packages/table/src/merge/deleteRow.ts
> fix: delete last row will cause editor crash when `enableMerging: true`

- .changeset/cold-jeans-sparkle.md
- packages/test-utils/src/jsx.ts
> Add media elements support in jsx

- apps/www/src/lib/plate/demo/plugins/resetBlockTypePlugin.ts
> fix playground can't remove codeblock

- .changeset/good-lizards-fry.md
- packages/slate/src/interfaces/history-editor/withMerging.ts
> Add withMerging

- .changeset/rare-zoos-shout.md
- apps/www/src/registry/default/example/playground-demo.tsx
- packages/selection/src/internal/SelectionArea.ts
fixes 
https://github.com/user-attachments/assets/3d772154-b714-4766-b388-e040d7e19234
> Fix width issues caused by hover scrollbars.

- .changeset/hip-toys-occur.md
- packages/indent-list/src/react/renderIndentListBelowNodes.tsx
- yarn.lock
> Fix renderBelowNodes make cursor position incorrect.

- apps/www/content/docs/dnd.mdx
- ~~`yarn changeset`~~ (N/A)
- ~~[ui changelog](apps/www/content/docs/components/changelog.mdx)~~ (N/A)
> Fix `NodeIdPlugin` name in Drag & Drop docs

- apps/www/content/docs/components/changelog.mdx
- apps/www/src/registry/default/plate-ui/code-line-element.tsx
- apps/www/src/registry/default/plate-ui/emoji-icons.tsx
- apps/www/src/registry/default/plate-ui/emoji-input-element.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker-content.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker-navigation.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker-preview.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker-search-and-clear.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker-search-bar.tsx
- apps/www/src/registry/default/plate-ui/emoji-picker.tsx
- apps/www/src/registry/default/plate-ui/excalidraw-element.tsx
- apps/www/src/registry/default/plate-ui/hr-element.tsx
- apps/www/src/registry/default/plate-ui/mention-input-element.tsx
- apps/www/src/registry/default/plate-ui/toc-element.tsx
- apps/www/src/registry/default/plate-ui/todo-list-element.tsx
- yarn.lock
**Checklist**
- [] `yarn brl`
- [] `yarn changeset`
> feat(emoji-picker): adjust ui emoji picker

- .changeset/loud-pugs-dance.md
- packages/link/src/react/components/FloatingLink/useFloatingLinkEdit.ts
Fix for issue https://github.com/udecode/plate/issues/3603
**Checklist**
https://www.loom.com/share/f574f6230d4d49fb8aff229b597cffc6?sid=178b818b-7865-4554-b381-086982e8ccc6
> floating link button correction

- .changeset/hot-icons-jam.md
- packages/core/src/react/stores/plate/selectors/useEditorPlugin.ts
> Fix: useEditorPlugin type

- .changeset/warm-waves-punch.md
- packages/markdown/src/lib/deserializer/utils/deserializeMd.spec.tsx
- packages/markdown/src/lib/remark-slate/remarkDefaultElementRules.ts
- packages/markdown/src/lib/remark-slate/remarkTransformElementChildren.ts
- yarn.lock
> Fix pasting >>>

- apps/www/content/docs/index.mdx
**Checklist**
Awesome project. I am currently using it for an open source knowledge base i am working on. Will be contributing more as I use the package.
> Updating "Who is using Plate in production" link

- .changeset/brown-flowers-brush.md
- packages/callout/src/react/hooks/useCalloutEmojiPicker.ts
> Fix set icon

- .changeset/big-snails-deny.md
- packages/core/src/react/components/DefaultLeaf.tsx
> Fix `DefaultLeaf` missing style attribute

- .changeset/big-lobsters-run.md
- packages/ai/src/react/copilot/CopilotPlugin.tsx
- packages/ai/src/react/copilot/utils/getNextWord.ts
- packages/ai/src/react/copilot/withCopilot.ts
- yarn.lock
> Fix issues with the Copilot plugin when using IME.

- apps/www/content/docs/collaboration.mdx
> fix collaboration.mdx code example

- .changeset/fuzzy-shrimps-allow.md
- jest.config.cjs
- packages/markdown/package.json
- packages/markdown/src/lib/deserializer/utils/deserializeMd.spec.tsx
- packages/markdown/src/lib/deserializer/utils/deserializeMd.ts
- yarn.lock
**Checklist**
Addresses issue: https://github.com/udecode/plate/issues/3733
> fix: add strikethrough support to deserializeMd

- packages/heading/src/react/hooks/useTocSideBar.ts
> Fix scrolling container error.

- .changeset/hip-weeks-deny.md
- packages/playwright/package.json
- packages/suggestion/package.json
> fix: license

- .changeset/empty-keys-pull.md
- packages/selection/src/react/BlockSelectionPlugin.tsx
> Add duration in addSelectedRow

- .changeset/nasty-eyes-smile.md
- packages/comments/src/lib/queries/getCommentFragment.ts
- packages/comments/src/lib/queries/index.ts
- packages/comments/src/lib/types.ts
- packages/comments/src/react/components/CommentNewSubmitButton.tsx
- yarn.lock
> Store `initialFragment` on TComment

- apps/www/content/docs/collaboration.mdx
- apps/www/public/r/index.json
- apps/www/src/__registry__/index.tsx
- apps/www/src/registry/registry-ui.ts
**Checklist**
Fixing a couple of issues with the docs for the yjs collaborative cursors component.
> doc: fix registry component location and issue in plugin config docs

- .changeset/cold-berries-tan.md
- packages/math/src/lib/utils/getEquationHtml.ts
>  Add getEquationHtml

- .changeset/brave-candles-approve.md
- apps/www/content/docs/ai.mdx
- apps/www/content/docs/components/changelog.mdx
- apps/www/src/registry/default/components/editor/plugins/comments-plugin.tsx
- apps/www/src/registry/default/plate-ui/table-element.tsx
- packages/selection/src/react/transforms/removeBlockSelectionNodes.ts
- yarn.lock
> Fix block selection remove nodes

- .changeset/light-glasses-buy.md
- apps/www/content/docs/cn/components/changelog.mdx
- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/default/plate-ui/code-block-element-static.tsx
- apps/www/src/registry/default/plate-ui/code-block-element.tsx
- apps/www/src/registry/default/plate-ui/column-element-static.tsx
- apps/www/src/registry/default/plate-ui/column-group-element-static.tsx
- apps/www/src/registry/default/plate-ui/column-group-element.tsx
- apps/www/src/registry/default/plate-ui/equation-element-static.tsx
- apps/www/src/registry/default/plate-ui/equation-element.tsx
- apps/www/src/registry/default/plate-ui/media-audio-element-static.tsx
- apps/www/src/registry/default/plate-ui/media-audio-element.tsx
- apps/www/src/registry/default/plate-ui/media-embed-element.tsx
- apps/www/src/registry/default/plate-ui/media-file-element-static.tsx
- apps/www/src/registry/default/plate-ui/media-file-element.tsx
- apps/www/src/registry/default/plate-ui/media-placeholder-element.tsx
- apps/www/src/registry/default/plate-ui/media-video-element.tsx
- apps/www/src/registry/default/plate-ui/plate-element.tsx
- apps/www/src/registry/default/plate-ui/table-cell-element-static.tsx
- apps/www/src/registry/default/plate-ui/table-cell-element.tsx
- apps/www/src/registry/default/plate-ui/toc-element-static.tsx
- apps/www/src/registry/default/plate-ui/toc-element.tsx
- apps/www/src/registry/default/plate-ui/toggle-element-static.tsx
- apps/www/src/registry/default/plate-ui/toggle-element.tsx
- packages/core/src/lib/static/__tests__/with-attributes.spec.ts
- packages/core/src/lib/static/components/SlateElement.tsx
- packages/plate-utils/src/react/PlateElement.tsx
> Add relative to PlateElement as default

- .changeset/shy-pandas-tie.md
- packages/core/src/react/plugin/toPlatePlugin.ts
> Fix overrideEditor

- .changeset/tiny-shirts-join.md
- packages/core/src/lib/static/utils/getNodeDataAttributes.ts
> Fix lodash import

- .changeset/thick-walls-sip.md
- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/default/plate-ui/emoji-picker-search-bar.tsx
- packages/emoji/src/lib/BaseEmojiPlugin.ts
- packages/emoji/src/lib/constants.ts
- packages/emoji/src/lib/utils/EmojiLibrary/EmojiInlineLibrary.ts
- packages/emoji/src/lib/utils/IndexSearch/EmojiInlineIndexSearch.ts
- packages/emoji/src/react/utils/EmojiLibrary/EmojiFloatingLibrary.ts
> fix emoji data

- .changeset/tiny-adults-marry.md
- apps/www/content/docs/cn/dnd.mdx
- apps/www/content/docs/en/dnd.mdx
- packages/dnd/src/components/useDraggable.ts
- packages/dnd/src/components/useDropLine.ts
- packages/dnd/src/hooks/useDndNode.ts
- packages/dnd/src/hooks/useDragNode.ts
- packages/dnd/src/hooks/useDropNode.ts
- packages/dnd/src/transforms/onDropNode.spec.ts
- packages/dnd/src/transforms/onDropNode.ts
- packages/dnd/src/transforms/onHoverNode.spec.ts
- packages/dnd/src/transforms/onHoverNode.ts
- packages/dnd/src/types.ts
- packages/dnd/src/utils/getHoverDirection.spec.ts
- packages/dnd/src/utils/getHoverDirection.ts
> Improve performance of drag and drop

- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/default/plate-ui/equation-popover.tsx
- apps/www/src/registry/default/plate-ui/inline-equation-element.tsx
- yarn.lock
> When selecting an inline equation, the popover should not open, as it causes the selection to be lost.

- .changeset/perfect-donkeys-ring.md
- packages/slate/src/interfaces/editor/editor-transforms.ts
> Move nodes type

- .changeset/forty-emus-repeat.md
- packages/basic-marks/src/react/SubscriptPlugin.tsx
- packages/basic-marks/src/react/SuperscriptPlugin.tsx
- yarn.lock
> Fix incorrect shortcut keys for subscript and superscript plugins

- .changeset/great-parrots-push.md
- packages/core/src/react/plugin/PlatePlugin.ts
> fix: fix type of NodeWrapperComponentReturnType

- .changeset/thin-pears-judge.md
- apps/www/content/docs/cn/api/core/plate-plugin.mdx
- apps/www/content/docs/en/api/core/plate-plugin.mdx
- apps/www/src/registry/default/plate-ui/draggable.tsx
- packages/ai/src/react/copilot/renderCopilotBelowNodes.tsx
- packages/core/src/lib/plugin/SlatePlugin.ts
- packages/core/src/react/plugin/PlatePlugin.ts
- packages/indent-list/src/lib/renderIndentListBelowNodes.tsx
- packages/toggle/src/react/renderToggleAboveNodes.tsx
> refactor: update types and docs of aboveNodes and belowNodes

- .changeset/slimy-shrimps-vanish.md
- packages/ai/src/react/ai-chat/hooks/useChatChunk.ts
> fix: Braces were missing

- .changeset/olive-mayflies-drum.md
- packages/selection/src/react/components/BlockSelectionAfterEditable.tsx
- packages/selection/src/react/utils/pasteSelectedBlocks.ts
- packages/selection/src/react/utils/selectInsertedBlocks.ts
- yarn.lock
> Fix block selection paste

- .changeset/rotten-mugs-joke.md
- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/default/plate-ui/block-suggestion.tsx
- packages/suggestion/src/lib/diffToSuggestions.ts
- packages/suggestion/src/lib/transforms/getSuggestionProps.ts
- yarn.lock
> Fix diffToSuggestions

- apps/www/src/registry/default/components/editor/plugins/editor-plugins.tsx
- yarn.lock
> fix trigger mention

- .changeset/weak-ravens-impress.md
- packages/dnd/src/hooks/useDragNode.ts
> Fix stale `dragItem.element` causing incorrect drag operations

- .changeset/flat-turtles-turn.md
- packages/indent-list/src/lib/normalizers/normalizeIndentListStart.spec.tsx
- packages/indent-list/src/lib/transforms/toggleIndentList.spec.tsx
- packages/indent-list/src/lib/withIndentList.ts
> Fix indent list normalizations

- .changeset/brown-tigers-stare.md
- packages/markdown/src/lib/serializer/serializeMdNodes.ts
**Checklist**
If you paste a node with an empty text followed by a custom element followed by text, the serializer returns early.
This PR fixes the detection of an empty text editor. 
```
[
{
"text": ""
},
{
"children": [
{
"text": ""
}
],
"type": "sanitized_inline_html",
"value": "<img src=\"image url\" width=\"20\" height=\"12\" alt=\"Lix Icon\"/>",
"id": "GtiMTLfLLG"
},
{
"text": " "
},
{
"text": "some text in bold",
"bold": true
},
{
"text": ": some normal text"
}
]
```
> fixes empty value detection

- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/registry-ui.ts
> fix: add missing `button` dependency to `tooltip` component

- apps/www/content/docs/en/api/slate/editor-transforms.mdx
- packages/slate/src/interfaces/editor/editor-transforms.ts
**Checklist**
[fixes docs - wrong parameter name](https://github.com/udecode/plate/commit/abd6335ec65b6dac5544d4e8ad7fc382bc8ec9dc)
> fixes docs - wrong parameter name

- packages/callout/README.md
> typo: callout doco

- README.md
- tooling/CONTRIBUTING.md
Small PR - Commit 0177d5f29b22eaa7a6e70748fbabf9c4e0b9e1c6 moved `CONTRIBUTING.md`. This PR adjusts sources to changes.
> Update continuation guide

- .changeset/selfish-doors-deliver.md
- packages/node-id/src/lib/withNodeId.ts
> fix conditional to remove duplicate id

- .changeset/wet-ladybugs-care.md
> markdown docs

- .changeset/slimy-vans-collect.md
- apps/www/src/registry/default/examples/markdown-to-slate-demo.tsx
- packages/markdown/src/lib/deserializer/__snapshots__/deserializeMdList.spec.tsx.snap
- packages/markdown/src/lib/deserializer/deserializeMdList.spec.tsx
- packages/markdown/src/lib/roundTrip.spec.tsx
- packages/markdown/src/lib/rules/defaultRules.ts
> Support for GitHub Flavored Markdown del, fix task list during deserialization

- .changeset/sixty-pumas-matter.md
- apps/www/src/registry/default/examples/markdown-to-slate-demo.tsx
- packages/markdown/src/lib/deserializer/utils/deserializeInlineMd.ts
> Add options for deserializeInlineMd

- apps/www/src/registry/default/examples/markdown-to-slate-demo.tsx
> line break

- .changeset/metal-trees-lay.md
- packages/markdown/package.json
- packages/markdown/src/lib/rules/defaultRules.ts
> removes underscore dependency

- .changeset/olive-hounds-compete.md
- apps/www/content/docs/en/markdown.mdx
- apps/www/src/registry/default/components/editor/plugins/markdown-plugin.tsx
- apps/www/src/registry/default/examples/markdown-to-slate-demo.tsx
- packages/markdown/src/lib/deserializer/deserializeMd.ts
- yarn.lock
> make remarkMention optional

- .changeset/few-pandas-care.md
- packages/selection/src/react/hooks/useBlockSelectable.ts
- packages/selection/src/react/transforms/duplicateBlockSelectionNodes.ts
- yarn.lock
> Fix open block menu shouldn't lose block selection when selecting multiple blocks.

- .changeset/nice-hornets-call.md
> fix release

- .changeset/olive-bulldogs-visit.md
- packages/markdown/src/lib/deserializer/deserializeMd.spec.tsx
- packages/markdown/src/lib/rules/defaultRules.ts
> Fix Markdown Deserialization to Handle KDB HTML Tags

- apps/www/content/docs/cn/debugging.mdx
- apps/www/content/docs/en/debugging.mdx
Simple change to add some docs about using the redux devtools for debugging.
@felixfeng33 - could you double check the mandarin for me? I used GPT/translate
> Add note about redux devtools to the debugging docs.

- .changeset/brown-wombats-jump.md
- packages/markdown/src/lib/rules/defaultRules.ts
- packages/markdown/src/lib/serializer/__snapshots__/serializeMd.spec.ts.snap
- packages/markdown/src/lib/serializer/serializeMd.spec.ts
- yarn.lock
> fix codeblock serialization if plate tree is not normalized

- .changeset/three-teachers-smash.md
- packages/markdown/src/lib/__snapshots__/mdx.spec.tsx.snap
- packages/markdown/src/lib/mdx.spec.tsx
- packages/markdown/src/lib/roundTrip.spec.tsx
- packages/markdown/src/lib/rules/defaultRules.ts
- packages/markdown/src/lib/serializer/serializeMd.ts
> Fix mdx serialize

- .changeset/rude-dolls-pay.md
- .changeset/slow-squids-fold.md
- apps/www/content/docs/cn/ai.mdx
- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/i18n/getI18nValues.ts
- apps/www/src/registry/default/app/api/ai/command/route.ts
- apps/www/src/registry/default/components/editor/plugins/ai-plugins.tsx
- apps/www/src/registry/default/components/editor/use-chat.ts
- apps/www/src/registry/default/examples/playground-demo.tsx
- apps/www/src/registry/default/examples/values/cn/playground-value.tsx
- apps/www/src/registry/default/plate-ui/ai-leaf.tsx
- apps/www/src/registry/default/plate-ui/ai-loading-bar.tsx
- apps/www/src/registry/default/plate-ui/ai-menu.tsx
- packages/ai/src/lib/streaming/streamDeserializeMd.spec.tsx
- packages/ai/src/lib/streaming/streamDeserializeMd.ts
- packages/ai/src/lib/streaming/utils/escapeInput.ts
- packages/ai/src/lib/streaming/utils/nodesWithProps.ts
- packages/ai/src/react/ai-chat/AIChatPlugin.ts
- packages/markdown/src/lib/deserializer/deserializeMd.spec.tsx
- packages/markdown/src/lib/deserializer/deserializeMd.ts
- yarn.lock
> Fix ai streamming

- .changeset/afraid-balloons-march.md
- apps/www/content/docs/en/components/changelog.mdx
- apps/www/src/registry/default/app/api/ai/command/route.ts
- packages/ai/src/lib/streaming/streamInsertChunk.spec.tsx
- packages/ai/src/lib/streaming/streamInsertChunk.ts
- packages/ai/src/lib/streaming/utils/getIndentListNode.ts
- packages/ai/src/lib/streaming/utils/isSameNode.ts
- packages/ai/src/lib/streaming/utils/nodesWithProps.ts
> Fix streaming indent list

- apps/www/content/docs/cn/ai.mdx
- apps/www/content/docs/cn/api/core/plate-plugin.mdx
- apps/www/content/docs/cn/api/slate/_slate.mdx
- apps/www/content/docs/cn/api/slate/editor-api.mdx
- apps/www/content/docs/cn/api/slate/editor-transforms.mdx
- apps/www/content/docs/cn/api/slate/element.mdx
- apps/www/content/docs/cn/api/slate/location-ref.mdx
- apps/www/content/docs/cn/api/slate/location.mdx
- apps/www/content/docs/cn/api/slate/node.mdx
- apps/www/content/docs/cn/api/slate/operation.mdx
- apps/www/content/docs/cn/api/slate/path.mdx
- apps/www/content/docs/cn/api/slate/point.mdx
- apps/www/content/docs/cn/api/slate/range.mdx
- apps/www/content/docs/cn/api/slate/text.mdx
- apps/www/content/docs/cn/api/utils.mdx
- apps/www/content/docs/cn/comments.mdx
- apps/www/content/docs/cn/components/changelog.mdx
- apps/www/content/docs/cn/copilot.mdx
- apps/www/content/docs/cn/debugging.mdx
- apps/www/content/docs/cn/indent-list.mdx
- apps/www/content/docs/cn/markdown.mdx
- apps/www/content/docs/cn/suggestion.mdx
- apps/www/content/docs/cn/table.mdx
- apps/www/content/docs/cn/troubleshooting.mdx
- tooling/scripts/translate.mjs
> update Chinese docs to latest

- package.json
- tooling/config/tsup.config.ts
**Checklist**
- [] `yarn changeset`
fix https://github.com/udecode/plate/issues/4299
> fix: build error in window with entry parser

- .changeset/young-mangos-sneeze.md
- packages/selection/src/internal/types.ts
- packages/selection/src/react/internal/api/setSelectedIds.ts
> Fix: ChangedElements

- .changeset/good-scissors-learn.md
- packages/core/src/react/components/EditorHotkeysEffect.tsx
- yarn.lock
> stopPropagation

- .changeset/core-async-init-patch.md
- apps/www/src/registry/examples/installation-next-04-value-demo.tsx
- apps/www/src/registry/examples/playground-demo.tsx
- apps/www/src/registry/ui/block-draggable.tsx
- docs/(guides)/controlled.mdx
- docs/(guides)/editor.mdx
- docs/api/core.mdx
- docs/api/core/plate-controller.mdx
- docs/api/core/plate-editor.mdx
- docs/installation/manual.mdx
- docs/installation/next.mdx
- docs/installation/react.mdx
- packages/core/src/lib/editor/withSlate.ts
- packages/core/src/lib/plugins/slate-extension/transforms/init.spec.ts
- packages/core/src/lib/plugins/slate-extension/transforms/init.ts
- packages/core/src/react/components/Plate.spec.tsx
- packages/core/src/react/components/PlateContent.tsx
- packages/core/src/react/editor/usePlateEditor.ts
- packages/core/src/react/editor/withPlate.ts
- packages/core/src/react/utils/pluginRenderElement.tsx
> Support synchronous value

- .changeset/tender-horses-beg.md
- packages/selection/src/react/BlockSelectionPlugin.tsx
> Remove useless block selection code

- docs/(plugins)/(elements)/list-classic.cn.mdx
- docs/(plugins)/(elements)/list-classic.mdx
> chore(docs): update usage example for list-classic in toolbars

- .changeset/khaki-ligers-fly.md
- packages/udecode/react-utils/src/useComposedRef.ts
- yarn.lock
> feat: support unref callback in composeRef

- .changeset/core-patch-getselecteddomfragment.md
- packages/core/src/lib/static/utils/getSelectedDomFragment.tsx
> fix getSelectedDomFragment

- .changeset/markdown-patch.md
- apps/www/src/app/dev/c.tsx
- apps/www/src/registry/components/editor/editor-base-kit.tsx
- apps/www/src/registry/components/editor/plugins/list-classic-kit.tsx
- packages/markdown/src/lib/deserializer/utils/customMdxDeserialize.ts
- packages/markdown/src/lib/deserializer/utils/markdownToSlateNodesSafely.ts
- packages/markdown/src/lib/rules/defaultRules.ts
- packages/markdown/src/lib/serializer/convertNodesSerialize.ts
- packages/markdown/src/lib/serializer/standardList.spec.tsx
> Fix indent list when custom paragraph node type

- .changeset/smooth-dnd-preview.md
- apps/www/src/registry/ui/block-draggable.tsx
- docs/components/changelog.mdx
- packages/dnd/src/components/useDraggable.ts
- packages/dnd/src/hooks/useDndNode.ts
- packages/dnd/src/hooks/useDragNode.ts
> Fix dnd preview

- apps/www/src/registry/ui/block-draggable.tsx
- docs/components/changelog.mdx
> Fix table dnd

- .changeset/neat-walls-mix.md
- apps/www/src/registry/blocks/editor-ai/components/editor/plate-editor.tsx
- apps/www/src/registry/blocks/editor-basic/components/editor/plate-editor.tsx
- packages/core/package.json
- packages/slate/package.json
- packages/slate/src/interfaces/node.ts
- packages/test-utils/package.json
- yarn.lock
> Slate 0.118

- .changeset/fast-moles-pay.md
- packages/ai/src/react/ai-chat/AIChatPlugin.ts
- packages/ai/src/react/ai-chat/utils/applyAISuggestions.ts
- packages/ai/src/react/ai-chat/utils/submitAIChat.ts
> Fix ai try again

- .changeset/hot-seals-shake.md
- packages/ai/src/react/ai-chat/AIChatPlugin.ts
- packages/ai/src/react/ai-chat/utils/resetAIChat.ts
> Add option `undo` to ai api

- .changeset/fix-ai-menu-block-selection.md
- .changeset/selection-fix-ai-menu-patch.md
- apps/www/src/registry/components/editor/plugins/ai-kit.tsx
- apps/www/src/registry/components/editor/plugins/block-selection-kit.tsx
- docs/components/changelog.mdx
- packages/selection/src/react/BlockSelectionPlugin.tsx
- packages/selection/src/react/components/BlockSelectionAfterEditable.tsx
> Fix can't open ai menu when block selected
