udecode/plate

packages/slate-plugins/src/elements/code/components/ToolbarCode.tsx
packages/slate-plugins/src/elements/code/components/index.ts
packages/slate-plugins/src/elements/code/index.ts
packages/slate-plugins/src/elements/code/transforms/index.ts
packages/slate-plugins/src/elements/code/transforms/toggleCode.ts
stories/plugins/elements.stories.tsx

The default toggleBlock function creates several code blocks if there are multiple paragraphs selected. This fix creates a toggleCode function that just wraps the whole selection in a code block - or unwraps if it is already in a block.
It's the behavior we want from the code block - so I just created a PR in case it is of general interest. The toggle-part with wrap + unwrap is pretty general - maybe it could be made into some kind of alternative toggleBlock thing? withBlock could possibly expose two alternative toggle functions?

Toggle code block as one

---

packages/slate-plugins/package.json
packages/slate-plugins/src/index.ts
packages/slate-plugins/src/paste-md/deserializeMd.ts
packages/slate-plugins/src/paste-md/index.ts
packages/slate-plugins/src/paste-md/withPasteMd.ts
stories/config/initialValues.ts
stories/plugins/paste-md.stories.tsx
yarn.lock

Paste Markdown content and format it correctly:
* tree-shakable plugin added
* storybook example added
* Tests (WIP)
In order to make it work, this plugin parse twice the content (MD -> HTML -> Slate). it's using `marked` to parse MD to HTML, and there is a way to parse to Slate directly. Would love some help from the community to achieve it.

paste-md plugin added

---

packages/slate-plugins/src/marks/components/ToolbarMark.tsx
packages/slate-plugins/src/marks/index.ts
packages/slate-plugins/src/marks/onKeyDownMark.ts
packages/slate-plugins/src/marks/subscript/SubscriptPlugin.ts
packages/slate-plugins/src/marks/subscript/deserializeSubscript.ts
packages/slate-plugins/src/marks/subscript/index.ts
packages/slate-plugins/src/marks/subscript/renderLeafSubscript.tsx
packages/slate-plugins/src/marks/subscript/types.ts
packages/slate-plugins/src/marks/superscript/SuperscriptPlugin.ts
packages/slate-plugins/src/marks/superscript/deserializeSuperscript.ts
packages/slate-plugins/src/marks/superscript/index.ts
packages/slate-plugins/src/marks/superscript/renderLeafSuperscript.tsx
packages/slate-plugins/src/marks/superscript/types.ts
packages/slate-plugins/src/marks/transforms/clearMark.ts
packages/slate-plugins/src/marks/transforms/index.ts
packages/slate-plugins/src/marks/types.ts
stories/plugins/marks.stories.tsx
stories/plugins/playground.stories.tsx

Hello,
I am currently working on a Rich Text Editor based on this repository. One of the requirements I have is to also include **superscript** and **subscript**. I have decided to publish it here as separate plugins.
I have used standard HTML `<sub>` and `<sup>` tags without any additional styling so anyone can style them as pleased.
The only problem I have run into is that the material-ui icon set does not include superscript and subscript icons. I have decided to use arrow up and arrow down for these. If anyone has any better idea I am open :-)

Add superscript and subscript plugins

---

packages/slate-plugins/src/elements/mention/useMention.ts

fixes #100 
Makes filtering for names in the mention plugin a bit more permissive. With this change substrings can be used instead of only the beginning of the name. 
I noticed that some characters cannot be used e.g. typing `@R2-`, when the user types `-` the suggestion popup gets closed. Will open a separate issue for that.

[mentions] change from startsWith to include

---

packages/slate-plugins/src/deserializers/deserialize-md/index.ts
packages/slate-plugins/src/deserializers/deserialize-md/utils/filterBreakLines.ts
packages/slate-plugins/src/deserializers/deserialize-md/utils/index.ts
packages/slate-plugins/src/deserializers/deserialize-md/withDeserializeMd.ts

Issue: #128 
- fix main function export
- separate utils (filterBreakLines) from main plugin
- normalize file structure like `withDeserializeHtml`
- Is this testable with Jest? Yes!, will add a test for it!
- Does this need a new example in Storybook? Nop!
- Does this need an update to the documentation? Nop!

fix(deserializeMd): fix export + separate utils

---

packages/slate-plugins/src/elements/mention/MentionPlugin.ts
packages/slate-plugins/src/elements/mention/components/MentionElement.tsx
packages/slate-plugins/src/elements/mention/renderElementMention.ts
packages/slate-plugins/src/elements/mention/types.ts
stories/element/inline-void/mention.stories.tsx

Issue:
Currently there is no way of adding an onclick handler to a MentionElement.
fixes #132 . Created a factory function for generating the MentionElement, which makes it possible to pass in directly options to it.
Added it to the mentions example in the storybook.

add onclick to MentionElement

---

packages/slate-plugins/src/__tests__/elements/mention/MentionSelect/at/null.spec.tsx
packages/slate-plugins/src/__tests__/elements/mention/MentionSelect/at/range.spec.tsx
packages/slate-plugins/src/elements/mention/components/MentionSelect.styles.ts
packages/slate-plugins/src/elements/mention/components/MentionSelect.tsx
packages/slate-plugins/src/elements/mention/components/MentionSelect.types.ts
packages/slate-plugins/src/elements/mention/useMention.tsx
stories/element/inline-void/mention.stories.tsx

Issue:
fixes #133 
- added `onMouseDown` to `MentionSelectBase`
- exposed an `onAddMention` function from `useMention`
- which should be passed in to the `MentionSelect` when setting up the editor
It feels a bit hacky not using the `onClick`, but that messes up the `selection` in the editor somehow, so I looked at the `ToolbarButton` for inspiration, and that uses `onMouseDown` too.
Click in the storybook when mention selection shows up.

selection works with mouse

---

packages/slate-plugins/src/marks/subscript/types.ts
packages/slate-plugins/src/marks/superscript/types.ts

Fixed the casing of types for Superscript and Subscript plugin to make it consistent with rest of the types.

Make casing of sub/sup type consistent

---

packages/slate-plugins/src/marks/highlight/renderLeafHighlight.tsx

Use `<mark>` html tag for HighlightPlugin render.

Use mark html tag for highlights

---

packages/slate-plugins/src/__tests__/serializers/serialize-html/htmlSerialize.spec.ts
packages/slate-plugins/src/serializers/serialize-html/serializeHTMLFromNodes.ts

Fixes: #172 
I am no longer taking a first mark plugin and applying it, I am instead taking all mark plugins that apply and apply them one by one. See tests for better explanation.

Serialize multiple marks on one leaf to html correctly

---

packages/slate-plugins/src/elements/table/components/ToolbarTable.tsx
packages/slate-plugins/src/elements/table/deserializeTable.ts
packages/slate-plugins/src/elements/table/queries/isTableCell.ts
packages/slate-plugins/src/elements/table/renderElementTable.tsx
packages/slate-plugins/src/elements/table/types.ts
stories/config/initialValues.ts

`<th>` tag are ignored
Fixes:
Fix serialization with html input containing `<th>`  tag
Add th type and render same component as td. Style can be applied using data attribute
Update the table initialValue with th type in the first row to check if it was working

add th support for table

---

packages/slate-plugins/src/common/queries/getSelectionNodesByType.ts
packages/slate-plugins/src/elements/list/transforms/toggleList.ts

When user selects block content with triple click, selection touches an adjacent block and transforming affects it:
Demo: https://codesandbox.io/s/nifty-frost-6ciri?file=/src/App.tsx
Fixed demo: https://codesandbox.io/s/epic-cartwright-p7xim?file=/src/App.tsx

Fix nested blocks toggling

---

packages/slate-plugins/src/common/plugins/inline-void/withInlineVoid.ts
packages/slate-plugins/src/common/queries/getNodesByType.ts
packages/slate-plugins/src/common/queries/getPointBefore.ts
packages/slate-plugins/src/common/transforms/setPropsToNodes.ts
packages/slate-plugins/src/common/transforms/toggleMark.ts
packages/slate-plugins/src/common/transforms/unwrapNodesByType.ts
packages/slate-plugins/src/common/utils/getNodeDeserializer.ts
packages/slate-plugins/src/common/utils/getRenderElement.tsx
packages/slate-plugins/src/common/utils/getRenderLeaf.tsx
packages/slate-plugins/src/common/utils/setDefaults.ts
packages/slate-plugins/src/handlers/autoformat/withAutoformat.ts

Though for a while Lodash promoted the ability to treeshake automatically, we have found that doesnt seem to work in any of our cases (we've tried the babel/webpack plugin and run into [similar issues as others](https://github.com/lodash/babel-plugin-lodash/issues/236).
Anyways, in our build we noticed slate-plugins was bundling a large part of lodash:
I'm hoping by using the per method approach, the build process will properly treeshake and reduce that footprint.
Replaced all imports of Lodash functions with the named function import

Minimize Lodash Footprint

---

packages/slate-plugins/src/common/queries/getPreviousBlockById.spec.ts
packages/slate-plugins/src/common/queries/getPreviousBlockById.ts

Dropping an element above a list was nesting the dropped element instead of inserting it above the list.
Issue isn't happening on stories, not really sure why, but see added test case to reproduce the issue. Without the newly added code, it fails the test.
Used `getBlockPathById` and `Editor.previous` to get the previous block.

Fix dropping element above a list

---

packages/slate-plugins/src/dnd/__tests__/selectable.spec.tsx
packages/slate-plugins/src/dnd/components/getSelectableElement.tsx
stories/examples/dnd.stories.tsx

The draggable component was being shown in readOnly mode
Return non-draggable component if `readOnly`

Don't show draggable component if readOnly

---

packages/slate-plugins/src/components/Toolbar/BalloonToolbar/index.ts

Exported useBalloonShow & useBalloonMove so they can be used in custom components.

Export balloon hooks

---

packages/slate-plugins/src/dnd/utils/getHoverDirection.ts

`getHoverDirection` seems to be triggered in some unrelated mouse events with `clientOffset` as `null` which causes a `Cannot read property 'y' of null` error. 
Early return if `clientOffset` is null.

Fix null clientOffset

---

packages/slate-plugins/src/elements/list/__tests__/withList.test.tsx
packages/slate-plugins/src/elements/list/queries/isSelectionInListItem.ts
packages/slate-plugins/src/elements/list/withList.ts
stories/elements/list.stories.tsx

After inserting an image within a list, pressing enter removes the image and the list hierarchy is broken.
- Allow to press enter on the image and continue with the list: Create a new list item
- Allow to press shift-enter on the image to insert a soft-break: Create a new line without making a new list item.

Fix image in list

---

packages/slate-plugins/src/elements/table/transforms/addColumn.ts
packages/slate-plugins/src/elements/table/withTable.ts
stories/config/initialValues.ts

- `th` headers were added by default & was not consistent with `insertTable`. 
- `th` cells were being deleted when removing content
- Removed default `th` creation until there's better consistency for adding headers.
- Added `th` cells to `preventDeleteCell`
- Updated story to use table without headers to be more consistent with `insertTable`

Remove default table headers

---

packages/slate-plugins/src/dnd/components/Selectable.tsx
packages/slate-plugins/src/dnd/hooks/useDropBlockOnEditor.ts

- Dropping an element doesn't work when hovering over the gutter
- Moving an element into a sibling path cause the element to go 1 position above what it should be
- Include gutter into droppable zone by using `rootRef` in place of `blockRef`
- Fixes dropping an element on sibling paths by
1) Ensure that the depth of the tree is maintained when dropping an item on a sibling path
2) Fix the condition used to check if the source path is before the destination path by accounting for sibling paths.

Fix dropping an item on sibling paths

---

packages/slate-plugins/src/dnd/hooks/useDndBlock.ts

I wanted to be able to use the provided `useDndBlock` hook, except remove the drag preview in order to use a custom drag image.
Added an optional boolean argument `removePreview` to the useDndBlock hook.

Add removePreview option to useDndBlock

---

packages/slate-plugins/src/elements/link/types.ts
packages/slate-plugins/src/elements/link/withLink.ts

I can't configure options used to get beforeWordRange
add new params in withLink function. I also keep default configuration option

IMP(withlink): allow custom range before options

---

packages/slate-plugins/src/elements/table/__tests__/withTable.spec.ts
packages/slate-plugins/src/elements/table/withTable.ts

#284 
- Don't delete a cell if deleting forward/backward next to a table by checking the location next to the current selection
- Don't delete cells if partially selecting a table by checking if a selection starts or ends within a table cell
- Don't delete cells on `insertText` if multiple cells are selected
- Delete content on `deleteFragment`. Currently, it's just doing an early return but we probably want to allow clearing the table contents without deleting the cells. @zbeyens any thoughts on the best way to achieve that?

Don't delete table cells. Closes #284

---

packages/slate-plugins/src/elements/table/__tests__/fixtures.ts
packages/slate-plugins/src/elements/table/__tests__/withTable.spec.ts
packages/slate-plugins/src/elements/table/withTable.ts

My previous PR #298 introduced a bug that was preventing to do valid deletions within a cell.
- Fixed the bug by using the same logic used for preventing cell deletions when the selection is inside the cell
- Added a test to check for valid deletions within a cell while preventing deleting the cell
- Moved fixtures into its own file

Fix deletions within a cell

---

packages/slate-plugins/src/deserializers/deserialize-md/utils/parseMD.ts

Turned out it's because of `blockquote` option uses https://github.com/udecode/slate-plugins/blob/master/packages/slate-plugins/src/deserializers/deserialize-md/utils/parseMD.ts#L37 `ELEMENT_PARAGRAPH`
More about it in [slack discussion](https://slate-js.slack.com/archives/C013QHXSCG1/p1603049816086800)
- [] The stories still work (run `yarn storybook`).
Couldn't run it locally because of issues with my local setup 
```
ERROR in ./packages/slate-plugins/src/index.ts
Module not found: Error: Can't resolve '@udecode/slate-plugins-core'
```

Fixes blockquote MD deserialization

---

packages/slate-plugins/src/elements/todo-list/components/TodoListElement.styles.ts
packages/slate-plugins/src/elements/todo-list/components/TodoListElement.tsx
packages/slate-plugins/src/elements/todo-list/types.ts
stories/config/autoformatRules.ts

- `todo-list`:
- use `user-select: none` in the checkbox wrapper to fix selection bug.
- `checked` can be undefined
- autoformat: `[]` will set a todo list item

fix-todo-list

---

packages/core/src/types.ts
packages/slate-plugins/src/serializers/serialize-html/__tests__/with-serialize.spec.ts
packages/slate-plugins/src/serializers/serialize-html/serializeHTMLFromNodes.ts

- #305 - serialize HTML with override of default editor render
- added `serialize` as a plugin option.  it accepts `element` and `leaf` properties.
- `serializeHTMLFromNodes` will use `plugin.serialize.element` in place of `plugin.renderElement` and `plugin.serialize.leaf` in place of `plugin.renderLeaf`

feat: serialize option to override default render

---

packages/slate-plugins/src/elements/list/transforms/insertListItem.ts

When creating a new list item, all of the current marks (bold, italic, etc..) are lost.
Copy the marks from the current leaf node to the next

Continue using current marks on next list item

---

packages/core/src/__tests__/decoratePlugins/decorate-deps-without-plugin.spec.tsx
packages/core/src/__tests__/decoratePlugins/decorate-deps.spec.tsx
packages/core/src/components/EditablePlugins.tsx
packages/core/src/types.ts

Close #328
Added deps props to the slate plugin definition to match the deps props on the SlateEditable component.
Specifically `SlatePlugin` gets the following properties.
```ts
// Dependencies of `decorate`
decorateDeps?: any[];
// Dependencies of `renderElement`
renderElementDeps?: any[];
// Dependencies of `renderLeaf`
renderLeafDeps?: any[];
// Dependencies of `onDOMBeforeInput`
onDOMBeforeInputDeps?: any[];
// Dependencies of `onKeyDown`
onKeyDownDeps?: any[];
```
Regarding my test cases I was hoping to check somehow that memoization is working by checking `decorate.hasBeenCalledTimes(...)`. But decorate is called on every render so there isn't much to check. Now my test case basically checks that the component renders when decorate dependencies are passed. I can add similar test …

feat: plugin deps

---

packages/slate-plugins/src/common/transforms/moveChildren.ts
packages/slate-plugins/src/elements/list/__tests__/transforms/deleteListFragment.test.ts
packages/slate-plugins/src/elements/list/queries/getListRoot.ts
packages/slate-plugins/src/elements/list/queries/isList.ts
packages/slate-plugins/src/elements/list/queries/isSelectionInListItem.ts
packages/slate-plugins/src/elements/list/transforms/deleteListFragment.ts
packages/slate-plugins/src/elements/list/withList.ts

Resolves #65
Resolves #66
When deleting nodes from a list, children and siblings were often unexpectedly deleted. This was because children and siblings of deleted list items would be deleted as part of a hanging node when their parent list was deleted.
I added logic to expressly handle children deletions when a delete spanned a list item. Added tests to confirm the fix and also that undo does and will continue to work.

Fix deleting from start of list and deleting a fragment

---

packages/slate-plugins/src/common/types/PluginOptions.types.ts
packages/slate-plugins/src/components/StyledComponent/StyledComponent.types.ts
packages/slate-plugins/src/components/StyledComponent/StyledElement.tsx
packages/slate-plugins/src/deserializers/deserialize-html/__tests__/deserializeHTMLElement/custom-deserialize.spec.tsx
packages/slate-plugins/src/elements/align/types.ts
packages/slate-plugins/src/elements/blockquote/components/BlockquoteElement.tsx
packages/slate-plugins/src/elements/blockquote/types.ts
packages/slate-plugins/src/elements/code-block/components/CodeBlockElement.tsx
packages/slate-plugins/src/elements/code-block/types.ts
packages/slate-plugins/src/elements/heading/types.ts
packages/slate-plugins/src/elements/image/components/ImageElement.tsx
packages/slate-plugins/src/elements/image/types.ts
packages/slate-plugins/src/elements/link/components/LinkElement.tsx
packages/slate-plugins/src/elements/link/types.ts
packages/slate-plugins/src/elements/list/types.ts
packages/slate-plugins/src/elements/media-embed/components/MediaEmbedElement.tsx
packages/slate-plugins/src/elements/media-embed/types.ts
packages/slate-plugins/src/elements/mention/components/MentionElement.tsx
packages/slate-plugins/src/elements/mention/types.ts
packages/slate-plugins/src/elements/paragraph/types.ts
packages/slate-plugins/src/elements/table/components/TableElement/TableElement.tsx
packages/slate-plugins/src/elements/table/types.ts
packages/slate-plugins/src/elements/todo-list/components/TodoListElement.tsx
packages/slate-plugins/src/elements/todo-list/types.ts
packages/slate-plugins/src/serializers/serialize-html/__tests__/elements.spec.ts
packages/slate-plugins/src/serializers/serialize-html/__tests__/with-attributes.spec.ts

When you specify attributes for deserialization (for instance `img { deserialize { attributes: ['alt'] } }`), those captured attributes are not rendered / serialized by default, requiring a custom component to extract them from the `htmlAttributes` prop provided by `getRenderElement`
Included the `htmlAttributes` prop on all element components, so no additional custom component is needed in these cases.  This is in regards to this slack conversation: https://slate-js.slack.com/archives/C013QHXSCG1/p1605138123156100?thread_ts=1605113240.155700&cid=C013QHXSCG1

spread any element attributes on all Element components

---

.eslintrc.js
packages/slate-plugins/src/dnd/components/Selectable.styles.ts
packages/slate-plugins/src/dnd/components/Selectable.tsx
packages/slate-plugins/src/dnd/components/Selectable.types.ts
packages/slate-plugins/src/dnd/components/getSelectableElement.tsx
stories/examples/dnd.stories.tsx

Importing  @styled-icons from within packages source results in styled-components being included in slate-plugins bundle.
- Added `no-restricted-imports` rule to ensure @styled-icons won't be imported from within /packages source files,
- Removed `@styled-icons/material/DragIndicator` from Selectable component,
- Added optional dragIcon argument to getSelectableElement, 
- Updated drag and drop story to include DragIndicator icon previously used in Selectable component, so the story looks the same way it did before the change
Note: there is no default icon provided, also the dragIcon attribute is optional
[Initial pull request](https://github.com/udecode/slate-plugins/pull/356).

feat: remove styled components from bundle

---

packages/slate-plugins/src/common/types/PluginOptions.types.ts
packages/slate-plugins/src/common/utils/getRenderElement.tsx
packages/slate-plugins/src/elements/align/types.ts
packages/slate-plugins/src/elements/blockquote/types.ts
packages/slate-plugins/src/elements/code-block/types.ts
packages/slate-plugins/src/elements/heading/types.ts
packages/slate-plugins/src/elements/image/types.ts
packages/slate-plugins/src/elements/link/types.ts
packages/slate-plugins/src/elements/list/types.ts
packages/slate-plugins/src/elements/media-embed/types.ts
packages/slate-plugins/src/elements/mention/types.ts
packages/slate-plugins/src/elements/paragraph/types.ts
packages/slate-plugins/src/elements/table/defaults.ts
packages/slate-plugins/src/elements/table/types.ts
packages/slate-plugins/src/elements/todo-list/types.ts
packages/slate-plugins/src/serializers/serialize-html/__tests__/node-to-props.spec.ts

When adding `attributesToProps`, I was focused on the use case of formatting deserialized attributes in a way React wouldn't complain (eg. `colspan` attribute -> `colSpan` prop).  But there's a lot more potential here.  Rather than constraining the `attributesToProps` to only reference `element.attributes` it might also be great to look at `element.url` for a link element, or whatever custom node data one might add.  Additionally it might be helpful to introspect the slate `attributes`, the node's `children` and even `rootProps`.
I am replacing `attributesToProps(attributes)` with `nodeToProps({ attributes, element, children, rootProps })`.  I also moved this optional function out from `rootProps` to the parent object since it doesn't feel like it belongs inside `rootProps`.  I updated …

alternative to attributesToProps that provides more context

---

packages/slate-plugins/src/elements/list/transforms/deleteListFragment.spec.tsx
packages/slate-plugins/src/elements/list/transforms/deleteListFragment.ts
packages/slate-plugins/src/elements/list/transforms/moveListItemSublistItemsToList.spec.tsx
packages/slate-plugins/src/elements/list/transforms/moveListItemSublistItemsToList.ts
packages/slate-plugins/src/elements/list/transforms/moveListItemSublistItemsToListItemSublist.ts

The fixes for #65 did not address the scenario where a non-standard type gets used in the editor (e.g. something besides ul/ol for lists).
Made certain that ListOptions gets passed to getListItemSubList if specified to override the default.

consistent pass list options to getListItemSubList to support AST types

---

packages/slate-plugins/src/elements/list/transforms/moveListItemSublistItemsToListItemSublist.spec.tsx
packages/slate-plugins/src/elements/list/transforms/removeRootListItem.ts

One more possible complication related to #65
Make sure list options get passed via the removeRootListItem code path also.

verify list options passed via removeRootListItem codepath

---

packages/slate-plugins/src/elements/list/normalizers/normalizeListItem.ts

In an ordered list, pressing tab to indent a child was pushing the ordered list item to the wrong place in the tree.
A bit more severe, changing a nested list item from unordered to ordered with a custom ast grammar was causing an infinite insertion of p elements until giving up. Related, I have no idea why this normalization was ignoring the ast options getting passed in, but there may be somewhere in the codebase where a normalization rule is ignoring or not getting passed options, but I don't see it.
Allow ol as a valid child type of li (in addition to p and ul). While it could be argued that the user should need to specify ol as a valid child type, the behavior for this bug was particularly challenging to track down, and it was also result

allow list items to have ol as children

---

packages/slate-plugins/src/deserializers/deserialize-md/utils/parseMD.ts

parseMD is missing the code_block type from the options passed to remark-slate/unified
Added the missing type and a default value

Add missing code_block type to parseMD

---

packages/slate-plugins/src/elements/table/utils/getEmptyCellNode.ts

Partial fix towards respecting table normalization rules
getEmptyCellNode now accepts and sets option for p.type

respect ast type options for child p in getEmptyCellNode

---

packages/slate-plugins/src/common/utils/getNodeDeserializer.ts
packages/slate-plugins/src/deserializers/deserialize-html/__tests__/deserializeHTMLElement/match-on-attribute.spec.tsx
packages/slate-plugins/src/serializers/serialize-html/__tests__/with-serialize.spec.ts

While deserializing html from a 3rd party source, there's a few cases where the only distinguishing aspect of a DOM node is a unique attribute name.  To be able to deserialize this into a custom plugin, it would be great to make a deserialization rule that would match either an attribute name or an attribute name + value.
Expanded `GetNodeDeserializerRule` to take an optional attribute property that would subsequently match either if the attribute name (if given a string) is found or if the attribute name and one of its values is found (if given an object).

deserialization rule to match on either an attribute name or value

---

packages/core/src/types.ts
packages/slate-plugins/src/common/utils/getLeafDeserializer.ts
packages/slate-plugins/src/common/utils/getNodeDeserializer.ts
packages/slate-plugins/src/deserializers/deserialize-html/__tests__/deserializeHTMLElement/element-without-children.spec.tsx
packages/slate-plugins/src/deserializers/deserialize-html/utils/deserializeHTMLToElement.ts

While deserializing, an element may include children elements that are not meaningful in the slate document or may be problematic.  It would be handy to create a single element that could encapsulate information about its children (or ignore them) without them being explicitly represented in the slate document.  This would be helpful to control how a deserialized element is rendered in the slate document or serialized back out.
New `withoutChildren` optional property on `GetNodeDeserializerOptions` that, when true, will not add any children to the deserialized element.

node deserializer can instruct not to include children on its element

---

packages/slate-plugins/src/elements/image/__tests__/ToolbarImage/onMouseDown.spec.tsx
packages/slate-plugins/src/elements/image/components/ToolbarImage.tsx
packages/slate-plugins/src/elements/image/types.ts
stories/config/initialValues.ts

Image Upload is hard to be solved for a general use-case, the one provided by `withImageUpload` puts the content of the image into the model, which is problematic for  images event with a trivial size. 
Provided a `getImageUrl` prop to the `ToolbarImage`, which allows getting the url in an async manner, allowing e.g. opening a file picker, uploading it to `S3` and returning the public url at the end, to insert it into the model. 
- display an upload indicator
- make it work with drag-n-drop too

add getImageUrl prop to ToolbarImage

---

packages/core/src/utils/renderElementPlugins.tsx
packages/core/src/utils/renderLeafPlugins.tsx

#403
Wrap renderElement and renderLeaf with a Tag component wrapper, so all useContext call specially useSelected can get the correct value in the render function.

Add component wrapper for renderElement and renderLeaf calls.

---

packages/slate-plugins/src/elements/mention/components/MentionElement.tsx
packages/slate-plugins/src/elements/mention/types.ts

The onClick handler only works as a PoC at the moment, the value in itself allows only a limited functionality. 
mentionNode is passed to onClick, to support arbitrary actions based on other props.

extending mention onclick param 

---

packages/slate-plugins/src/elements/table/TablePlugin.ts
packages/slate-plugins/src/elements/table/onKeyDownTable.ts
packages/slate-plugins/src/elements/table/queries/getCellInNextTableRow.ts
packages/slate-plugins/src/elements/table/queries/getCellInPreviousTableRow.ts
packages/slate-plugins/src/elements/table/queries/getNextTableCell.ts
packages/slate-plugins/src/elements/table/queries/getPreviousTableCell.ts
packages/slate-plugins/src/elements/table/queries/getTableCellEntry.ts
packages/slate-plugins/src/elements/table/types.ts

When in a table cell, tab and shift-tab are common keyboard shortcuts to move to next or previous cell.
Added an `onKeyDown` handler for tables following the pattern for the list plugin, along with helpers to get the current and next/previous cell and logic to handle start/end of row and table.
Note: I have not written tests as I don't quite follow the syntax for the similar tests for lists. I could use help with that, or some guidance if possible. Thanks!
Note: Many rich text editors add a new row if you press tab in the last cell of a table. I did not implement this but left a TODO. If this is desired behavior it should be pretty easy to add.

enable tab/shift-tab between table cells

---

packages/slate-plugins/src/elements/list/transforms/insertListItem.ts

List item split failure
wrap the 3 operations with Editor.withoutNormalizing

Fix split list item failure.

---

packages/slate-plugins/src/elements/list/transforms/deleteListFragment.ts
packages/slate-plugins/src/elements/list/withList.ts

create a two-item list, then select the two items, delete, this will not only delete the list item content, also will cause the list be deleted. which is because internally, the deleteFragment is called again after the list content delete, due to the return value check.
Adjust the return value check of deleteListFragment, and also make sure it return undefined if it did not call transform 'delete'.

Prevent double delete fragment.

---

packages/slate-plugins/package.json
packages/slate-plugins/src/deserializers/deserialize-md/utils/parseMD.ts
packages/slate-plugins/src/elements/link/defaults.ts
packages/slate-plugins/src/elements/link/types.ts
yarn.lock

The markdown parser parses links and sets a link property rather than a url property (#350)
* Update to 1.4.0 of 'remark-slate' which recently added a `linkDestinationKey`
* Update slate-plugins defaults to make it easier to override the default
* Update `parseMD` to specify the `linkDestinationKey` based on defaults + options

fixes #350, markdown deserialize link property

---

packages/slate-plugins/src/common/__tests__/queries/isWordAfterTrigger/trigger-accent.spec.tsx
packages/slate-plugins/src/common/queries/isWordAfterTrigger.ts

When using useMention, if the variable names have accents in it, the RegExp won't match them. Eg. in French: 
| @pr | @pré |
| ---- | ------|
| ![image](https://user-images.githubusercontent.com/445045/104315633-89b76280-54db-11eb-8cd4-7d46620d220e.png) | ![image](https://user-images.githubusercontent.com/445045/104315663-91770700-54db-11eb-9cff-9f7e20d1761f.png) |
Tweak the RegExp so that accents characters are taken into accounts.
I've followed this RegExp pattern: https://stackoverflow.com/a/26900132
I could've used `\S` like in this example: https://codesandbox.io/s/mentions-forked-06ctt?file=/src/index.js:576-585, which is a non blank character, but thought of just adding accents for now.

Improve useMention to work with accents

---

packages/slate-plugins/src/serializers/serialize-html/__tests__/classNames.spec.ts
packages/slate-plugins/src/serializers/serialize-html/serializeHTMLFromNodes.ts

When deserializing html from various sources, a custom plugin could rely on a unique classname to match into that custom type.  Subsequently, when serializing that custom node, we would expect to be able to preserve that classname
```
<div class="spoiler">This text is a spoiler</div>
```
↕️
```
getElementDeserializer({
type: 'spoiler',
rules: [{ className: 'spoiler' }],
})
```
However, when using `serializeHTMLFromNodes`, all class names that are not `slate-` are stripped away.
Add a new optional `preserveClassNames` property to `serializeHTMLFromNodes` that allows one to opt-in other class names or class prefixes to be preserved from `stripClassNames`

optional array of classname prefixes to preserve from `stripClassNames`

---

packages/slate-plugins/src/serializers/serialize-html/__tests__/classNames.spec.ts
packages/slate-plugins/src/serializers/serialize-html/serializeHTMLFromNodes.ts

In the previous PR, `preserveClassNames` was not passed through when `serializeHTMLFromNodes` was called recursively for the children nodes.
Passed through `preserveClassNames` and added a test to verify

fix not passing preserveClassNames recursively

---

packages/slate-plugins/src/elements/code-block/decorateCodeBlock.ts
packages/slate-plugins/src/elements/code-block/types.ts

The decorate method for the CodeBlock plugin was not supporting options to override the default AST type
Following the pattern of other similar methods, the decorate method now reads the options and overrides the defaults.

CodeBlock plugin: decorate now supports overriding the AST type

---

stories/config/autoformatRules.ts

For the autoFormat story, the provided autoformatRules ignored the types passed in via options for marks (italic, bold, strikethrough, inline code).
Updated autoformatRules to retrieve the type from options.

Story autoformatRules preserve options type

---

packages/slate-plugins/src/elements/list/transforms/moveListItemUp.ts

fix Enter in sublistitem error
#454 
add withoutNormalizing

fix: moveListItemUp add withoutNormalizing #454

---

packages/slate-plugins/src/elements/link/components/ToolbarLink.tsx

Currently, there is no way of writing down something that matches the URL regex, without having it become a link.
And also there is no way of removing a link without deleting and rewriting the text.
When submitting an empty string in the link URL prompt, the selected node will be unwrapped from the link.

Unwrap links when entering an empty URL in the prompt

---

packages/slate-plugins/src/elements/code-block/index.ts

Missed an export of onKeyDownCodeBlock
Added the export to the code-block index.ts

missing export from code-block refactor

---

packages/slate-plugins/src/normalizers/withRemoveEmptyNodes.ts

Normalization is a multi-pass process in Slate. `withRemoveEmptyNodes` remove nodes, and therefore other normalization steps such as merging nodes are broken if we don't end the current normalization pass after. 
Refer to https://github.com/ianstormtaylor/slate/blob/master/docs/concepts/10-normalizing.md#multi-pass-normalizing
> When you do call `Editor.removeNodes`, you're actually changing the content of the node that is currently being normalized. So even though you're ending the current normalization pass, by making a change to the node you're kicking off a new normalization pass. This results in a sort of recursive normalizing.
Added a `return` statement to end the current normalization pass

Fix multi-pass normalization of withRemoveEmptyNodes

---

packages/slate-plugins/src/normalizers/withNormalizeTypes.ts
packages/slate-plugins/src/normalizers/withTrailingNode.ts

Follow-up to #515 
Fixes multi-pass normalization of `withNormalizeTypes` and `withTrailingNode` normalizers.
Added return statements to kick-off a new normalization pass after a transform is applied. In Slate, all transforms kick off a new normalization pass, and therefore it's important to early return to end the current normalization pass after a transform is applied in `normalizeNode`. 
Refer to https://github.com/ianstormtaylor/slate/blob/master/docs/concepts/10-normalizing.md#multi-pass-normalizing for more details

Fix multi pass normalization for withNormalizeTypes and withTrailingNode

---

packages/slate-plugins/src/elements/code-block/onKeyDownCodeBlock.ts

Addressed a fixme in code-block after the refactor
For code-block, removed a fixme and replaced with a comment explaining mod+enter/mod+shift+enter behavior

code-block, remove a fixme, add a comment

---

packages/slate-plugins/src/elements/list/transforms/insertListItem.ts

#480
Fix the issue by ensuring that selection will move to the beginning of nextListItem when split happens.

Fix split list item with mark

---

packages/slate-plugins/src/elements/table/withTable.ts

A noted in #431, when content is selected in a table cell and you attempt to type over that content, instead the selection is collapsed and content is added at the end.
Check to see if the start and end of the selection are in the same cell. If so, replace the selected content when typing

fixes #431, allow typing over selected content in single table cell

---

packages/slate-plugins/src/elements/code-block/transforms/insertCodeBlock.ts

`insertCodeBlock` was allowing the insertion of a code-block element inside an existing code-block element
Check to see if the selection is already a code-block or code-line. If so, return false.

prevent insertCodeBlock from nesting code-block elements

---

stories/elements/basic-elements.stories.tsx

I broke CodeBlock in the basic elements story in a recent commit
Restored CodeBlock in basic elements story

accidentally deleted invoking codeblock plugin in recent story update

---

packages/slate-plugins/src/elements/code-block/components/ToolbarCodeBlock.tsx
packages/slate-plugins/src/elements/code-block/defaults.ts
packages/slate-plugins/src/elements/code-block/transforms/insertEmptyCodeBlock.ts
packages/slate-plugins/src/elements/code-block/types.ts

Inserting code_block elements from the toolbar mid-paragraph was a bit inconsistent.
* If some text was selected, it would fail silently
* If no text was selected but it was mid-sentence, it would take the rest of the content and inject it into the code block
In general we're trying to avoid taking content and converting it to code_block content, at least for now.
* Added an `insertEmptyCodeBlock` transform to be called from the `ToolbarCodeBlock` `onmousedown` handler
* Added a couple of options, `defaultType` and `level` (these are not hooked into the normal `setDefaults` call, I could use guidance if there's a better way to do this)
* Check to see if the cursor either has an expanded selection, or a collapsed selection in the middle of an element. If so, insert a new block, select it, …

Insert code block below paragraph

---

packages/slate-plugins/src/elements/code-block/transforms/index.ts
packages/slate-plugins/src/elements/code-block/transforms/insertEmptyCodeBlock.ts

Missed a dependency in #549
Inverted logic of selected block being empty
Added missing dependency
Fixed the logic for checking if the block above the selection is empty

missing export, minor cleanup of insertEmptyCodeBlock transform

---

packages/slate-plugins/src/elements/list/transforms/index.ts

Newly created methods: insertBreakList & deleteBackwardList are not exported from the package.
Exported the two methods

Exports deleteBackwardList and insertBreakList transform methods.

---

packages/slate-plugins/src/elements/table/onKeyDownTable.ts

When focus is on a table, mod+a keyboard event was selecting the entire page rather than all contents of a table
refs #547 
Added a keyboard handler in `onKeyDownTable` to select the entire table when pressed.

add mod+a handler to select all contents of a table

---

packages/elements/mention-ui/src/MentionSelect/MentionSelect.spec.tsx
packages/elements/mention/src/types.ts
packages/elements/mention/src/useMentionPlugin.ts

Added searchValue in useMentionPlugin as before
Search value is not returned in the useMentionPlugin function I was having issues while I refactor the code to the new version. 
Added searchValue in the useMentionPlugin return data

Updated useMentionPlugin return data

---

packages/elements/code-block/src/getCodeBlockDecorate.ts

Code-block syntax highlighting is not working accurately (randomly highlighting keywords breaking the formatting. Also without a user mechanism to specify the language, having a default of JavaScript isn't ideal for many users.
Set the language to empty for now, and skip the application of syntax highlighting until we have time to investigate this further.

Disable code-block syntax highlighting until we resolve formatting issues

---

packages/elements/table/src/withTable.ts

Select table cells with mouse, delete, crash.
Delete cell content with reversed order.

Fix table delete content

---

packages/elements/mention/src/__tests__/useMention/onKeyDown/key/enter.spec.tsx
packages/elements/mention/src/useMentionPlugin.ts

When using the keyboard to select an item in the mention plugin, the selection was failing as the targetRange was getting cleared before the selection could occur. It is unclear how this is not an error in the CodeSandbox example (perhaps that environment has different behavior with respect to how events get fired).
Removed a call to clear the range (it gets cleared after the node gets inserted anyway).

Mention plugin was prematurely clearing targetRange with keyboard events

---

packages/core/src/types/SlatePlugin/Decorate.ts
packages/core/src/types/SlatePlugin/Deserialize.ts
packages/core/src/types/SlatePlugin/OnChange.ts
packages/core/src/types/SlatePlugin/OnDOMBeforeInput.ts
packages/core/src/types/SlatePlugin/OnKeyDown.ts
packages/core/src/types/SlatePlugin/RenderElement.ts
packages/core/src/types/SlatePlugin/RenderLeaf.ts
packages/core/src/types/SlatePlugin/SlatePlugin.ts

When building a plugin with a custom editor type, the typing for callback functions (`renderElement`, `onChange`, etc) cannot be changed when using the `SlatePlugin` interface.
I added a generic to the `SlatePlugin` interface and all callback functions (`renderElement`, `onChange`, etc), defaulting it to `SPEditor`. This will maintain the current typings but allow for custom typing as well.

Allow custom typing for editor in plugin, defaulting to SPEditor

---

packages/elements/media-embed/src/createMediaEmbedPlugin.ts
packages/elements/media-embed/src/getMediaEmbedDeserialize.ts
packages/elements/media-embed/src/transforms/index.ts
packages/elements/media-embed/src/transforms/insertMediaEmbed.ts

The media-embed plugin did not have an insert* transform like some other plugins such as table
Created a simple insertMediaEmbed transform which inserts a media-embed element.
Assuming this is good and lands, we should also update the toolbar examples in storybook to use it. Let me know if I should do that before we land this.

add insertMediaEmbed transform

---

packages/core/src/components/SlatePlugins.tsx
packages/core/src/hooks/useSlatePlugins/useSlatePlugins.ts
packages/core/src/hooks/useSlatePlugins/useSlatePluginsEffects.ts
packages/core/src/plugins/createInlineVoidPlugin.ts
packages/core/src/store/useSlatePluginsActions.ts
packages/core/src/types/SlatePluginsStore.ts
packages/core/src/types/UseSlatePluginsEffectsOptions.ts
packages/core/src/types/UseSlatePluginsOptions.ts
packages/core/src/utils/getInlineTypes.ts
packages/core/src/utils/getSlatePluginWithOverrides.ts
packages/core/src/utils/withSlatePlugins.ts
packages/elements/image-ui/src/ToolbarImage/ToolbarImage.fixtures.tsx
packages/serializers/html-serializer/src/deserializer/__tests__/withDeserializeHTML/html-empty.spec.tsx
packages/serializers/html-serializer/src/deserializer/__tests__/withDeserializeHTML/html.spec.tsx
packages/serializers/html-serializer/src/deserializer/__tests__/withDeserializeHTML/iframe-without-src.spec.tsx
packages/serializers/html-serializer/src/deserializer/__tests__/withDeserializeHTML/inline.spec.tsx
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLElement.ts
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLNode.ts
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLToDocumentFragment.ts
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLToElement.ts
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLToMarks.ts
packages/slate-plugins/src/__tests__/all-plugins.spec.tsx
packages/slate-plugins/src/utils/createEditorPlugins.ts
stories/deserializers/deserialize-html.stories.tsx
stories/examples/playground.stories.tsx

#640 allowed for better typings for custom editor types within plugins, but it is still necessary to cast the editor and plugins to the correct type when dealing with the plugin options.
Added generic typings around the plugin options and props, defaulting to `SPEditor`.

Add additional typings to avoid casting when working with a custom editor

---

packages/autoformat/src/__tests__/withAutoformat/block/code-block-middle.spec.tsx
packages/autoformat/src/__tests__/withAutoformat/inline/code-block.spec.tsx
packages/common/src/queries/index.ts
packages/common/src/queries/isType.ts
stories/config/autoformatRules.ts

I often want a quick way to determine if something is of a particular type which may include a custom ast type.
For autoformat, we currently have a few extensions to prevent lists from getting inserted into code-block elements and to insert an empty code_block element.
* Added isType (my type definition for node is currently an any, could use guidance on what this should be)
* Updated shared autoformatRules from stories

autoformat improvements and isType common query

---

packages/elements/media-embed/src/transforms/insertMediaEmbed.ts

With the `insertMediaEmbed` transform I added yesterday, the default of undefined was a bad idea when working in a collaborative environment
Switched the default type to null, updated the type defintion

fix default url type for insertMediaEmbed

---

packages/elements/media-embed/src/index.ts

Forgot to export transforms at the top-level of media-embed
Added an export

add missing export for insertMediaEmbed transform

---

.changeset/polite-goats-watch.md
packages/elements/mention/src/useMentionPlugin.ts

I need to highlight an active option. An option should become active when you navigate to it using keyboard or mouse.
**Issue**
Currently mention-plugin changes `valueIndex` only on keyboard navigation. It would be useful to change it `onMouseEnter` as well. For this purpose the `setValueIndex` need to be exposed.
--fix`.)
storybook`.)
[added a changeset](https://github.com/atlassian/changesets/blob/main/docs/adding-a-changeset.md)
if changing functionality. (Add one with `yarn changeset add`.)

[Mention plugin] expose setValueIndex for select

---

docs/docusaurus.config.js

Fix the following error when  running `yarn start` :
```
../packages/slate-plugins/src/index.tsx
Module not found: Can't resolve '@udecode/slate-plugins-placeholder' in '/home/jim/rien/slate-plugins/packages/slate-plugins/src'
```

fix missing placeholder alias in doc config

---

.changeset/polite-cars-tie.md
packages/elements/link-ui/src/ToolbarLink/ToolbarLink.tsx

Supporting "getLinkUrl" for "ToolbarLink". So we can customize input component.（Like ”getLinkUrl“ in ”ToolbarImage")
**Example**
```ts
import {ToolbarLink} from "@udecode/slate-plugins";
function getLinkUrl(prev: string | null): Promise<string | null> {}
<ToolbarLink getLinkUrl={getLinkUrl} />
```
--fix`.)

feat: supporting "getLinkUrl" for "ToolbarLink"

---

.changeset/violet-bees-deliver.md
packages/serializers/html-serializer/src/serializer/serializeHTMLFromNodes.ts

slate introduced a new data attribute `data-slate-leaf` that doesn't get stripped out in `serializeHtmlFromNodes`
--fix`.)

fix: strip new data-slate-leaf attributes

---

.changeset/tasty-wasps-explain.md
packages/marks/basic-marks/src/italic/createItalicPlugin.ts

Italic plugin uses Code plugin's deserializer by mistake. I fixed it.

Fix deserialization of italic plugin

---

.changeset/cold-lemons-taste.md
packages/serializers/html-serializer/src/serializer/__tests__/with-serialize.spec.ts
packages/serializers/html-serializer/src/serializer/serializeHTMLFromNodes.ts

Source problem is adding a leaf serializer ignores all previous serialization of that leaf. However similar `renderLeaf` plugin option works differently. It feeds preceding computation of `renderLeaf` to succeeding, so it looks like a cascade. I've made changes that serialization works in the same way.
**Example**
https://codesandbox.io/s/slate-plugins-playground-v1-forked-4146s?file=/index.tsx:0-54
--fix`.)

Fix calling leaf serializers with preceding serialization result

---

.changeset/blue-eels-mate.md
packages/common/src/__tests__/utils/normalizeDescendantsToDocumentFragment/default.spec.tsx
packages/common/src/utils/normalizeDescendantsToDocumentFragment.ts
packages/serializers/html-serializer/src/deserializer/__tests__/withDeserializeHTML/html.spec.tsx
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLToDocumentFragment.ts

Additionally to the handler of the first constraint (https://docs.slatejs.org/concepts/11-normalizing) I added a handler for 3rd one. The original problem was pasting HTML text that does not follow these rules. Say we have copied text that has such source:
```html
<p>Some text</p>
<p>Another paragraph text</p>
<a>Any inline element</a>
``` 
When we paste it to the editor it becomes:
```html
<p>Some text<a>Any inline element</a></p>
<p>Another paragraph text</p>
```
Personally I treat it as a bug, since Google Doc and Apple Notes paste it in original order. So my fix wraps such elements with a default block, like so:
```html
<p>Some text</p>
<p>Another paragraph text</p>
<p><a>Any inline element</a></p>
``` 
The PR mainly touches `normalizeDescendantsToDocumentFragment()`. …

Add normalization for 3rd constraint

---

.changeset/small-bottles-work.md
packages/elements/list/src/normalizers/normalizeListItem.ts

Documentation was referencing p instead of lic for list normalization rules
**Issue**
Code comments improvement
--fix`.)

Fix comments for list normalization

---

.changeset/many-birds-flow.md
packages/elements/list/src/normalizers/getListNormalizer.ts
packages/elements/list/src/normalizers/normalizeListItem.ts
packages/elements/list/src/withList.spec.tsx

List item normalization did not cover all scenarios, and in particular did not completely handle the change from using the default type (usually a paragraph) to a list item container.
**Issue**
Fixes scenarios and upgrades that would generate invalid list nesting
**Example**
It was pretty easy to end up with list item > list item container > paragraph > children rather than list item > list item container > children.
**Context**
New logic handles a variety of possible list normalization scenarios.
--fix`.)

List item container normalization

---

.changeset/good-hornets-crash.md
packages/elements/excalidraw/src/components/ExcalidrawElement/ExcalidrawElement.tsx

Excalidraw plugin was stealing focus/scroll onmount
**Issue**
Excalidraw no longer steals focus (though I do see a single frame flicker of the component)
**Example**
In the playground, when loading the page, it was scrolling to have Excalidraw in focus. With this change, there is a brief flicker but the scroll position does not change.
--fix`.)

prevent excalidraw from stealing focus

---

docs/docs/plugins/autoformat.mdx
docs/docs/plugins/exit-break.mdx
docs/docs/plugins/forced-layout.mdx
docs/docs/plugins/reset-node.mdx
docs/docs/plugins/soft-break.mdx

The Utils docs jump right into how to configure them, without answering the really basic question of "What does this
thing do?" This pull request adds a single line at the top, providing that answer.
**Issue**
N/A, it just tripped me up personally.
**Example**
N/A
**Context**
N/A
--fix`.)
Anyway, Just want to say thanks for this project. It's a big help!

Add 'What it does' line to Utils doc pages.

---

.changeset/shy-trees-swim.md
docs/src/live/config/initialValues.tsx
packages/elements/list/src/createListPlugin.ts
packages/elements/list/src/getListOnKeyDown.ts
packages/elements/list/src/normalizers/getListNormalizer.ts
packages/elements/list/src/normalizers/normalizeListItem.ts
packages/elements/list/src/queries/getListItemEntry.ts
packages/elements/list/src/transforms/moveListItemDown.ts
packages/elements/list/src/transforms/moveListItemUp.ts
packages/elements/list/src/transforms/unwrapList.ts

By @newageoflight
Adds multiple indents/dedents for lists and adding hotkeys to toggle lists.
**Issue**
Fixes: #552 
**Example**
**Context**
--fix`.)

Adds multiple indenting and dedenting, list hotkeys 

---

.changeset/clean-penguins-peel.md
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

Update the markdown deserializer code to be more similar to the html and ast deserializers
**Issue**
Trying to make sure paste from markdown works consistently.
**Example**
I had a few scenarios where the formatting of the first element was lost. Not sure yet if this fixes that.
**Context**
If your change is non-trivial, please include a description of how the
new logic works, and why you decided to solve it the way you did.
--fix`.)

Deserialize markdown refinements

---

.changeset/fair-squids-teach.md
packages/serializers/ast-serializer/src/deserializer/createDeserializeAstPlugin.ts
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

* Ast deserializer should have used insertFragment instead of insertNodes
* Reuse firstNodeType variable in all deserializers
**Issue**
Ast deserializer was inserting at the wrong ast level
**Example**
**Context**
--fix`.)

Improve logic for ast deserialize insert

---

.changeset/spicy-carrots-run.md
packages/serializers/ast-serializer/src/deserializer/createDeserializeAstPlugin.ts
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

If your ast is non-standard, you may need to override the fragment root (most likely only for ast, but for consistency adding the option for all deserializers)
**Issue**
With a non-standard ast structure, you can end up with the wrong type applied to the first node that gets pasted.
**Example**
**Context**
--fix`.)

Deserialize override fragment root

---

.changeset/gold-planes-dance.md
packages/elements/list/src/getListDeserialize.ts

Allow customization of ELEMENT_LIC deserializer, just as all other elements allow it.
**Issue**
Fixes: https://github.com/udecode/slate-plugins/issues/816
**Example**
```
createSlatePluginsComponents({
[ELEMENT_LIC]: withProps(StyledElement, {
as: 'span',
}),
})
```
--fix`.)

added deserializer for ELEMENT_LIC

---

.changeset/shiny-snakes-listen.md
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

Markdown deserializer was breaking the pasting of a simple URL into the editor. This fix checks the content and if it's simply a URL, it skips the handling of the content as markdown.
**Issue**
Fixes: #800
**Example**
See #800
**Context**
See #800
--fix`.)

Markdown deserializer should not block simple URL paste, fixes #800

---

.changeset/fresh-months-serve.md
packages/serializers/ast-serializer/src/deserializer/createDeserializeAstPlugin.ts
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

If the fragment is empty in a deserializer, it potentially blocks the calling of the next deserializer up the tree. This change should fix that scenario
**Issue**
See description
**Example**
I don't have a good example, but the logic to simply return felt less accurate than an explicit call to insertData.
**Context**
--fix`.)

deserializers: if no fragment to deserialize, call insertData and return

---

.changeset/modern-kangaroos-invent.md
packages/slate-plugins/package.json

Missed a dependency for the new csv-serializer in the top-level slate-plugins
**Issue**
Missed a dependency for the new csv-serializer in the top-level slate-plugins
--fix`.)

missed adding csv-serializer to slate-plugins package.json

---

.changeset/fair-schools-appear.md
docs/docs/guides/creating-plugins.mdx
packages/core/src/hooks/useSlatePlugins/useSlateProps.ts
packages/core/src/types/SlatePlugin/DOMHandlers.ts
packages/core/src/types/SlatePlugin/OnChange.ts
packages/core/src/utils/pipeHandler.ts
packages/core/src/utils/pipeOnChange.ts

Before, the handlers had to return `false` to prevent the next handlers to be called.
Now, we reuse `isEventHandled` internally used by `slate@0.65.0` which has the opposite behavior: a handler has to return `true` to stop the pipeline.
Additionally, the pipeline stops if at any moment `event.isDefaultPrevented()` or `event.isPropagationStopped()` returns `true`, except if the handler returns `false`.
See the updated docs in "Creating Plugins".
--fix`.)

core-prevent-default

---

.changeset/heavy-poems-cheat.md
packages/elements/list/src/transforms/toggleList.ts
packages/elements/list/src/withList.ts

The recent normalization update at https://github.com/udecode/slate-plugins/blob/main/packages/elements/list/src/normalizers/getListNormalizer.ts#L37 was causing the ul or ol to get removed before the li gets added to the tree. This change wraps the contents of toggleList in a withoutNormalizing block to prevent normalization from kicking in before the list item gets inserted.
**Issue**
Fixes:  New lists can now get inserted again.
**Example**
See how the order was incorrect:
The playground would throw an error when attempting to insert a new list.
--fix`.)

Insert list was breaking due to premature normalization

---

.changeset/few-turkeys-hunt.md
packages/serializers/ast-serializer/src/deserializer/createDeserializeAstPlugin.ts
packages/serializers/csv-deserializer/src/deserializer/createDeserializeCSVPlugin.ts
packages/serializers/csv-deserializer/src/deserializer/utils/deserializeCSV.ts
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

When pasting from a slate-plugins list into another list, it was often causing normalization errors like this:
```
Uncaught Error: 
Could not completely normalize the editor after 966 iterations! This is usually due to incorrect normalization logic that leaves a node in an invalid state.
normalize https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
withoutNormalizing https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
normalize https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
withoutNormalizing https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
insertFragment https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
l https://slate-plugins.udecode.io/assets/js/5009.f5f344b9.js:2
insertData …
```

Fix paste list into a list normalization errors

---

.changeset/long-seahorses-check.md
packages/common/src/utils/getNodeDeserializer.ts

Do not deserialize empty styles
**Issue**
Fixes: #863 
--fix`.)

Fix empty style in deserialization

---

.changeset/little-horses-sip.md
packages/serializers/ast-serializer/src/deserializer/createDeserializeAstPlugin.ts
packages/serializers/csv-deserializer/src/deserializer/createDeserializeCSVPlugin.ts
packages/serializers/html-serializer/src/deserializer/createDeserializeHTMLPlugin.ts
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

The deserializers for handling pasted comments were not easy to override as there was no reference to the editor easily available. Also combined preInsert and insert for simplicity as there was not much utility in having them separate.
**Issue**
Fixes: 
**Example**
--fix`.)

Deserializer insert override

---

.changeset/hip-dodos-explain.md
packages/elements/media-embed-ui/src/MediaEmbedElement/MediaEmbedUrlInput.tsx

When adding something via an iframe embed, many services automatically place the full embed code into the copy buffer, whereas our plugin only wants the src/url. This update inspects the value and if it's obviously not a URL, it attempts to extract the value of the src attribute to save users time and reduce the opportunity for errors.
**Issue**
Nothing was broken so much as this saves users a step or two.
**Example**
--fix`.)

Parse Media-Embed paste for src value

---

docs/docs/plate/contributing.md

There was an extra (dot) in the markdown link, and the link itself 404’d. This PR removes the dot and provides a working link

Fix link in contributing.md

---

.changeset/chilled-ties-knock.md
packages/elements/media-embed-ui/src/MediaEmbedElement/MediaEmbedUrlInput.tsx

Media embed regex breaks Safari due to it not yet supporting regex look behind.
My solution is somewhat of a cop out (I don't know a good way to feature detect Safari's lack of regex look behind, and other attempts I made at an older style regex syntax fail for at least one of my embed examples). I'm happy to replace this with a better regex, but I want to unbreak the release for Safari users as a higher priorty.
**Issue**
Fixes: #880
**Example**
--fix`.)

Safari regex

---

.prettierrc

This has no impact on the code, but it will enable contributors to use prettier and it will no longer conflict with eslint when it comes to quotes or trailing comma.

fix prettier quote config and trailingComma to match eslint settings

---

.changeset/wise-ads-tan.md
packages/serializers/csv-serializer/src/deserializer/utils/deserializeCSV.ts

CSV check was not sufficient as it would create tables from single blocks of text.
**Issue**
Fixes: Check to make sure it's at least a 2x2 table before handling as csv.
**Example**
--fix`.)

CSV detection was getting triggered for plain text paste

---

.changeset/curvy-crews-scream.md
packages/elements/table/src/transforms/deleteColumn.ts

Typo in deleteColumn code was not referring to TH and TD, but TD twice
**Issue**
Fixes: #899
**Example**
--fix`.)

fix(table) typo in deleteColumn, fixes #899

---

.changeset/dirty-elephants-yawn.md
packages/elements/table/src/queries/getTableCellEntry.ts
packages/elements/table/src/transforms/addColumn.ts
packages/elements/table/src/utils/getEmptyCellNode.ts
packages/elements/table/src/withTable.ts

Some of our logic for working with table cells was referencing TD twice instead of TD and TH.
**Issue**
Fixes: #947
--fix`.)

bug: some table cell calls were missing th

---

.changeset/shiny-wolves-build.md
docs/yarn.lock
packages/elements/list/src/getListOnKeyDown.ts

List plugin was preventing all tab key strokes without checking if a list item was being selected. This PR makes this check before preventing the `Tab`.
**Issue**
Fixes: #892 
**Example**
https://www.loom.com/share/b9da77d94b2047e6984b028ebc3f8c7d
--fix`.)

Don't prevent tab if list is not selected

---

.changeset/great-years-lick.md
packages/serializers/md-serializer/src/deserializer/createDeserializeMDPlugin.ts

When pasting a file, on Firefox content was showing the URL triggering markdown parsing. Instead if there's a file in the paste buffer, markdown parsing should not get triggered.
**Issue**
Markdown parser was winning over image or file attachment when processing pasted content.
--fix`.)

Prevent markdown deserializer from working on attachments

---

docs/docs/plugins/list.mdx

Fix wrong url from link to list.
Fix url in this page.
https://plate.udecode.io/docs/plugins/list#source-code
**Issue**
Fixes: none. document only.
**Example**
--fix`.)

Fix docs typo

---

.changeset/shy-bugs-shave-2.md
.changeset/shy-bugs-shave-3.md
.changeset/shy-bugs-shave.md
packages/elements/mention-ui/src/MentionSelect/MentionSelect.tsx
packages/elements/mention-ui/src/MentionSelect/MentionSelect.types.ts
packages/ui/styled-components/src/PortalBody/PortalBody.tsx
packages/ui/styled-components/src/PortalBody/PortalBody.types.ts
packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.tsx
packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.types.ts

Allow PortalBody to be mounted on a custom container. Using `document.body` can conflict with other portals with the same container
--fix`.)

Allow PortalBody to be mounted on a custom container

---

.changeset/nice-ties-hope.md
packages/elements/mention/src/transforms/insertMention.ts
packages/placeholder/src/components/Placeholder.tsx

Before 
https://user-images.githubusercontent.com/24937683/132167778-710d301c-0203-4bfc-9f4b-b10c2209150b.mov
After 
https://user-images.githubusercontent.com/24937683/132167817-798e9c0e-2bf3-4a94-80e8-40c954a5b410.mov
The placeholder overlaps with the mention element if the node is empty. So added empty space to the mention node when creating it. Please let me know if you have any better fix than this.
**Issue**
Fixes: 
**Example**
--fix`.)

fix: mention & placeholder

---

.changeset/breezy-rats-end.md
packages/common/src/queries/findNode.ts
packages/elements/list/src/getListInsertFragment.spec.tsx
packages/elements/list/src/getListInsertFragment.ts

Insert all nested list items next to the lowest li in selection.
The current logic inserts lis next to top level li, and fails to insert nested lis altogether. See example for more details.
**Example**
* refactored `findNode` to use Editor.nodes, as it appears to have been doing the same thing, but was missing certain functionality from Editor.nodes such as `mode`
* open to suggestions on `getFirstAncestorOfType`

Fix nested list paste

---

.changeset/tasty-dolls-judge.md
packages/elements/table/src/utils/getEmptyTableNode.ts

`insertTable` with `header=true` marks all cells as header elements. I think it only makes sense to mark the first row as header (if enabled).
What do you think?
--fix`.)

fix(table): only mark first row as table header

---

.changeset/selfish-rockets-compare.md
packages/elements/table/src/queries/getTableCellEntry.ts

A tiny if-condition fix to check for both `ELEMENT_TD` AND `ELEMENT_TH` in the `getTableCellEntry` helper. That enables pressing TAB to jump to the next Header cell and SHIFT+TAB to jump to the previous one
--fix`.)

fix(table): jump to next header cell on TAB

---

.changeset/rare-dingos-mix.md
packages/autoformat/src/transforms/autoformatMark.ts
packages/serializers/html-serializer/src/deserializer/__tests__/deserializeHTMLToDocumentFragment/codeblock.spec.tsx
packages/serializers/html-serializer/src/deserializer/utils/deserializeHTMLToDocumentFragment.ts
packages/serializers/html-serializer/src/serializer/__tests__/elements.spec.ts
packages/serializers/html-serializer/src/serializer/serializeHTMLFromNodes.ts
packages/serializers/html-serializer/src/serializer/utils/htmlStringToDOMNode.ts

As described in #954, this PR adds the ability to turn off whitespace stripping from the html de/serialize. Which in turn allows codeblocks/blockquotes to have new lines.
**Broken Example**
```
const hello = 'world';
console.log(hello);
```
ran through serializeHTMLFromNodes
becomes:
<pre class="slate-CodeBlockElement"><code>const hello = 'world';console.log(hello);</code></pre>
This PR corrects that by retaining the whitespace.
- Not really a TS developer
- Not sure how much these changes will break existing functionality.
--fix`.)

Allow deserializeHTMLToDocumentFragment, serializeHTMLFromNodes to retain whitespace

---

.changeset/perfect-bobcats-tickle.md
packages/common/src/queries/isSelectionAtBlockEnd.ts
packages/elements/list/src/getListDeleteForward.ts
packages/elements/list/src/getListOnKeyDown.ts
packages/elements/list/src/transforms/indentListItems.ts
packages/elements/list/src/transforms/moveListItems.ts
packages/elements/list/src/transforms/removeListItem.ts
packages/elements/list/src/transforms/unindentListItems.ts
packages/elements/list/src/withList.spec.tsx
packages/elements/list/src/withList.ts

Fix data loss on list delete forward. This was not implemented before, so nested lists were being deleted.
Left current, right PR
Have some extra refactorings i made during the process, not really needed but i believe they are useful. I can remove any extra work if needs be.

Fix list delete forward

---

.changeset/blue-camels-cry.md
packages/elements/table/src/transforms/addColumn.ts

When inserting a new column to an existing table, the current implementation of the `addColumn` transform only allows for all table cells to be a header at once (`TH`) or none at all. However, most of the time, you usually want the top row of cells to remain as a table header and all other instances as standard `TD` cells.
This PR allows the flexibility for the header option to be more consistent with the current table row that we're iterating through when inserting a new column 🙂  
To maintain backwards compatibility, I've made sure that this only happens if the header option is not set. If the header option is already configured when calling `addColumn`, then this will override the default behaviour for all table cell instances.
--fix`.)

Adds more natural default header option when inserting table columns

---

.changeset/polite-owls-taste.md
packages/serializers/md-serializer/src/deserializer/utils/deserializeMD.ts

Add additional nodeTypes to markdown deserializer for marks. Note, I'd like to also add underline, subscript, and superscript, but those are not currently supported by remark-slate so we'll need to raise a PR there first and then revisit here.
**Issue**
Fixes: Clearer deserialization of marks from markdown.
--fix`.)

More markdown nodetypes

---

.changeset/long-impalas-occur.md
packages/elements/list/src/getListInsertFragment.spec.tsx
packages/elements/list/src/normalizers/normalizeListItem.ts

When pasting list item, normalize first li child is ignored. Specify the location of the firstLiChildPath should fix it
**Issue**
Pasting list first child not getting normalized
Fixes: 
**Example**
https://codesandbox.io/s/plate-playground-forked-7i3w8?file=/index.tsx
https://user-images.githubusercontent.com/11587066/133574631-4a57a653-eaf2-4dd5-809e-e2493ff59300.mp4
--fix`.)

Fix first LIC normalize on paste

---

.changeset/lucky-boats-drive.md
packages/common/src/queries/findNode.spec.tsx
packages/common/src/queries/findNode.ts

This PR fixes the `findNode` function
**Issue**
If does not respect the given `at` attribute from the options
**Fix**
Provide default `at` value before the `options` spread.

fix: findNode when path is provided

---

.changeset/cyan-bulldogs-attend.md
packages/elements/link/src/__tests__/withLink/insertData/insert-url-over-link.spec.tsx
packages/elements/link/src/withLink.ts

Hi folks. 👋🏼 Just a small behavior change to get started as a contributor.
This PR modifies the behavior of the `link` plugin when **pasting a URL**.
Previously, pasting any text (including a URL) with an existing link selected would insert plain text. With this change, pasting a URL will unwrap any selected links and wrap a new link.
For example, if the pipes below represents the editor selection:
> For more information [please |**click**](https://google.com) **here**|.
and the user pastes a URL, e.g. `https://yahoo.com`, then the result would be:
> For more information, please [click here](https://yahoo.com).
--fix`.)

feat(link): Unwrap selected links when pasting a URL

---

.changeset/forty-socks-grin.md
packages/elements/list/src/getListDeleteForward.spec.tsx
packages/elements/list/src/getListDeleteForward.ts
packages/elements/list/src/queries/getListItemEntry.ts
packages/elements/list/src/withList.spec.tsx

There are a couple of scenarios that the current `deleteForward` in the list plugin does not handle properly.
I made a couple of tests that describe these scenarios
Also I reworked the `getListItemEntry` so it would be a bit more lenient when it comes to finding listItem and list.
It should not affect the earlier applications, but with this it is not so hard to provide a proper path for it.

feat: handle edge case scenarios when it comes to deleteForward

---

packages/elements/list/src/getListDeleteForward.ts

Clean up for `getListDeleteForward` so it can convey the intention of early returns much better without comment and unnecessary internal variables.

refactor: remove unneccessary skipDefaultDelete internal variable

---

.changeset/strange-impalas-protect.md
.changeset/strong-cars-shave.md
.changeset/tame-mails-chew.md
.changeset/twelve-wolves-sell.md
packages/elements/list-ui/src/ToolbarList/ToolbarList.tsx
packages/elements/list/src/normalizers/getListNormalizer.spec.tsx
packages/elements/list/src/normalizers/getListNormalizer.ts
packages/elements/list/src/normalizers/normalizeListItem.spec.tsx
packages/elements/list/src/normalizers/normalizeListItem.ts
packages/elements/list/src/transforms/insertListItem.ts
packages/elements/list/src/transforms/moveListItemDown.ts
packages/elements/list/src/transforms/moveListItemSublistItemsToListItemSublist.ts
packages/elements/list/src/transforms/moveListItems.ts
packages/elements/list/src/transforms/moveListItemsToList.ts
packages/elements/list/src/transforms/removeListItem.ts
packages/elements/list/src/transforms/toggleList.spec.tsx
packages/elements/list/src/transforms/toggleList.ts
packages/elements/list/src/transforms/unwrapList.ts
packages/ui/toolbar/src/ToolbarElement/ToolbarElement.tsx

List toggle had some issues when it came to changing type or revering it back to standard paragraphs this PR intends to fix those issues and it has a couple of test for the different usecases.
* Normalizer now merges lists with the same type next to each other also if a list has no lic and it has children it moves those childrens up a level 
* toggleList works as expected (check tests)
* ToolbarElement now uses the provided active prop
* ToolbarList leverages this since the default ToolbarElement solution would activate both button if there is an unordered list within a ordered list.
* moveListItemDown wrap transformations in withoutNormalizing (it caused a pathing issue since the normalization would remove the created empty list)

fix: toggleList

---

packages/autoformat/src/__tests__/withAutoformat/block/code-block.spec.tsx

One of the tests was broken from the recent work in #1055
**Issue**
Fixes: broken test cases
--fix`.)

fix broken test

---

.changeset/forty-boats-unite.md
packages/elements/code-block/src/getCodeBlockInsertFragment.spec.tsx
packages/elements/code-block/src/getCodeBlockInsertFragment.ts
packages/elements/code-block/src/index.ts
packages/elements/code-block/src/withCodeBlock.ts

Pasting into a code block should paste only code lines:
* If pasting a code block into a code line, extract the code lines
* If pasting a non-code block block into a code line, extract the text

Fix code block paste

---

.changeset/selfish-carrots-shout.md
packages/elements/code-block-ui/src/CodeBlockElement/index.ts

Missed an export in the barrel for code-block-ui
**Issue**
Fixes: Missed an export in the barrel for code-block-ui
--fix`.)

Syntax highlight missing export

---

.changeset/smooth-squids-vanish.md
packages/elements/code-block-ui/src/CodeBlockElement/CodeBlockSelectElement.tsx

Missed key when interating over map of language names in #1055 .
--fix`.)

add missing key for iterating over languages for syntax highlighting

---

.changeset/odd-plums-join.md
packages/elements/code-block-ui/src/CodeBlockElement/CodeBlockSelectElement.tsx

Syntax highlighting select element was editable which causes all sorts of issues.
**Issue**
Fixes: Crashes when trying to edit a selection with the select element
--fix`.)

Syntax highlighting not editable

---

.changeset/happy-days-rush.md
docs/src/live/config/initialValues.tsx
packages/elements/code-block/src/getCodeBlockDecorate.ts
packages/elements/code-block/src/getCodeLineDecorate.ts

The condition for verifying the parent of a code_line was a code_block was not quite right. Also restricting to text only was not allowing all syntax highlighting to get applied.
--fix`.)

Syntax highlighting apply tokens

---

.changeset/fast-pandas-dance.md
packages/elements/code-block-ui/src/CodeBlockElement/CodeBlockSelectElement.tsx

Click events on the select element were bleeding click events up the tree to causing the select element to close prematurely due to focus events firing on the editor.
**Issue**
Fixes: dropdown won't close prematurely.
**Example**
--fix`.)

Syntax highlighting propagation

---

.changeset/thick-phones-listen.md
packages/core/src/hooks/usePlate/useSlateProps.ts

> If I pass the state value to plate it re-renders the whole editor for each change and the editor was insanely slow. But after stops passing the value to plate, the editor performance was good.
Fix: memoize onChange

fix-onChange-memo

---

.changeset/good-points-reply.md
packages/autoformat/src/transforms/autoformatMark.ts
packages/common/src/transforms/removeMark.ts

* it simplifies `removeMark`
* enables the usage of array of marks 
* adds the ability to specify the location of the operation instead of just limiting it to editor.selection

feat: refactor removeMark with multiple marks and location options

---

packages/autoformat/src/transforms/autoformatMark.ts
packages/common/src/transforms/setMarks.ts
packages/common/src/transforms/toggleMark.ts

Remove mark can now handle arrays as input, so functions that uses removeMark could be leverage that.
@zbeyens I added `withoutNormalize` to some of the functions I'm not 100% sure if it's needed, but it seemed logical to me, please check them.

refactor: functions that use removeMark

---

docs/docs/getting-started/basic-plugins.mdx

As I was reading through the docs I came across this error on the "Basic plugins" page: `ReferenceError: components is not defined`. I thought I'll just go ahead and fix it as it looked like an easy one.
**Issue**
`ReferenceError: components is not defined` error shown on the `"Basic plugins"` documentation page.
Fixes: #1192 
**Example**
https://plate.udecode.io/docs/basic-plugins
--fix`.)

docs: fix live code for basic plugins documentation

---

.changeset/hungry-spies-rest.md
docs/src/live/config/mentionables.ts
packages/elements/mention-ui/src/MentionCombobox/MentionCombobox.tsx
packages/elements/mention/CHANGELOG.md
packages/elements/mention/src/getMentionOnSelectItem.ts
packages/ui/combobox/src/combobox.store.ts
packages/ui/combobox/src/components/Combobox.styles.ts
packages/ui/combobox/src/components/Combobox.tsx
packages/ui/combobox/src/components/Combobox.types.ts
packages/ui/combobox/src/types/ComboboxOnSelectItem.ts

Make the MentionCombobox a generic component, as to be able to infer or provide the data property.
**Example**
What we want to achieve:
```tsx
<MentionCombobox<UserData>
items={users.map(user => ({
key: user.id,
text: user.fullName,
data: {
fullName: user.fullName,
avatar: user.avatar,
},
}))}
createMentionNode={item => ({
fullName: item.data.fullName,
})}
onRenderItem={({ item }) => <SuggestedMention user={item.data} />}
/>
```
Basically typescript complains if the data is incorrect, which was not the case so far - it was an unknown.

Make ComboboxProps a generic with an TItemData parameter

---

.changeset/fast-eagles-camp.md
packages/ui/button/package.json

I noticed this error in my app:
> react_devtools_backend.js:2540 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.
It didn't manifest in any bugs but after tracing things down I was pretty confident we weren't loading 2 versions of the styled components module (I've seen this error many times over the years 🤦 ). From the error I noticed it was coming from `@udecode/plate-ui-button`, and upon inspection I saw that it wasn't listing `styled-components` as a peer dependency even though it does get used. It was also compiled to a 74kb size. After listing `styled-components` as a …

Ensure styled-components doesn't get bundled with `@udecode/plate-ui-button`

---

.changeset/four-llamas-join.md
packages/core/src/common/queries/getPointBefore.ts
packages/elements/link/src/__tests__/withLink/insertText/space-after-url-across-blocks.spec.tsx
packages/elements/link/src/createLinkPlugin.ts

Closes #1215 
Looks like the call to `getRangeBefore` was spanning across multiple paths. I don't know if this was intentional or if there are any downstream consequences of changing this, but setting `multiPaths: false` in the `rangeBeforeOptions` object seems to fix the bug in #1215.
**Note:** lots of tests are currently failing, so could not test to pass successfully / build etc. I'm getting lots of "Unable to resolve path to module" errors. See screenshot below. Is this just me? If so, how do I fix?
--fix`.)

Fixes link upsert on space 

---

.changeset/afraid-doors-own.md
packages/core/src/common/queries/getPointBefore.ts
packages/marks/font-ui/src/ColorPicker/ColorPicker.spec.tsx
packages/marks/font-ui/src/ColorPicker/ColorPicker.tsx
packages/marks/font-ui/src/ColorPickerToolbarDropdown/ColorPickerToolbarDropdown.spec.tsx
packages/marks/font-ui/src/ColorPickerToolbarDropdown/ColorPickerToolbarDropdown.tsx

added additional property to check the open status in react memo comparison.
Fixes: 
#1271 
--fix`.)

Bug Fix - Color picker does not close on first selection

---

packages/core/src/plugins/createInsertDataPlugin.ts
packages/core/src/plugins/html-deserializer/utils/pipeDeserializeHtmlElement.ts
packages/core/src/plugins/html-deserializer/utils/pipeDeserializeHtmlLeaf.ts
packages/serializers/docx/src/deserializer/__tests__/testDocxDeserializer.tsx

when trying to add customized insertData plugin for insertData, after the call, because of the change of the plugins order, our own plugin is not get called first. this change is to ensure the execution of plugin logics consistent every time.

avoid plugins array been changed

---

.changeset/long-shoes-battle.md
packages/nodes/table/src/transforms/insertTable.ts
packages/serializers/docx/src/deserializer/__tests__/testDocxDeserializer.tsx

Fixes: #1216 the cursor is not in the first cell for newly created table. because in slate, it always set cursor to end of newly inserted node
**Solution**
set the cursor to the first cell once the table is inserted.

set the cursor to the first cell for new table

---

.changeset/green-lobsters-judge.md
packages/nodes/code-block/src/decorateCodeLine.ts

1. Open the plate playground,
2. Go to developer Tools of Chrome, click the Sources tab
enable the Pause on caught exceptions
3. add a Code block from plate editor
4. Browser paused and complain `Error: Cannot get the parent path of the root path [].`
**Issue**
decorateCodeLine don't check the path of nodeEntry
Fixes: 
in decorateCodeLine.ts
if path length is equal to zero, just return
**Example**
--fix`.)

fix error popup in browser console  when adding a code block

---

docs/src/components/Home/Header.tsx

As a user I expect that a link named "GitHub" opens the repository.

Update GitHub link

---

.changeset/long-ravens-talk.md
packages/core/src/hooks/usePlate/useEditableProps.ts

Fixes #1357.
`keyPlugins` was updating whenever plugins changed _but_ since `keyPlugins` was outside of the `useMemo` calls, `isValid` never updated.
I initially attempted to wrap `isValid` in a `useMemo` but doing that caused the type refinement to think that `editor` _could_ be `undefined`. As a result, I removed `isValid` and instead passed `keyPlugins` to everywhere that used `isValid` as a defendency to the `useMemo`.
This is now working as desired.

use keyPlugins in useMemos of useEditableProps (fix decorate)

---

.changeset/calm-parents-type.md
packages/decorators/find-replace/src/__tests__/decorateSearchHighlight/search/text.spec.ts
packages/decorators/find-replace/src/decorateFindReplace.ts

`find-replace` should highlight case-insensitive findings as the default behaviour (https://github.com/udecode/plate/discussions/1411)

Support case-insensitive matching

---

.changeset/cold-falcons-crash.md
packages/editor/combobox/package.json

`@udecode/plate-combobox` has an unnecessary peer dep on `styled-components` which prevents installing `@udecode/plate-headless` without also adding `styled-components`

Remove unnecessary peer dep in combobox

---

.changeset/big-carrots-change.md
packages/core/src/common/__tests__/queries/isType/type.spec.tsx
packages/core/src/common/queries/isType.ts

This pull request addresses #1446. Instead of attempting to return from within a `forEach`, this solution utilizes the same `forEach` to build a map of plugin types. It then uses `Array.prototype.includes()` to check if the node type exists in the map.
You can see a working example of this solution here: https://codesandbox.io/s/plate-playground-forked-qsd5ly?file=/index.tsx
1. Move the cursor into the paragraph field.
2. Click the Test Type button in the toolbar.
3. Check the console.
Example return values from the sandbox:

Fixes #1446: Update isType to return expected boolean value.

---

.changeset/hip-experts-punch.md
packages/core/src/plugins/html-serializer/__tests__/elements.spec.ts
packages/core/src/plugins/html-serializer/serializeHtml.ts

(from the original issue  #1189)
On adding a image into editor the serialized nodes gets url encoded.
This HTML serialized node
<p class="slate-p">the post body without any images and a smiley ✅</p><p class="slate-p"></p>
becomes
<p class="slate-p">the%20post%20body%20without%a%20image%20and%20a%20smiley%20%E2%9C%85</p>
On adding a image url using <ToolbarImage />
**Solution**
The fix is to perform decoding per node, rather than full object.

Fix Url encoded HTML nodes on adding an image #1189

---

.changeset/small-buckets-help.md
packages/editor/combobox/src/onKeyDownCombobox.ts

add event.stopPropagation() in addition to  event.preventDefault();
Fixed the issue on Chrome.

fix the issue of ComboBox Enter and Tab event propagate to editor on Chrome

---

.changeset/spicy-foxes-poke.md
packages/editor/break/src/exit-break/onKeyDownExitBreak.ts
packages/editor/break/src/soft-break/onKeyDownSoftBreak.ts

Latest version of chrome seems to have changed some behavior with regards to input events, which results in newlines being added multiple times when enter is pressed with soft/exit break plugins enabled.
Similar to the issue fixed for combo boxes, in https://github.com/udecode/plate/pull/1483
https://user-images.githubusercontent.com/3934894/163037178-49c0975c-1872-4a77-b073-4d41fd74df8f.mov
https://user-images.githubusercontent.com/3934894/163037194-9a9481a1-63b3-4a8c-aef9-708019ef47ae.mov

prevent double new lines when pressing enter with soft/exit break plugins

---

.changeset/eight-ties-behave.md
packages/nodes/table/src/onKeyDownTable.ts

add event.stopPropagation() to tab key event handling in Table plugin to prevent the unwanted indent action.

prevent tab key event in table  propagate to editor

---

.changeset/eighty-days-protect.md
docs/yarn.lock
packages/core/src/plugins/html-serializer/__tests__/elements.spec.ts
packages/ui/nodes/image/src/ImageElement/ImageElement.fixtures.tsx
packages/ui/nodes/image/src/ImageElement/ImageElement.spec.tsx
packages/ui/nodes/image/src/ImageElement/ImageElement.tsx
packages/ui/nodes/image/src/ImageElement/ImageElement.types.ts

See changesets. Also added tests to ImageElement. Image captions were not being properly handled by readOnly mode, so added logic to handle it by default, with logic to override

Added readOnly mode to images and their captions

---

.changeset/kind-islands-appear.md
packages/ui/combobox/src/Combobox.tsx
packages/ui/combobox/src/Combobox.types.ts

Combobox should pass portalElement to PortalBody, otherwise it is impossible to use it in some cases. For example in a scrolling modal.

fix(ui-combobox): add portalElement prop which is passed to PortalBody

---

.changeset/sharp-scissors-obey.md
packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.ts

I experience runtime error when deserializing HTML that contains svg element. This is because the deserializeHtml plugin check `!el.className.includes(validClassName)`. When `el` is svg the className value is not a string, so calling `includes` causes error.
In versions < v8, the check was using `!el.classList.contains(validClassName)`. And this works for all elements
https://github.com/udecode/plate/blob/632f7057fd8c05e8a92fc6fea3445d1641f082fe/packages/common/src/utils/getNodeDeserializer.ts#L35-L36

Fix runtime error when deserialized html contains svg element

---

packages/serializers/md/src/deserializer/utils/deserializeMd.ts

Added element type of image to markdown deserialization. Because markdown mdast expects "image" for the type, images aren't decoded right. Now uses ELEMENT_IMAGE as the type.

Markdown image deserialization

---

docs/docs/examples/huge-document.mdx

This PR fixes a syntax error in the huge editor example, which causes the example not to be rendered. See:
https://plate.udecode.io/docs/examples/huge-document

Fix issue in huge editor example

---

.changeset/moody-apricots-laugh.md
packages/nodes/list/src/deleteBackwardList.ts

List delete backward behavior is a bit erratic when using a custom ast/tag name as the condition check is against the default type rather than looking up the type.

list deleteBackward should check for custom li type instead of default

---

.changeset/grumpy-gorillas-change.md
packages/nodes/mention/src/getMentionOnSelectItem.ts

Makes it possible to create nodes based on search, for example creating
a task if a task with the query is not found.

Pass search to createMentionNode as metadata

---

.changeset/clean-stingrays-repair.md
packages/nodes/list/src/transforms/toggleList.spec.tsx
packages/nodes/list/src/transforms/toggleList.ts

If I toggle a nested list, all of the nested list elements are toggled
If my selection includes both a nested list and a paragraph, this is not the case. I would expect toggling the list to toggle all nested list elements.
Before toggle:
```
• Item 1
• Item 11
• Item 2
Body
```
Expected:
```
1. Item 1
1. Item 11
2. Item 2
3. Body
```
Actual:
```
1. Item 1
• Item 11
2. Item 2
3. Body
```

Toggling a nested list that includes paragraph content should toggle all nested list elements

---

.changeset/lemon-queens-pretend.md
packages/nodes/list/src/onKeyDownList.ts
packages/nodes/list/src/onkeyDownList.spec.tsx

This fixes a whole class of list indentation bugs that are introduced due to "hanging" nodes. 
There is still a bug in Slate's hang code for which @davisg123 created [this PR](https://github.com/ianstormtaylor/slate/pull/5039).
Before:
https://user-images.githubusercontent.com/5635880/176800545-fb866e13-ec71-4151-82cd-c238ac6dfaa1.mp4
After:
https://user-images.githubusercontent.com/5635880/176800439-32570d2e-e88f-493c-b912-2138ed32fab5.mp4

Add ability to indent/un-indent multiple list items

---

.changeset/mighty-ducks-taste.md
packages/serializers/html/src/serializeHtml.ts

This fixes an oversight in my latest PR ([#1633](https://github.com/udecode/plate/pull/1633#issuecomment-1175947681)) where the `convertNewLinesToHtmlBr` option was not passed down to the recursive call of `serializeHtml`.
Thanks to @igorsheg-wix for pointing this out!

HTML Serializer: Ensures options are passed down

---

.changeset/real-pigs-punch.md
packages/nodes/list/src/onKeyDownList.ts
packages/nodes/list/src/onkeyDownList.spec.tsx
packages/nodes/list/src/transforms/moveListItems.ts
packages/nodes/list/src/types.ts

Given a list:
```
1. E1
2. <cursor>E2
3. E3
```
When user presses `Shift+Tab` to un-indent, it should break apart the list. Currently, Plate does not allow unindenting beyond level 1. The correct output after unindent should be:
```
1. E1
<cursor>E2
1. E3
```

allow unindent of top level list item

---

.changeset/stale-swans-buy.md
examples/src/autoformat/autoformatPlugin.ts
packages/editor/autoformat/src/__tests__/withAutoformat/trigger.spec.tsx
packages/editor/autoformat/src/createAutoformatPlugin.ts
packages/editor/autoformat/src/onKeyDownAutoformat.ts
packages/editor/autoformat/src/types.ts

Fixes [This issue](https://github.com/udecode/plate/issues/1678)
Previously, a text autoformat rule was impossible to undo. Usually there is a way to escape it. E.g. it was impossible to type `http://www.google.com` in the plate sandbox.
This change allows the following behavior:
I added tests as well. 
[](url)

Add ability to escape a text autoformat rule by pressing backspace

---

.changeset/cyan-snails-grow.md
packages/nodes/list/src/onKeyDownList.ts
packages/nodes/list/src/onkeyDownList.spec.tsx
packages/nodes/list/src/transforms/removeFirstListItem.ts

In Previous PR (https://github.com/udecode/plate/pull/1663), I forgot to add a case for top level list item which specifically was disallowed from being pulled up.
In this PR I added the failing test case and fixed the implementation. 

Fix the unindent problem; add a test

---

.changeset/tough-pears-tickle.md
packages/nodes/link/src/__tests__/withLink/insertText/space-after-url-across-blocks-custom-href.spec.tsx
packages/nodes/link/src/__tests__/withLink/insertText/space-after-url-custom-href.spec.tsx
packages/nodes/link/src/types.ts
packages/nodes/link/src/withLink.ts

Currently the link plugin only supports links that map directly to the link text content, this change allows clients to optionally specify an href for given text; for example:
```
[google.com](https://google.com)
[ed@gmail.com](mailto://ed@gmail.com)
```

Allow the link plugin to optionally specify a custom href for link text

---

.changeset/curvy-clocks-knock.md
packages/core/src/slate/node/getNode.ts

Improve performance of list normalizations by calling our own getNode that does not throw and stringify the message which was significantly slowing down performance, especially given that we would just return null.

Get node performance list normalization

---

.changeset/large-hats-cross.md
packages/ui/combobox/src/Combobox.tsx

ComboBox and Mention were scrolling off-screen when near the bottom of the viewport. Now they should flip above the element in the editor if necessary.

Mention position

---

.changeset/funny-hotels-wash.md
packages/nodes/link/src/components/FloatingLink/FloatingLinkUrlInput.tsx
packages/nodes/link/src/components/FloatingLink/useFloatingLinkInsert.ts
packages/ui/nodes/list/src/TodoListElement/TodoListElement.tsx

Fixes https://github.com/udecode/plate/issues/1700
- (Temporary) usage of `setTimeout` to allow the location of the floating element to be finalized before focusing.
- Re-focus on the selected node when clicking on outside of the floating element.
---
When using `FloatingLinkUrlInput`, the `updated` event is fired before the the final location of the floating element has been determined.
The `updated` event triggers a call to `.focus()` on the `input` contained within the floating element resulting in the following:
- On first instantiation, `x` and `y` are both `null` resulting in styles of `top: 0, left: 0`, so when the the `updated` event is fired and the user is sent to the top of the page. 
- On follow-on instantiations, `x` and `y` are both still their previous values, so when the …

fix(link): stop the link floating element from snapping to the wrong location

---

patches/is-hotkey+0.2.0.patch
scripts/plop/plop-sandpack.js

1. Fixed invalid patch file. Added missing spaces before LF in patch file.
2. Fixed hardcoded slash in scripts/plop/plop-sandpack.js
For more information about the patch-format see:
https://www.oreilly.com/library/view/git-pocket-guide/9781449327507/ch11.html
Description
On Windows run:
git clone https://github.com/udecode/plate.git
cd plate
yarn install
You get:
root-workspace-0b6124@workspace:. couldn't be built successfully (exit code 1, logs can be found here: AppData\Local\Temp\xfs-200e4c83\build.log)
build.log
This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
Script name: postinstall
patch-package 6.4.7
Applying patches...
ERROR Failed to apply patch for package is-hotkey
This happened because the patch file patches\is-hotkey+0.2.0.patch …

Fixed Windows build problems

---

.changeset/friendly-dryers-tap.md
packages/nodes/list/src/transforms/toggleList.spec.tsx
packages/nodes/list/src/transforms/toggleList.ts

In our application, toggling a set of blocks to a list was partially inverting the order, e.g 1 2 3 4 5 -> 1 3 2 5 4.
I was not able to reproduce this in Plate, but my hunch is that something in Slate changed in the past few months.
I have added tests to check that the order is preserved regardless of selection direction, and all current tests pass for me.

Prevent reversal of items when toggling blocks to a list

---

.changeset/big-kids-admire.md
examples/apps/next/src/config/sidebarItems.ts
packages/media/package.json
packages/media/src/twitter/components/Tweet.tsx
yarn.lock

Uses scriptjs to handle waiting for window.twttr to become available before trying to call createTweet.
Fixes only 1 tweet loading when using multiple plate instances that includes tweets.
Also includes fix for broken link to Media in the example app.
Closes #1753

Fix loading tweets in multiple plate instances

---

.changeset/chilled-wolves-walk.md
packages/core/src/queries/isSelectionAtBlockEnd.ts

Makes isSelectionAtBlockStart's and isSelectionAtBlockEnd's behavior consistent.

Allow passing options to isSelectionAtBlockEnd

---

docs/docs/plugins/SerializingCsvSandpack.tsx
docs/docs/plugins/SerializingHtmlSandpack.tsx
docs/docs/plugins/SerializingMdSandpack.tsx
docs/docs/sandpack/files/code-SerializingHtmlApp.tsx
examples/src/SerializingHtmlApp.tsx

The example about serializing on the official website does not work properly because linkFiles is not imported. It works fine after adding it.
In the example of serializing html, the serialized object is changed from baseNode to editor.children, which can be seen more intuitively.

fix: serializing sandbox examples

---

.changeset/dry-mails-dress.md
packages/core/src/queries/getPointBeforeLocation.ts
packages/editor/autoformat/src/__tests__/withAutoformat/text.spec.tsx

The auto formatter was incorrectly matching the text that contained extra characters:
```
`-X-` became `—`
`-X>` became `→`
```

Autoformatter will incorrectly match on text that contains one additional character of text

---

examples/src/preview-markdown/PreviewLeaf.tsx

Styles were not applied properly in PreviewLeaf.tsx, now its fixed. Probably there are others way to fix it (via styled components, etc), but this one looks good to me :)
Closes #1813

Fix preview Markdown example

---

packages/nodes/mention/src/getMentionOnSelectItem.ts

After selecting and item in dropdown the cursor is positioned behind the mention tag so the writer can write further without interruption. 
The prop `insertSpaceAfterMention` also does what it should do: it adds additional space after mention tag.
This Issue i think also talks about the same problem.
https://github.com/udecode/plate/issues/1533
Video with new behavior!
https://www.loom.com/share/ad5ea5759bc84bc1a5334560534b1a78

Updated creation of mention after selection

---

docs/docs/plugins/serializing-html.mdx

The package name is misspelled as `plate-serialize-html`, mind the missing `r`.
I tried to install the html serializer, but I could not get it installed with yarn or npm. I then looked up the package name from the `headless` package, where it is a dependency.
```
$: yarn add @udecode/plate-serialize-html
yarn add v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@udecode%2fplate-serialize-html: Not found".
```

docs: Use correct package plate-serializer-html

---

.changeset/dirty-feet-lay.md
packages/nodes/link/src/withLink.spec.tsx
packages/nodes/link/src/withLink.ts

Previously, when you type a valid URL and hit 'enter,' it created a new block but did not wrap the inserted link into an anchor element. 
This PR fixes this behavior by overriding insertBreak and refactoring. Also added a test.

improve link plugin to wrap on insert-break

---

.changeset/smart-moles-act.md
packages/core/src/plugins/createPrevSelectionPlugin.ts
yarn.lock

React 16.x used an event pooling mechanism that would cause synthetic events to get "re-used" unless they are explicitly persisted. You can find this documented here. https://reactjs.org/docs/legacy-event-pooling.html
As a result the synthetic events stashed in the `prevSelectionPlugin` would have all of its values nulled out and was issuing a warning when the properties of the events were accessed.
Notably for me this manifested in the table plugin's keyboard shortcuts not working properly, although I'm imaging it causes other keyboard shortcuts relying on this previous event to be broken too.
Of course we're working to move to react 17, but one of the blockers is our old editor that we are replacing with Plate. Luckily at the moment the fix is pretty straightforward. …

Fix prev selection plugin event persistence on React 16.x

---

docs/docs/plugins/autoformat.mdx

I noticed a small typo when referencing the docs, figured I'd make a PR to correct it :)

Fix doc typo

---

.changeset/good-pumpkins-fold.md
.changeset/long-spoons-roll.md
packages/editor/node-id/src/createNodeIdPlugin.spec.tsx
packages/editor/node-id/src/withNodeId.ts

The current way that `withNodeId` is implemented doesn't guarantee ID uniqueness when inserting nested nodes. 
For instance, say we apply the following insert node operation:
```
{
"type": "insert_node",
"path": [
0,
1
],
"node": {
"type": "li",
"children": [
{
"type": "lic",
"children": [
{
"text": "",
"id": "2"
}
],
"id": "1"
}
],
"id": "0"
},
}
```
The current implementation of `withNodeId` will only check if the node with **id 0** is duplicated and regenerate it if so. It will not check if the nodes with **id 1** and **id 2** are being used elsewhere, meaning it's possible to have multiple nodes with those ids.

Make withNodeId add Ids to nested blocks

---

.changeset/rotten-planes-collect.md
packages/nodes/link/src/components/FloatingLink/floatingLinkStore.ts
packages/nodes/link/src/components/FloatingLink/useFloatingLinkEdit.ts
packages/nodes/link/src/components/FloatingLink/useFloatingLinkEnter.ts
packages/nodes/link/src/components/FloatingLink/useFloatingLinkEscape.ts
packages/nodes/link/src/components/FloatingLink/useFloatingLinkInsert.ts
packages/nodes/link/src/components/FloatingLink/useVirtualFloatingLink.ts
packages/nodes/link/src/utils/triggerFloatingLinkInsert.ts

Fixed floating link toolbar when used with multiple editors.
Fixes https://github.com/udecode/plate/issues/1771

Fix floating link open state for multiple editors

---

packages/nodes/link/src/components/FloatingLink/OpenLinkButton.tsx

Fixes https://github.com/udecode/plate/issues/1967
Basically link node was memoized without dep on selection, and when you change selection it stays the same.
It's my first PR here, I am not sure about changesets, do I need to add one?

Fix OpenLinkButton href

---

.changeset/khaki-vans-sleep.md
packages/ui/nodes/excalidraw/src/components/ExcalidrawElement/ExcalidrawElement.tsx

**Updated the import from `@excalidraw/excalidraw` to support latest version**
**Issue**
Excalidraw board stopped rendering upgrading the package to latest stable version. PR: #1943
**Solution**
This PR will fix the import issue. Latest version has named export for Excailidraw component instead of default.
**Video demonstration**
https://app.usebubbles.com/5B6y9mR73oAHdLknpsBJS4/excalidraw-demo-after-fix

Fix import for Excalidraw component

---

.changeset/few-elephants-roll.md
packages/nodes/link/src/components/FloatingLink/useFloatingLinkInsert.ts

It seems that I missed one case when `useFloatingLinkInsert` closes other editors popups because of always enabled `useOnClickOutside`
Fixes https://github.com/udecode/plate/issues/1771#issuecomment-1305433623

Fix floating link insert popup closing other editors popups

---

.changeset/large-tips-heal.md
.changeset/popular-spoons-type.md
packages/core/src/components/plate/PlateEditable.tsx
packages/core/src/types/plugin/PlatePlugin.ts
packages/ui/nodes/link/src/PlateFloatingLink.tsx

Fix: don't render `FloatingLink` on `readOnly`

---

.changeset/loud-emus-return.md
packages/nodes/link/src/components/FloatingLink/useFloatingLinkEscape.ts

Does it makes sense to do that? 😄 
This PR:
1) Adds `e.preventDefault();` when `Escape` is handled by the floating link popup.
2) Adds `insert` mode handling too, so now you can close insertion window with keyboard too.

Fix floating link escape handling

---

.changeset/cyan-chairs-kiss.md
packages/nodes/list/src/onKeyDownList.ts
packages/nodes/list/src/onkeyDownList.spec.tsx

Fixes https://github.com/udecode/plate/issues/1985
I tracked this down as a regression coming from https://github.com/udecode/plate/pull/1642
The existing tests should all still be passing and I did some additional manual testing and the behaviour still seems to match the expection from that other PR. TBH I'm not really sure what this little line's purpose was.
**Before**
**After**

Fix list plugin adjusting selection range on Tab or ShiftTab keypress

---

.changeset/nice-dryers-invent.md
packages/nodes/mention/src/handlers/mentionOnKeyDownHandler.ts

I think mention keydown might be incorrect, it always prevents default on `Escape` but it seems that it should only happen when there is a mention input

Fix mention keydown handler

---

.changeset/cool-grapes-jam.md
packages/nodes/link/src/components/FloatingLink/useFloatingLinkEdit.ts
packages/nodes/link/src/components/FloatingLink/useFloatingLinkInsert.ts
packages/nodes/link/src/utils/triggerFloatingLinkEdit.ts
packages/nodes/link/src/utils/triggerFloatingLinkInsert.ts

It seems that link hotkey always prevents default too, it should only do it when it really handled the action

Fix link hotkey prevent default

---

.changeset/cuddly-cups-cover.md
packages/nodes/table/src/transforms/insertTableColumn.spec.tsx
packages/nodes/table/src/transforms/insertTableColumn.ts
packages/nodes/table/src/transforms/insertTableRow.spec.tsx
packages/nodes/table/src/transforms/insertTableRow.ts

Solves #2004 
I went for the `at` option as requested by @zbeyens 
I created our own `TableToobarButton` component with the same props but with our existing style system. So the usage is the same. Here is an example from my test with our editor:
```tsx
[...]
const type = getCellTypes(editor)
const node = getBlockAbove(editor, { match: { type } })
if (!node) return null
const [, path] = node
[...]
return (
<TableToolbarButton
title={t('insertTableColumnButton.tooltip')}
transform={(editor, options) => insertTableColumn(editor, { ...options, at: path })}
className={styles.tableButtonAdd}>
<PlusIcon />
</TableToolbarButton>
)
```
This is my first try on this. I am not yet satisfied with the code as it is now, lot's of `if`s that probably can be done better. But I am running …

plugin-table: Add `at` option for inserts

---

.changeset/proud-buckets-bathe.md
packages/nodes/emoji/src/utils/getFindTriggeringInput.ts

If the editor is empty or the whole text is deleted then the editor throws error while it can find the text he is searching for.
Fixed with stopping the loop if the offset is 0

fix bug when editor text is empty

---

.changeset/thin-ties-confess.md
packages/selection/src/useHooksBlockSelection.ts

Respect editor read-only state in block selection hooks

---

.changeset/strange-radios-heal.md
packages/nodes/emoji/src/withEmoji.ts

Conflict with combobox. Only apply if the triggering mark is for Emoji and not any other

only trigger if has emoji mark

---

.changeset/happy-jobs-judge.md
packages/serializers/md/src/deserializer/createDeserializeMdPlugin.ts

If you copy and paste a markdown string from a text editor, the process of converting it to a node may not work, for example, VSCode. Then occurs because dataTransfer.getData('text/html') can obtain a string.
The query process itself seems unnecessary in the markdown deserialization process.
**Example**
1. Go to https://plate.udecode.io/docs/serializing-md
2. Paste markdown strings from VSCode.

Remove unnecessary query in deserialize markdown

---

.changeset/dull-crabs-train.md
examples/src/exit-break/exitBreakPlugin.ts
packages/editor/break/src/exit-break/transforms/exitBreak.ts
packages/editor/break/src/exit-break/types.ts

This PR adds a new option `relative?: boolean` to the exit break plugin that allows the exit point ("level" property) to be relative to the current level rather than absolute. It is optional and default false to not introduce any breaking change. Also adds a passing fix to a doc typo.
This allows the exit break plugin to be useful in editors with nested blocks e.g. tables (fixes #2128 `:^)`).
**Before (and remains default behaviour):**
https://user-images.githubusercontent.com/33153339/212947593-ed714699-fefd-4225-ab5b-54ab582bd730.mov
**After (and with `relative: true`):**
https://user-images.githubusercontent.com/33153339/212947663-e1c41312-fd3e-474a-a6f2-b84fe8d89bd1.mov

Add "Relative" Option to Exit Break Plugin #2128

---

.changeset/chatty-sloths-check.md
packages/core/src/plugins/html-deserializer/utils/htmlTextNodeToString.spec.ts
packages/core/src/plugins/html-deserializer/utils/htmlTextNodeToString.ts
packages/serializers/docx/src/deserializer/__tests__/legal-in.spec.tsx
packages/serializers/docx/src/deserializer/__tests__/legal.spec.tsx

Fixes #2152 
This PR changes the behaviour of the HTML deserializer plugin to strip `\n` chararcters from the start and end of text nodes, leaving internal newlines in place. If the text node contains no characters other than newlines, it will be excluded. (Previously, text nodes were only excluded if they contained exactly one newline and nothing else.)
`'test'` -> `'test'`
`'\ntest\n'` -> `'test'`
`'\ntest\ntest\n'` -> `'test\ntest'`
`''` -> `null`
`'\n'` -> `null`
`'\n\n'` -> `null`
**To do**
`yarn run jest packages/serializers/docx/src/deserializer/__tests__/legal*.spec.tsx`
I'm not sure what to do about the failing DOCX serializer tests. If we want to keep the original behaviour in this context, we could add an option to `htmlTextNodeToString` and other relevant …

Trim \n from start and end of text nodes when deserializing HTML

---

.changeset/blue-seals-taste.md
docs/docs/sandpack/files/code-PlaygroundApp.tsx
examples/src/PlaygroundApp.tsx
packages/nodes/code-block/src/normalizers/normalizeCodeBlock.spec.tsx
packages/nodes/code-block/src/normalizers/normalizeCodeBlock.tsx
packages/nodes/code-block/src/transforms/indentCodeLine.spec.tsx
packages/nodes/code-block/src/transforms/indentCodeLine.ts
packages/nodes/code-block/src/transforms/insertCodeBlock.spec.tsx
packages/nodes/code-block/src/transforms/insertCodeLine.spec.tsx
packages/nodes/code-block/src/transforms/insertEmptyCodeBlock.spec.tsx
packages/nodes/code-block/src/transforms/insertEmptyCodeBlock.ts
packages/nodes/code-block/src/transforms/outdentCodeLine.spec.tsx
packages/nodes/code-block/src/transforms/toggleCodeBlock.spec.tsx
packages/nodes/code-block/src/transforms/toggleCodeBlock.ts
packages/nodes/code-block/src/transforms/unwrapCodeBlock.ts
packages/nodes/code-block/src/withCodeBlock.spec.tsx
packages/nodes/code-block/src/withCodeBlock.ts

This PR adds tests for a few important functions relating to code blocks, plus fixes where necessary to ensure the correct behaviour. In most cases, I've assumed that the implemented behaviour is the desired behaviour, and I've documented this behaviour in the tests. If you see any tests that don't match intended behaviour, let me know.
See discussion #2160
Fixes #2161
Fixes #719
Check if fixes:
- ~~#2046~~
- Cannot reproduce in latest examples
- ~~#2026~~
- Not fixed
**To do**
Edit: Decorations are working correctly but no CSS is set for them

Code block tests and fixes

---

.changeset/popular-beds-doubt.md
examples/src/MentionApp.tsx
packages/nodes/mention/src/types.ts
packages/nodes/mention/src/withMention.ts

Fixes https://github.com/udecode/plate/discussions/2056 + useful towards slash menu. Have added an example to the Mentions example (the slash-triggered plugin only works at the start of the line) `:^)`

Add query option to mention plugin

---

.changeset/witty-moles-serve.md
docs/docs/sandpack/files/exit-break/code-exitBreakPlugin.ts
docs/docs/sandpack/files/reset-node/code-resetBlockTypePlugin.ts
examples/src/reset-node/resetBlockTypePlugin.ts
packages/editor/reset-node/src/onKeyDownResetNode.spec.tsx
packages/nodes/code-block/src/queries/index.ts
packages/nodes/code-block/src/queries/isCodeBlockEmpty.spec.tsx
packages/nodes/code-block/src/queries/isCodeBlockEmpty.ts
packages/nodes/code-block/src/queries/isSelectionAtCodeBlockStart.spec.tsx
packages/nodes/code-block/src/queries/isSelectionAtCodeBlockStart.ts

This PR adds two queries to code block which can be used in reset node rules to ensure the correct behaviour. It also rewrites the tests for `onKeyDownResetNode` to be more clear about what they test and to demonstrate the intended usage with code blocks.
I've updated the Reset Nodes example to add rules for code blocks. 
Fixes #2046
Fixes #2026

Add `isCodeBlockEmpty` and `isSelectionAtCodeBlockStart`

---

.changeset/warm-buttons-kneel.md
packages/nodes/list/src/onKeyDownList.ts

**Context**
I'm working on a plugin, which I'm hoping to share once it's finished, that lets you tab into and out of void elements as you would expect. To do this, I need to be able to conditionally prevent the list plugin from handling the tab event, and this seemed to be the simplest way of doing that.
If this change to the list plugin might have undesirable results, I'm happy to close this PR and expore alternative solutions.

Ignore defaultPrevented keydown event in list plugin

---

.changeset/violet-buses-tell.md
packages/media/src/resizable/Resizable.tsx

fix: Cannot read properties of null (reading 'toString') when image width is null

---

.changeset/old-cougars-destroy.md
packages/ui/toolbar/src/MarkToolbarButton/MarkToolbarButton.tsx

Fixes #2223
I'm pretty sure `ReactEditor.focus` should be sufficient, since the selection won't have changed since before the button was pressed. Would it be worth changing this in the [other types of toolbar button](https://github.com/search?q=repo%3Audecode%2Fplate%20Toolbar%20focusEditor&type=code)?

Fix mark toolbar button not applying mark properly

---

.changeset/nasty-cougars-hear.md
packages/core/src/types/plugin/PlatePlugin.ts
packages/core/src/utils/plate/overridePluginsByKey.ts

Add check for `then` being replaced.  This will fix #2230.

Fix #2230: Stop accidental infinite recursion

---

.changeset/great-actors-work-core.md
.changeset/great-actors-work.md
.changeset/quiet-wombats-hug.md
docs/docs/plugins/link.mdx
packages/core/src/utils/misc/index.ts
packages/core/src/utils/misc/sanitizeUrl.spec.ts
packages/core/src/utils/misc/sanitizeUrl.ts
packages/nodes/link/src/components/FloatingLink/OpenLinkButton.tsx
packages/nodes/link/src/components/Link.tsx
packages/nodes/link/src/createLinkPlugin.ts
packages/nodes/link/src/transforms/submitFloatingLink.ts
packages/nodes/link/src/transforms/upsertLink.spec.tsx
packages/nodes/link/src/transforms/upsertLink.ts
packages/nodes/link/src/utils/getLinkAttributes.spec.ts
packages/nodes/link/src/utils/getLinkAttributes.ts
packages/nodes/link/src/utils/index.ts
packages/nodes/link/src/utils/validateUrl.ts

Links that are pasted as text are detected using the link plugin. Links pasted as HTML are not, leading to https://github.com/udecode/plate/issues/2239.
This PR applies the `isUrl` option, if present, to the href of any pasted `<a />` tag, and falls back to pasting as text if the href is not deemed to be a URL.
Realise this might be quite opinionated and/or a breaking change so happy to create a new "should validate pasted links" flag if preferred.

Apply isUrl option to pasted links #2239

---

.changeset/fast-pots-enjoy.md
packages/comments/src/components/CommentNewSubmitButton.tsx
packages/comments/src/stores/comments/CommentsProvider.tsx

Since `myUserId` is `string | null`, `onCommentAdd` receives a `WithPartial<TComment, 'userId'>`. This can safely be converted to a `TComment` so long as `myUserId` is non-null.

Pass full comment object to `onCommentAdd`

---

.changeset/rude-seas-work.md
examples/src/CloudApp.tsx
packages/cloud/src/cloud/withCloud.ts
packages/cloud/src/image/createCloudImagePlugin.ts
packages/cloud/src/image/types.ts
packages/cloud/src/image/withCloudImage.ts
packages/ui/cloud/src/CloudImageElement/ResizeControls.tsx

Add options to set minResizeWidth and maxResizeWidth to CloudImagePlugin
Enables options like this when defining the CloudImagePlugin
```typescript
createCloudImagePlugin({
options: {
maxInitialWidth: 320,
maxInitialHeight: 320,
minResizeWidth: 100,
maxResizeWidth: 720,
},
}),
```

Add cloud options for min and max resize width of images

---

.changeset/nervous-doors-film.md
packages/ui/cloud/src/CloudImageElement/generateSrcAndSrcSet.ts

Server side resizing of animated GIFs does not work with the current server-side image resizing library SharpJS.
Typically, the only use case for GIFs is animated GIFs as PNGs are typically used for static images.
For this reason, it's probably best if we just don't resize animated GIFs on the server side. Even if we can support this in the sever-side resizing library, this can lead to complications and trade-offs in the way that GIFs use an adaptive palette which is not necessarily a good fit for resizing which will cause more colors to be required.
This PR allows the GIF image to be resized on the client, but does not cause the image to be resized on the server.
This PR is related to this issue #2260

Disable server side resizing of GIF files

---

.changeset/sweet-chairs-confess.md
examples/src/balloon-toolbar/MarkBalloonToolbar.tsx
examples/src/comments/CommentBalloonToolbar.tsx
packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.tsx
packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.types.ts
packages/ui/toolbar/src/BalloonToolbar/useFloatingToolbar.ts

The changes in `/examples` aren't used, but show how options can be passed down to BalloonToolbar. I can revert them if preferred.

Add `ignoreReadOnly` prop to BalloonToolbar

---

.github/workflows/release.yml

Use `X_GITHUB_CHANGESET_RELEASE_TOKEN` for changeset release action. Workaround for [this limitation](https://stackoverflow.com/questions/69063452/github-actions-on-release-created-workflow-trigger-not-working) of workflow triggers.

Use custom access token for changeset release action

---

.changeset/odd-moles-smoke.md
packages/editor/autoformat/src/onKeyDownAutoformat.ts
packages/editor/break/src/exit-break/onKeyDownExitBreak.ts
packages/editor/break/src/single-line/onKeyDownSingleLine.ts
packages/editor/break/src/soft-break/onKeyDownSoftBreak.ts
packages/editor/reset-node/src/onKeyDownResetNode.ts
packages/media/src/caption/getOnKeyDownCaption.ts
packages/nodes/emoji/src/handlers/getOnKeyDownEmoji.ts
packages/nodes/indent-list/src/onKeyDownIndentList.ts
packages/nodes/indent/src/onKeyDownIndent.ts
packages/nodes/table/src/onKeyDownTable.ts
packages/plate-utils/src/plate/onKeyDownToggleElement.ts
packages/plate-utils/src/plate/onKeyDownToggleMark.ts

Ignore `defaultPrevented` keydowns for most handlers. Mention and combobox are an exception, since they both need to handle the same escape key.
**Context**
Generally speaking, for good UX, any input event should map to at most one action. The standard way of enforcing this is by calling `event.preventDefault()` when handling an input event, and checking `event.defaultPrevented` if there's a chance that the event has already been handled.
This pattern is useful for preventing conflicts between standard Plate plugins and custom plugins. For example, the conflict that prompted this PR was between the soft break plugin and a custom combobox plugin.

Ignore `defaultPrevented` keydowns for most handlers

---

.changeset/strong-bags-relate.md
packages/ui/cloud/src/CloudImageElement/CloudImageElement.tsx
packages/ui/cloud/src/StatusBar/StatusBar.styles.ts
packages/ui/cloud/src/StatusBar/StatusBar.tsx

This is part 2 to the Plate Cloud Collaborative Fix.
When uploading state is not found, which will happen for any collaborators that are not doing the upload, the UI will now show "uploading" instead of "state not found". Additionally, the image placeholder will not be a broken image and will instead show a gray background as would be appropriate in a collaborative environment.

Make Plate Cloud state not found look correct for collaborative uploads

---

.changeset/new-rabbits-smoke.md
packages/resizable/package.json

Missing peer dependencies cause yarn pnp to fail.

Add missing peer dependencies

---

.changeset/early-mayflies-build.md
packages/dnd/src/components/useDraggableState.ts
packages/dnd/src/hooks/useDndNode.ts
packages/dnd/src/hooks/useDragNode.ts
packages/dnd/src/hooks/useDropNode.ts
packages/ui/dnd/src/PlateDraggable.tsx

This PR does two things:
- It adds an **optional** `onDropHandler` to the `draggableProps` property. This handler takes the same arguments as the `drop`function in the `useDropNode` hook and should return `boolean`.
If the function returns `true`, the default onDropNode behavior will not be called since it would be considered handled. If the function returns `false`, the default onDropNode will be triggered.
- It adds an `editorId` property to the `dragItem` property so there is always a reference to the editor from which the item was dragged. This allows for better support and more control when working with nested editors.

Adds optional ondrop handler to draggableProps

---

.changeset/tricky-garlics-guess.md
packages/nodes/mention/src/getMentionOnSelectItem.ts

When overriding `ELEMENT_MENTION_INPUT` this function was still used the hardcoded value.

Get right mention input type when overriden

---

.changeset/blue-cats-wave.md
packages/dnd/src/components/Scroller/DndScroller.tsx

Scroller only appears after a delay after dragging.
This fixes #2081, as the scroll area doesn't come immediately over the dragged element, causing the drag to fail/cancel.

fix: add delay to DnD scroller

---

.changeset/twelve-months-bow.md
packages/core/src/hooks/useEditableProps.ts

The `readOnly` value coming from Plate store was not passed as a dependency of `useDeepCompareMemo` in `useEditableProps` which could cause `Editable` to receive an stale `readOnly` prop.

fix: add missing readOnly dep in useEditableProps

---

.changeset/large-trains-taste.md
packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.spec.ts
packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.ts

Alter existence check to only check for null and undefined values.  This allows the validAttribute to check for empty strings .
Per https://github.com/udecode/plate/discussions/2399#discussion-5206912
Before the following rule would fail to match when checking for an attribute that equals ''.
```
deserializeHtml: {
isElement: true,
rules: [
{
validAttribute: { href: '' },
validNodeName: 'A',
},
],
}
```

Fix/2399 deserialize validAttribute nullcheck

---

docs/docs/plugins/emoji.mdx
docs/docs/plugins/mention.mdx

Plate doc links from "Emoji" and "Mention" to combobox are invalid because they duplicate path components: (e.g. https://plate.udecode.io/docs/plugins/docs/plugins/combobox)
This fixes it by adding a leading slash to the link path.

fixes doc links to combobox

---

docs/docs/plugins/serializing-html.mdx

✅ ~~[Awaiting confirmation from @fbolcic](https://github.com/udecode/plate/discussions/2390#discussioncomment-5884626)~~
> ### Creating an `editor` Instance
>
> An `editor` instance is required to serialize a Slate value to HTML. If you need to use `serializeHtml` in a context where no `editor` is available, you can create one using `createPlateEditor({ plugins })`. Include the plugins and components necessary for rendering all node types used in your Slate value.
>
> ```tsx
> import {
>   createParagraphPlugin,
>   createPlateEditor,
>   createPlateUI,
>   createPlugins,
>   serializeHtml,
>   // ...
> } from '@udecode/plate';
> 
> const plugins = createPlugins([
>   createParagraphPlugin(),
>   // ...
> ], {
>   components: createPlateUI(),
> });
> 
> const editor = createPlateEditor({ …
```

Correct docs on serializing HTML without editor instance

---

.changeset/metal-toys-shop.md
packages/core/src/hooks/useSlateProps.ts

[Slate 0.94.1 changed value to initialValue](https://github.com/ianstormtaylor/slate/pull/5421). In order to support support the new version and still support previous versions I added this new property and still kept the old one.

fix: support slate 0.94.1 after changing prop name for value to initialValue

---

.changeset/emoji-plugin.md
packages/nodes/emoji/src/handlers/getFindTriggeringInput.ts
packages/nodes/emoji/src/utils/EmojiTriggeringController.ts
packages/nodes/emoji/src/utils/EmojiTriggeringController.types.ts
packages/nodes/emoji/src/utils/IndexSearch/IndexSearch.ts
packages/nodes/emoji/src/withEmoji.ts

- if after ':' char was break inserted typing further would activate dropdown. Should be only activated in the same line.
- if the emoji was enclosed whit the ':' sign nothing happened, now the emoji is created if it was found.
https://www.loom.com/share/a849a1e2a1f745c6931e2d7c2f62f368

fix: improve emoji plugin

---

.changeset/nasty-terms-heal.md
.changeset/weak-ways-impress.md
packages/ui/button/src/Button/PlateButton.tsx
packages/ui/button/src/Button/RemoveNodeButton.tsx
packages/ui/nodes/table/src/PlateTableBordersDropdownMenuContent.tsx
packages/ui/nodes/table/src/PlateTablePopover.tsx

See changesets. Table popover icons are unchanged.
**Before**
**After**
**Unchanged**

Fix comment popover button icons

---

.changeset/smooth-beds-kneel.md
packages/utils/src/isUrl.spec.ts
packages/utils/src/isUrl.ts
yarn.lock

This PR allows pasting `email` links from clipboard.
**Before**
https://github.com/udecode/plate/assets/39378793/320d8532-ea0e-42fa-98a9-417609eab1a0
**After**
https://github.com/udecode/plate/assets/39378793/26e1355d-446f-4a2e-9660-28a538f4d8c6

[LinkPlugin] Allows pasting `email` links from clipboard

---

.changeset/funny-plants-listen.md
packages/core/src/plugins/html-deserializer/utils/cleanHtmlEmptyElements.ts

Fixes pasting tables from clipoboard which have empty cells.
**Before**
https://github.com/udecode/plate/assets/39378793/e27b960f-3d61-41af-b0d8-4f30fb93d733
**After**
https://github.com/udecode/plate/assets/39378793/7c8415e4-ec50-4aa2-a8bd-b0df13a20104

[HtmlDeserializer] Fix pasting tables with empty cells

---

apps/www/content/docs/accessing-editor.mdx

This is just a small fix for a typo I saw in accessing-editor.mdx.

📚 docs: fix typo in accessing-editor.mdx

---

.changeset/violet-ravens-jam.md
packages/list/src/deleteFragmentList.ts
packages/slate/src/interfaces/editor/deleteMerge.ts

This PR fixes elements remove caused by list plugin handlers. So, removing content with `ctrl+a` and `backspace` triggers list plugin handlers which is already incorrect from my perspective. Then selection change from `path: [0, 2]` to `path: [0, 0]` keeps 2 last elements, no matter which type they have.
https://github.com/udecode/plate/assets/39378793/91c2fb7a-53b4-428d-929f-92d753ce6fcf
The problem with the following lines
https://github.com/udecode/plate/blob/e7f73457e5682f350d11b82e75baabb3b4334a77/packages/slate/src/interfaces/editor/deleteMerge.ts#L182-L184

[ListPlugin] Fix elements remove 

---

.changeset/six-trees-change.md
packages/select/src/createSelectOnBackspacePlugin.ts
packages/select/src/withSelectOnBackspace.ts

This PR removes node if empty on selection change.
**Before**
https://github.com/udecode/plate/assets/39378793/56c7b18e-3972-4bc8-95f6-c047466bddd4
**After**
https://github.com/udecode/plate/assets/39378793/f030347a-0f06-4499-a35b-8b868657a1b8

[SelectOnBackspace] Remove empty node

---

.changeset/bright-dryers-suffer.md
packages/table/src/transforms/insertTableColumn.ts
packages/table/src/transforms/insertTableRow.ts

Fixes #2577
Modify insertTableRow and insertTableColumn to support header columns to preserve header columns if they exist + not blindly assume that a header row if the first cell in that row is a header cell.
**Before**
https://github.com/udecode/plate/assets/33153339/dce6e359-92fe-433e-9c53-ea530d63bd9e
**After**
https://github.com/udecode/plate/assets/33153339/26c57080-b348-4c22-95df-7570c2c61fdd

Modify insertTableRow and insertTableColumn to support header columns #2577

---

.changeset/nine-singers-change.md
packages/table/src/queries/isTableBorderHidden.spec.tsx
packages/table/src/transforms/deleteColumn.spec.tsx
packages/table/src/transforms/deleteColumn.ts

This PR fixes a bug where a path index was being used instead of the value at that index 🤔🤔🤔
Emerged as you cannot delete columns in tables with parent nodes with the current implementation.

Fix column deletion early return

---

apps/www/src/components/plate-ui/playground-floating-toolbar-buttons.tsx
apps/www/src/registry/default/plate-ui/image-element.tsx
apps/www/src/registry/default/plate-ui/link-floating-toolbar.tsx
apps/www/src/registry/default/plate-ui/media-popover.tsx
apps/www/src/registry/default/plate-ui/table-element.tsx
templates/plate-playground-template/src/components/plate-ui/media-popover.tsx

When attempting to print content from the Plate Editor, users encounter an issue where the floating toolbars and empty image captions associated with the editor remain visible in the print output. This behavior is unintended and disrupts the appearance of printed content.
The floating toolbars, which are meant to provide editing and formatting options while interacting with the editor, should ideally be hidden when generating a print preview or printing the content.
Also, when the caption for image is empty, should be hidden
**Steps to Reproduce**
Pre-requirements: You've a setup of Plate Editor with following plugins enabled
1. Image
2. Balloon Toolbar
1. Add content to Plate Editor (include image with empty caption).
2. Select some text (This should trigger balloon …

Print view fix

---

.changeset/slow-cats-thank.md
packages/slate/src/interfaces/editor/unhangRange.ts

**Examples**
```ts
unhangRange(editor, selection as Range | null) // has type Range | null
unhangRange(editor, selection as Range) // has type Range
unhangRange(editor, point) // has type Point
```

Ensure the return type of `unhangRange` matches the argument type

---

.changeset/twelve-cars-drop.md
apps/www/content/docs/components/cli.mdx
apps/www/content/docs/components/dark-mode/next.mdx
packages/cli/src/commands/add.ts
packages/cli/src/utils/transformers/transform-css-vars.ts
packages/cli/test/utils/__snapshots__/transform-css-vars.test.ts.snap
packages/cli/test/utils/apply-color-mapping.test.ts
packages/cli/test/utils/transform-css-vars.test.ts

Sync shadcn

---

.changeset/great-files-boil.md
packages/serializer-docx/src/docx-cleaner/utils/cleanDocxImageElements.ts

Replace `import isURL from 'validator/lib/isURL'` with `import validator from 'validator'` to fix CommonJS import issue when using `esModules` under vitest.

FIX #2677 : CommonJS validator import in cleanDocXImageElements

---

.changeset/long-students-retire.md
packages/table/src/transforms/insertTable.ts

`newCellChildren` is now picked up as an option in `newCellChildren` otherwise it's also used the plugin option.
Fixes: #2681

fetch newCellChildren or allow it to be passed into insertTable

---

.changeset/fast-eggs-burn.md
packages/link/src/transforms/submitFloatingLink.ts

Fix exception when Enter is pressed in link input.
Fix issue when pressing Enter in link input on floating toolbar with latest plate/slate:
https://github.com/udecode/plate/issues/2674
Steps to reproduce:
- select text
- click "link" on a floating toolbar
- enter some url and click enter -> exception "Cannot resolve a DOM node from Slate node"

Fix: "Cannot resolve a DOM node from Slate node" floating link case

---

apps/www/src/registry/default/plate-ui/toolbar.tsx

This prevents nesting multiple `<button>`s

Add `asChild` to the TooltipTrigger in ToolbarButton

---

.changeset/tender-socks-dress.md
.changeset/tiny-carpets-help.md
packages/media/src/media/insertMedia.ts
packages/slate/src/interfaces/transforms/insertNodes.ts

Implements the `removeEmpty` option on `insertNodes` discussed [here](https://github.com/udecode/plate/issues/2704#issuecomment-1764797567). If a node is removed as a result of this option, the `nextBlock` option is ignored.
I wasn't able to import `ELEMENT_DEFAULT` or `isAncestorEmpty` since these are from packages that depend on `@udecode/slate`. @zbeyens Is there a workaround for this, or should we settle for duplicating them?
**Usage**
Most or all Plate transforms that insert a node accept an options type inheriting from `InsertNodesOptions`; if anyone finds a transform that does not expose these options, feel free to make a PR. This is where you can add the `removeEmpty: true` option to enable this behaviour.
If you want empty blocks other than paragraphs to be …

Add `removeEmpty` option to `insertNodes`

---

CONTRIBUTING.md

Running `yarn build:registry` manually is not necessary, since it's [handled in CI](https://github.com/udecode/plate/blob/main/.github/workflows/registry.yml#L41).

Remove instruction to build registry from CONTRIBUTING.md

---

.changeset/silver-rings-own.md
packages/serializer-html/src/elementToHtml.ts
packages/serializer-html/src/utils/createElementWithSlate.ts

Fix: `serializeHtml` mutates the live `editor` instance

---

.changeset/calm-tables-kick.md
apps/www/src/lib/plate/demo/comments/CommentsProvider.tsx
packages/comments/src/components/CommentDeleteButton.tsx
packages/comments/src/components/CommentEditSaveButton.tsx
packages/comments/src/components/CommentNewSubmitButton.tsx
packages/comments/src/components/CommentResolveButton.tsx
packages/comments/src/stores/comments/CommentsProvider.tsx
yarn.lock

The `onCommentAdd`, `onCommentUpdate` and `onCommentDelete` callbacks weren't using the `{ fn: ... }` pattern required by jotai-x. This problem was masked by jotai-x silently wrapping the functions in `{ fn: ... }` anyway but not amending the types.

Fix CommentsProvider callbacks

---

.changeset/serious-masks-punch.md
packages/table/src/components/TableCellElement/useTableCellElementState.ts
packages/table/src/merge/mergeTableCells.ts
packages/table/src/merge/unmergeTableCells.ts
packages/table/src/queries/getTableOverriddenColSizes.ts
packages/table/src/transforms/insertTableRow.ts

- Fixes merge of headers in table
- `rowSizeOverrides.get` sometime were undefined, that is why added ooptional type check
- collapseSelection helps not to select cells on merge

[Table] Fix merge headers

---

.changeset/rotten-foxes-tickle.md
packages/table/src/merge/mergeTableCells.ts

Fixes following error by normalizing lodash cloneDeep import to be consistent with other imports in the repo
> SyntaxError: Named export 'cloneDeep' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.

Normalize cloneDeep import

---

apps/www/src/config/customizer-plugins.ts

closes https://github.com/udecode/plate/issues/2848
Changed route in builder drawer to docs/serializing-md.
Link now takes user to docs instead of a 404 page.

fix: changed docs/serializing-markdown route to docs/serializing-md

---

.changeset/violet-years-train.md
packages/core/CHANGELOG.md
packages/core/src/utils/pipeHandler.ts

Description
This pull request addresses the issue described in [udecode/plate#2794](https://github.com/udecode/plate/issues/2794). The main goal was to resolve the type mismatch issue between DOM events and React's synthetic events, particularly for the onDOMBeforeInput event handler.
After discussing the issue with the community on Discord, two main solutions were proposed. I opted for the second solution, which involves manually creating an object compatible with React's SyntheticEvent interface and passing this object to pipeHandler instead of the native DOM event. This approach was chosen because it allows maintaining the current consumer types in Plate, while also addressing the type mismatch issue.
Here’s a summary of the changes:
Implemented a function …

fix: implement dom to react synthetic event conversion

---

.changeset/nervous-nails-bathe.md
packages/serializer-md/src/deserializer/createDeserializeMdPlugin.ts
packages/serializer-md/src/deserializer/types.ts
packages/serializer-md/src/deserializer/utils/deserializeMd.spec.tsx
packages/serializer-md/src/deserializer/utils/deserializeMd.ts
packages/serializer-md/src/remark-slate/remarkDefaultElementRules.ts
packages/serializer-md/src/remark-slate/types.ts
packages/utils/src/types/types.ts

The `indentList` option handles markdown conversion of ordered and unordered lists when the indentList plugin is being used
Fixes MD deserialization compatibility with IndentList plugin
Testing:
- Unit tests added
- Tested on playground (by modifying plugin options locally)
Before
https://github.com/udecode/plate/assets/16997807/a2f9cd79-3622-4f9b-a058-6ca50e23e486
After
https://github.com/udecode/plate/assets/16997807/c16cc7d2-1f32-4843-926b-b0a049b260ef

indentList option for MD deserializer

---

.changeset/brown-gifts-smoke.md
packages/table/src/withDeleteTable.ts

`isRangeInSameBlock` was called but not used.

fix: remove unused code

---

apps/www/package.json
apps/www/src/app/_components/home-tabs.tsx
yarn.lock

- Update package name from `next-usequerystate` to `nuqs`
- Add type-safety for the 'builder' boolean search param.
Announcement about package name migration here: https://github.com/47ng/nuqs/discussions/438.
This only affects the `www` webapp.

[www] Migrate `next-usequerystate` to `nuqs`

---

.changeset/good-cats-scream.md
.changeset/smart-poems-marry.md
.changeset/violet-mugs-shake.md
apps/www/content/docs/components/changelog.mdx
apps/www/src/registry/default/plate-ui/table-element.tsx
packages/core/src/libs/jotai.ts
packages/table/src/createTablePlugin.ts
packages/table/src/stores/tableStore.ts
yarn.lock

Fix table store issues

---

.changeset/six-papayas-tan.md
packages/core/src/components/Plate.spec.tsx
packages/core/src/components/Plate.tsx

When we use the `editor` prop to instantiate Plate, we have a desynchronization  between the `editor` id and the id in the plate store.
Plugin like `Mention` can't work because we check the `editorId` and the `focusedEditorId`:
```ts
const focusedEditorId = useEventEditorSelectors.focus?.() // undefined
const editorId = usePlateSelectors().id()
if (
focusedEditorId !== editorId
) {
return null
}
```
Without this fix, we need to set the editor id and the plate id with the same value:
```tsx
const editor = createPlateEditor({
id: 'test',
})
return (
<Plate id="test" editor={editor}>
// ...
</Plate>
)
```

fix plate store id with editor prop

---

.changeset/shiny-steaks-whisper.md
packages/toggle/src/queries/getLastEntryEnclosedInToggle.ts

Error while importing from `@udecode/plate-toggle`
Module not found: Error: Can't resolve 'lodash/last' in '/app/node_modules/@udecode/plate-toggle/dist' Did you mean 'last.js'?
BREAKING CHANGE: The request 'lodash/last' failed to resolve only because it was resolved as fully specified (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"'). The extension in the request is mandatory for it to be fully specified. Add the extension to the request.

Update `lodash.last` import in `getLastEntryEnclosedInToggle.ts`

---

apps/www/src/config/customizer-plugins.ts

`docs/todo-list` gives a 404, the doc for the todo list in under `docs/list`

Fix todo list doc path

---

apps/www/src/app/_components/installation-code.tsx

Very very small PR (one word command change!).
Copying the install command for bun (provided through `copy-button.tsx`) populates the command with `yarn add` as currently deployed. This command changes that to `bun add` to avoid that small friction/inconsistency with the rest of the commands as the rest are configured as expected.
As far as I can tell this is the only instance of `__bunCommand__` that's not properly updated! I did a big `CMD + F` in VS Code and the install command seems to be the only `bun` command that's affected.

Fix bun install command for install docs

---

.changeset/chatty-rocks-think.md
packages/cli/src/utils/templates.ts
packages/cli/src/utils/transformers/transform-tw-prefix.ts
packages/cli/test/utils/__snapshots__/transform-tw-prefix.test.ts.snap
packages/cli/test/utils/transform-tw-prefix.test.ts

fix prefix

---

apps/www/content/docs/components/changelog.mdx
apps/www/src/registry/default/plate-ui/mention-combobox.tsx

Fix: Mention input removed when clicking mention combobox scrollbar

---

.changeset/beige-kids-suffer.md
packages/serializer-html/src/__tests__/serializeHtml/classNames.spec.ts
packages/serializer-html/src/utils/stripClassNames.ts
yarn.lock

- Fix handling of empty `preserveClassNames` array
- Previously, would output `<div class="                 ">`
- Now, it outputs `<div>`
- Reduce time complexity of `stripClassNames` function
- Simplify RegEx patterns
- Add a test case to ensure content doesn't get replaced

[serialize-html] Fix handling of empty `preserveClassNames` array

---

.changeset/light-comics-dream.md
packages/alignment/src/__tests__/setAlign/left.spec.tsx
packages/alignment/src/createAlignPlugin.ts
packages/alignment/src/hooks/useAlignDropdownMenu.ts
packages/alignment/src/types.ts

Resolves https://github.com/udecode/plate/issues/2946.
Alignment plugin:
- Support 'start' and 'end' values for supporting right-to-left languages
- Default to 'start' (which is [the initial value](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#formal_definition) for browsers)

[alignment] Support 'start' and 'end' values, default to 'start'

---

.changeset/great-buses-switch.md
packages/diff/src/internal/utils/string-char-mapping.spec.ts
packages/diff/src/internal/utils/string-char-mapping.ts

Fix `StringCharMapping` key order dependency

---

.changeset/old-numbers-ring.md
packages/emoji/src/utils/EmojiLibrary/EmojiFloatingLibrary.ts
packages/emoji/src/utils/EmojiLibrary/EmojiInlineLibrary.ts

Allows testing with Vitest in full ESM mode, otherwise we get: 
```
TypeError: Module "file:///[...]/node_modules/.pnpm/@emoji-mart+data@1.1.2/node_modules/@emoji-mart/data/sets/14/native.json" needs an import attribute of type "json"
```

fix: add assertion on emoji-mart data for ESM mode

---

apps/www/content/docs/autoformat.mdx

Adding options to the autoFormatPlugin
Problems: 
Real implementation will have typescript error saying `Object literal may only specify known properties, ...`
Fixed by adding: 
```tsx
import { createAutoformatPlugin } from '@udecode/plate-autoformat';
const plugins = [
// ...otherPlugins,
createAutoformatPlugin({
options: {
rules: autoformatRules,
enableUndoOnDelete: true,
},
}),
];
```

fix: Doc missing 'options' for autoFormatPlugin

---

apps/www/content/docs/caption.mdx

This is just one line change to the doc of `createCaptionPlugin`, and it does not seem to be much of the problem here. However, IMO, I would like to keep as consistent and should be intuitive .
Change:
```
import { createCaptionPlugin } from './createCaptionPlugin';
```
Modified
```
import { createCaptionPlugin } from '@udecode/plate-caption';
```

fix: relative 'import' caption in doc

---

.changeset/lovely-llamas-call.md
packages/cloud/src/cloud/types.ts
packages/cloud/src/cloud/uploadFiles.ts
packages/cloud/src/cloud/withCloud.ts
packages/cloud/src/image/withCloudImage.ts

Please see some more information in the #3002 .

fix: #3002

---

.changeset/fluffy-donuts-roll.md
packages/diff/src/computeDiff.spec.ts
packages/diff/src/computeDiff.ts
packages/diff/src/internal/transforms/transformDiffDescendants.ts
packages/diff/src/internal/transforms/transformDiffNodes.ts

- Add `shouldDiffDescendants` option to `computeDiff` to control whether a pair of descendant lists should be diffed. If false, the parent node will be deleted and re-inserted. Defaults to `() => true`.
- Example use case: To prevent `computeDiff` from diffing the text of unrelated paragraphs, use a text similarity checking algorithm to determine whether the paragraphs are sufficiently similar, and return false if not.
- When multiple consecutive nodes have been deleted and inserted, `computeDiff` now groups all consecutive deletions together and does the same with all consecutive insertions.
- Example of a diff prior to this change:
```diff
- Old paragraph 1
+ New paragraph 1
- Old paragraph 2
+ New paragraph 2
```
- Example of a diff after this change:
```diff
- Old …
```

Add `shouldDiffDescendants`

---

.changeset/dirty-clocks-hide.md
packages/diff/src/computeDiff.spec.ts
packages/diff/src/computeDiff.ts
packages/diff/src/internal/transforms/transformDiffDescendants.ts
packages/diff/src/internal/transforms/transformDiffNodes.ts
packages/diff/src/internal/utils/diff-nodes.ts

- Remove `shouldDiffDescendants` option in favour of `elementsAreRelated`.
- The `elementsAreRelated` option controls whether `computeDiff` treats a given pair of elements as "related" and thus tries to diff them. By default, elements are related if they have the same `children` OR they differ only in their `children`. Return null to use the default logic for a pair of elements.
- Use case: In addition to supporting the same use case as the deprecated `shouldDiffDescendants`, `elementsAreRelated` can be used to ensure that `computeDiff` compares the correct pair of paragraphs.
For example, by default, `computeDiff` would compare `My slightly modified paragraph.` with `New paragraph` in the following diff.
```diff
- My slightly modified paragraph.
+ New paragraph
+ My …
```

Replace `shouldDiffDescendants` with `elementsAreRelated`

---

.changeset/fuzzy-beds-tie.md
packages/table/src/queries/getTableColumnIndex.ts

If nothing exists, set colIndex to -1 instead of 0 so that we can discern from a "not found" and an actual index 0 value.
For PlateJS tables, we use this code:
```
const { colIndex, rowIndex, readOnly, selected, hovered, hoveredLeft, rowSize, borders, isSelectingCell, colSpan } =
useTableCellElementState();
```
to grab the colIndex and rowIndex.
However, I'm finding that with the right memoizations, when the editor refreshes, `colIndex` is briefly set to 0 before it's set back to the expected value.
There's no way to discern the "not found" value and the actual index 0 value.

Set "not found" value to -1 instead of 0 for colIndex

---

templates/plate-playground-template/src/components/plate-editor.tsx

As discussed in issue https://github.com/udecode/plate/issues/2993 and in discord, the editor should be placed in a `relative` div so that DnD adjusts the cursor overlay position accordingly.

fix: make editor div relative to fix DnD

---

.changeset/witty-vans-lick.md
packages/toggle/src/injectToggle.tsx

An element hidden by a toggle can still take some vertical space if an inner element has a vertical margin. This PR addresses this issue

Toggle > injectToggle.tsx > Make hidden elements overflow hidden to account for inner elements with a vertical margin

---

.changeset/chatty-flowers-move.md
packages/table/src/merge/getTableGridByRange.ts

In PR https://github.com/udecode/plate/pull/3029 I forgot to reset `cellEntries` array. It leads to unexpected errors when merging cells in a few corner cases.

Hotfix: reset cell entries list when table is overflown

---

.changeset/eighty-monkeys-poke.md
packages/excalidraw/package.json
yarn.lock

This commit fixes a potential XSS vulnerability in the `@udecode/plate-excalidraw` package by updating the `@excalidraw/excalidraw` dependency to version `0.16.0`.
Security Advisory: https://github.com/advisories/GHSA-v7v8-gjv7-ffmr
Snyk Report: https://security.snyk.io/vuln/SNYK-JS-EXCALIDRAWEXCALIDRAW-5841658
Patches for `@excalidraw/excalidraw` were introduced in version `0.15.3`; however, as advised by the Snyk Report, I've updated it to version `0.16.0`.

Fix: CVE-2023-26140

---

.changeset/old-fireants-relate.md
apps/www/src/components/icons.tsx
apps/www/src/components/plate-ui/playground-fixed-toolbar-buttons.tsx
apps/www/src/lib/plate/demo/plugins/autoformatIndentLists.ts
apps/www/src/lib/plate/demo/values/indentListValue.tsx
apps/www/src/registry/default/example/playground-demo.tsx
apps/www/src/registry/default/plate-ui/indent-todo-marker-component.tsx
apps/www/src/registry/default/plate-ui/indent-todo-toolbar-button.tsx
packages/indent-list/src/createIndentListPlugin.ts
packages/indent-list/src/hooks/index.ts
packages/indent-list/src/hooks/someIndentList.ts
packages/indent-list/src/hooks/someIndentTodo.ts
packages/indent-list/src/hooks/useIndentTodoToolbarButton.ts
packages/indent-list/src/injectIndentListComponent.tsx
packages/indent-list/src/queries/areEqListStyleType.ts
packages/indent-list/src/queries/getIndentListSiblings.ts
packages/indent-list/src/transforms/indentList.ts
packages/indent-list/src/transforms/outdentList.ts
packages/indent-list/src/transforms/setIndentListNode.ts
packages/indent-list/src/transforms/setIndentListNodes.ts
packages/indent-list/src/transforms/setIndentListSiblingNodes.ts
packages/indent-list/src/transforms/toggleIndentList.ts
packages/indent-list/src/transforms/toggleIndentListSet.ts
packages/indent-list/src/transforms/toggleIndentListUnset.ts
yarn.lock

1. The code I wrote when I just started learning Plate may have some issues. I didn't submit a pull request at that time because there were two checkboxes.
2. Until no issues, I will continue to write markComponent and supplement autoformat rules, or test case.
3. The issue now is that sometimes the cursor behaves abnormally when clicking on the leftmost part of the checkbox.Regarding this, do you have any good suggestions?
4. I close the last pr

feat:indent-toodo

---

.changeset/happy-experts-kneel.md
packages/indent-list/src/injectIndentListComponent.tsx
yarn.lock

fix pressing Arrow Up

---

.changeset/purple-pens-share.md
packages/serializer-html/src/__tests__/serializeHtml/elements.spec.ts
packages/serializer-html/src/__tests__/serializeHtml/with-useEditor.spec.ts
packages/serializer-html/src/elementToHtml.ts
packages/serializer-html/src/leafToHtml.ts
packages/serializer-html/src/utils/renderToStaticMarkupClient.ts

Fixes #1123
Fixes #1047
Related issue on slate https://github.com/ianstormtaylor/slate/issues/5012
See [react APIs update](https://react.dev/reference/react-dom/server/renderToString#removing-rendertostring-from-the-client-code) for more details
- Removes `renderToStaticMarkup` from client code
- Now, the lack of `react-dom/server` import will reduce bundle size
- Since serialize will render client react apis, unwanted warnings wont ashore the console

[SerializerHtml] Remove `renderToStaticMarkup` from client code

---

.changeset/tame-beans-deliver.md
packages/heading/src/createHeadingPlugin.ts
packages/heading/src/types.ts

I would like to add the headings nodes to `h3` without the `h1` node.
So I changed the API to make it more customisable.
**Example**
Before
```ts
createHeadingPlugin({ options: { levels: 3 } })
// Create headings from 1 to 3
```
After 
```ts
createHeadingPlugin({ options: { levels: [2, 3] } })
// Create headings 2 and 3
```

[Heading Plugin] Customise Heading levels

---

.changeset/fresh-turkeys-jam.md
packages/basic-elements/src/createBasicElementsPlugin.ts
packages/basic-marks/src/createBasicMarksPlugin.ts
packages/core/src/client/plugins/react/createReactPlugin.ts
packages/core/src/shared/plugins/createHistoryPlugin.ts
packages/heading/src/createHeadingPlugin.ts
packages/list/src/createListPlugin.ts
packages/normalizers/src/createRemoveEmptyNodesPlugin.ts

Export plugin keys for easier access plugin options by key

---

apps/www/src/app/_components/installation-tab.tsx

issue: #3202 
When `isManual` is false, `installCommands.components` returns unexpected value.
```ts
isManual && ' tooltip' // returns 'false'
```
So, I changed the code as below
```ts
isManual ? ' tooltip' : '' // returns ''
```
It's the result!

 Fix: Command is invalid, when I install emoji-combobox in platejs.org 

---

.changeset/plenty-suits-serve.md
.changeset/silly-candles-return.md
packages/link/src/components/FloatingLink/useFloatingLinkEdit.ts
packages/link/src/components/FloatingLink/useFloatingLinkInsert.ts

close #3144
I fixed the zIndex of `useFloatingLinkInsert` according to 12joan's comment, but the same problem still exists.
So I resolved this issue by fixing the zIndex of `useFloatingLinkEdit`.
It works without any problems.
But I'm not sure if changing the zIndex to 30 is the best way.
https://github.com/udecode/plate/assets/77661228/a1f607dd-c7ed-46bb-820e-faa549fb9343

fix: zIndex of floating link

---

.changeset/sour-candles-sneeze.md
packages/alignment/src/client/useAlignDropdownMenu.ts
yarn.lock

The changes in `useAlignDropdownMenu.ts` refactor the logic used to determine the alignment of text in a dropdown menu. The new implementation imports additional functions (`getNodeEntries`, `isBlock`) and uses them to iterate over block nodes within the editor's selection. It then determines a common alignment or defaults to 'left' if alignments differ among nodes. This approach replaces the previous method of finding a single node and checking its alignment, making the new logic more robust and capable of handling multiple nodes with potentially different alignments.
I have discussed this bug in detail here https://github.com/udecode/plate/issues/3171

Bug : Refactor alignment determination logic in useAlignDropdownMenuState

---

apps/www/content/docs/components/changelog.mdx
apps/www/src/components/site-header.tsx
apps/www/src/registry/default/plate-ui/fixed-toolbar.tsx

close  #3213
zIndex of FloatingToolbar is 50
I change the zIndicies of SiteHeader and FixedToolbar to 60
https://github.com/udecode/plate/assets/77661228/95e46e78-e8ad-416f-95aa-c5d66331c65c

Fix: zIndicies of the SiteHeader and FixedToolbar #3213

---

.changeset/yellow-chairs-smile.md
packages/trailing-block/src/withTrailingBlock.ts

We're in the process of migrating from Slate to Plate and due to us wanting to maintain backward compatibility between the two editor data formats, we have to customize most plugins to use custom element types. We did notice that the trailing block plugin is broken when trying to override the trailing block type which is already supported in the options but isn't working correctly because the trailing block is always defaulting to the default type configured on an editor level which doesn't seem to be intended behavior.

Trailing Block plugin fixes

---

.changeset/calm-mails-flow.md
packages/floating/src/hooks/useFloatingToolbar.ts

fix: add mouse down

---

.changeset/long-rocks-relate.md
packages/combobox/src/hooks/useHTMLInputCursorState.ts

Fixes two issues affecting `useHTMLInputCursorState`:
- Synchronously triggering a rerender on the `input` event was preventing the `<input>` from receiving keystrokes in Chrome and WebKit.
- The `selectionchange` event is not currently supported for `<input>` elements outside of Firefox. Added other events as fallbacks.

Fix compatibility of `useHTMLInputCursorState` with Chrome and WebKit

---

.changeset/fuzzy-dolls-speak.md
apps/www/content/docs/components/changelog.mdx
packages/caption/src/components/CaptionTextarea.tsx
yarn.lock

Currently, the caption plugin is using an internal React state variable as the source of truth for the caption value. While it is updating the Slate element's `caption` property when the caption value changes, it is only reading the element `caption` property to set the _initial_ value of the aforementioned React state. So after the caption mounts, external changes to the element's `caption` property do not get reflected in the caption textarea.
In my app, this bug is most apparent when using undo/redo. After typing some text into a caption textarea, the undo action will revert one character at a time in the `caption` property on the element itself, but the caption textarea will remain unchanged.
This PR removes the internal React state variable and uses the element's `caption` property …

Update caption UI when element `caption` property changes

---

apps/www/content/docs/components/changelog.mdx
templates/plate-playground-template/src/components/plate-ui/floating-toolbar.tsx

fix(templates): added `portalElement` in `floating-toolbar` component.

---

apps/www/src/components/ui/sheet.tsx

the sheet (customization sidebar) component was being overlapped by the main navbar and editor's tools.
this PR fixes the issue by increasing the z-index of the sidebar.
this is a very **small** but **impactful** fix that improves the overall UI experience. :)

increased z-index to fix overlapping of navbar and editors toolbar

---

.changeset/lemon-trees-pay.md
packages/plate-utils/src/shared/createNodeHOC.tsx

fix: omit plate properties from createNodeHOC props

---

.changeset/curvy-ligers-try.md
packages/media/CHANGELOG.md
packages/media/src/media/useMediaState.ts

`@udecode/plate-media@34.0.0` included a change to `useMediaState` that set the default `align` to 'left', overriding the defaults of 'center' specified in the image and media embed elements.
**Checklist**

Allow components using `useMediaState` to choose their own default `align`

---

.changeset/violet-worms-guess.md
apps/www/content/docs/table.mdx
apps/www/src/components/plate-ui/playground-fixed-toolbar-buttons.tsx
packages/table/src/utils/getEmptyCellNode.ts
packages/table/src/utils/getEmptyTableNode.ts

**Checklist**
Before, when trying to insert a table or table row/column with the header property set (something like `insertTable(editor, { header: true });`), you'd get an error with the following message.
> TypeError: Cannot read properties of undefined (reading 'children')
../src/utils/getEmptyCellNode.ts (19:27) @ children
This should be fixed now. In addition, setting `header: true` on insertTable would make every row in the table a header row, rather than just the first one (see #3131). Finally, I updated some documentation and fixed an issue with the table toolbar option not showing up in one of the table examples.

Fix table headers not working correctly

---

.changeset/quick-falcons-vanish.md
apps/www/content/docs/link.mdx
packages/link/src/createLinkPlugin.ts
packages/link/src/transforms/submitFloatingLink.ts

**Checklist**
Adds `transformInput` option to `LinkPlugin` which allows transforming the input from the user before validation. There was already a similar function `getUrlHref` which is applied to all spaced text in the editor. I therefore made the two compatible so you can pass the same function.
However there is no existing transform being applied to the URL input which means if you use `getUrlHref` your text editor may make links out of things more permissively than the URL input itself, which is strange behaviour, e.g., if you add protocols (`google.com` => `https://google.com`).
I also made it two separate functions because you may not want to use `getUrlHref` but you may want to have more permissive URLs in the input (my case) or even if you use both `getUrlHref` may require …

feat: add transformInput to LinkPlugin

---

.changeset/dull-dryers-sip.md
apps/www/src/components/plate-ui/playground-more-dropdown-menu.tsx
apps/www/src/registry/default/plate-ui/more-dropdown-menu.tsx
packages/combobox/src/hooks/useHTMLInputCursorState.ts
packages/normalizers/src/createRemoveEmptyNodesPlugin.ts
packages/plate-utils/src/useFormInputProps.ts
packages/selection/src/queries/index.ts
packages/table/src/queries/getTableColumnCount.spec.tsx
templates/plate-playground-template/src/components/plate-ui/more-dropdown-menu.tsx

The `MoreDropdownMenu` component had incorrect behavior for toggling the Superscript and Subscript marks. The behavior of these marks was swapped; selecting **Superscript** was incorrectly setting the **Subscript** mark and vice versa. Additionally, the `clear` and `key` parameters needed adjustments to ensure the correct mark is toggled while clearing the other.
**Summary of Changes**:
- Updated the `clear` parameter to include both `MARK_SUBSCRIPT` and `MARK_SUPERSCRIPT`.
- Corrected the `key` values for Superscript and Subscript, which were previously swapped.
**Checklist**:
- **MoreDropdownMenu**: Fixed the toggling behavior for Superscript and Subscript marks.

fix: corrected toggle calls for Superscript and Subscript

---

.changeset/purple-windows-wink.md
packages/core/src/shared/plugins/createDeserializeAstPlugin.ts
packages/link/src/components/FloatingLink/FloatingLinkUrlInput.tsx

**Checklist**
Fixes an error that happens sometimes when unmounting the Link edit input. The error itself is mostly benign as it happens inside `setTimeout` however it interferes with our testing framework and not ideal to have errors in the logs.
The Link edit input appears to work correctly despite the error:
https://github.com/user-attachments/assets/16516370-b5e5-419c-b40d-a07664d98b7c

fix: link update error after umounting input

---

.changeset/ten-apes-melt.md
packages/serializer-md/src/serializer/serializeMdNode.ts

I believe the if check contains a mistake and it should check whether the child is a leaf and not the node/parent.
**Checklist**

fix(serializer-md): invalid condition for ignoreParagraphNewLine

---

apps/www/content/docs/getting-started.mdx

Without the updated imports, the example code will not run. Including `PlateContent` and the full `Editor` import provides context about which components are belong to Plate and which are custom, helping bring clarity to the next explainer paragraph.
Also, as Plate is a "collection of re-usable components that you can copy and paste into your apps" if feels like a mistake that you cannot copy/paste the getting-started examples.

updates example code imports to match instructions

---

.changeset/orange-months-sort.md
package.json
packages/plate-utils/package.json
packages/plate-utils/src/react/usePlaceholder.ts
yarn.lock

**Checklist**
fixes #3425 
fixes #3250

fix: support composition event in placeholder

---

.changeset/eight-bugs-look.md
packages/core/src/lib/editor/SlateEditor.ts
packages/core/src/lib/plugin/BasePlugin.ts

**Checklist**
getOption signature when the option is not a setter function is wrong. Change to never[] instead of never

fix: fix type signature

---

.changeset/twenty-cows-count.md
packages/plate-utils/src/react/usePlaceholder.ts

**Checklist**
Modify logic a little bit that makes more sense.

fix: fix incorrect placeholder when both hideOnBlur and composing occurs

---

.changeset/ninety-badgers-run.md
packages/table/src/lib/merge/computeCellIndices.ts
packages/table/src/lib/merge/insertTableColumn.ts
packages/table/src/lib/merge/insertTableRow.ts
packages/table/src/react/components/TableElement/useTableElement.ts
packages/table/src/react/merge/deleteColumn.ts
packages/table/src/react/merge/deleteRow.ts
packages/table/src/react/merge/unmergeTableCells.ts
packages/table/src/react/withSetFragmentDataTable.ts

**Checklist**
Fixed errors in calculating row and column indexes of complex merged cells and unMerge function

Fix unmerge, compute cell indices, delete row / column, add row / column

---

apps/www/src/registry/default/plate-ui/indent-todo-toolbar-button.tsx
templates/plate-playground-template/pnpm-lock.yaml
templates/plate-playground-template/src/components/icons.tsx
templates/plate-playground-template/src/components/plate-editor.tsx
templates/plate-playground-template/src/components/plate-ui/fixed-toolbar-buttons.tsx
templates/plate-playground-template/src/components/plate-ui/indent-todo-marker-component.tsx
templates/plate-playground-template/src/components/plate-ui/indent-todo-toolbar-button.tsx

Add todo to playground template

---

.changeset/few-pans-float.md
packages/markdown/src/lib/deserializer/utils/deserializeMd.spec.tsx
packages/markdown/src/lib/remark-slate/remarkDefaultElementRules.ts

it will throw error when deserializing list with indented block element (eg. code block)  using `@udecode/plate-markdown`
<pre>
- 1
- 2
- 2.1
```
2.2 code
```
</pre>
it expects to render a nested code block element like this rendered by github: 
----
- 1
- 2
- 2.1
```
2.2 code
```
----
while using `@udecode/plate-markdown` to deserializing it will throw runtime errors.
`@udecode/plate-markdown` will treat every child of `list` as `listItem`. But it's totally legal to put another element into `list`

Fix @udecode/plate-markdown deserializing list with indented block element

---

apps/www/content/docs/components/changelog.mdx
apps/www/src/registry/default/plate-ui/mention-element.tsx

I'm currently researching plate.js for its editor capabilities, and I came across an issue with the mention component similar to the one in https://github.com/ianstormtaylor/slate/pull/5685.
So I decided to fix this issue. On MacOS browsers, typing in nodes after the spacer tag interrupts the IME. Additionally, pressing the delete key at this point also causes some issues with the selection position.
Moving the spacer node forward can fix this issue. However, on Android devices, it still needs to stay in its original position.
**Checklist**

fix: mention component interrupt IME

---

.changeset/rich-boats-fix.md
packages/link/src/react/components/FloatingLink/useFloatingLinkEdit.ts

Fixed the problem that the LinkFloatingToolbar disappears when clicking anywhere when inserting a link
**Checklist**
[video:before](https://github.com/user-attachments/assets/44575852-bc5b-4cc7-81c9-302d5473606d)
[video:after](https://github.com/user-attachments/assets/8bb2e224-008e-4596-9dd6-f5cf2a20d47f)

Insert link issue

---

.changeset/honest-apples-grab.md
packages/callout/src/lib/transforms/insertCallout.ts
packages/callout/src/react/hooks/useCalloutEmojiPicker.ts

fix set local storage

---

.changeset/large-items-remember.md
packages/ai/src/react/copilot/utils/getNextWord.spec.ts
packages/ai/src/react/copilot/utils/getNextWord.ts

Fix the copilot issues with mixed Chinese and English text.

---

apps/www/content/docs/components/changelog.mdx
apps/www/content/docs/components/installation/manual.mdx
apps/www/content/docs/components/installation/next.mdx
apps/www/content/docs/components/installation/vite.mdx
apps/www/src/components/icons.tsx
apps/www/src/components/plate-ui/playground-fixed-toolbar-buttons.tsx
apps/www/src/components/plate-ui/playground-floating-toolbar-buttons.tsx
apps/www/src/components/plate-ui/playground-insert-dropdown-menu.tsx
apps/www/src/components/plate-ui/playground-mode-dropdown-menu.tsx
apps/www/src/components/plate-ui/playground-more-dropdown-menu.tsx
apps/www/src/components/plate-ui/playground-turn-into-dropdown-menu.tsx
apps/www/src/registry/default/example/cards/cards-toolbar.tsx
apps/www/src/registry/default/example/mode-toggle.tsx
apps/www/src/registry/default/plate-ui/align-dropdown-menu.tsx
apps/www/src/registry/default/plate-ui/column-group-element.tsx
apps/www/src/registry/default/plate-ui/insert-dropdown-menu.tsx
apps/www/src/registry/default/plate-ui/slash-input-element.tsx
apps/www/src/registry/default/plate-ui/table-dropdown-menu.tsx
apps/www/src/registry/default/plate-ui/table-element.tsx
apps/www/src/registry/default/plate-ui/turn-into-dropdown-menu.tsx

Remove icons

---

.changeset/dirty-rockets-sort.md
packages/core/src/react/components/DefaultLeaf.tsx

Fix DefaultLeaf props

---

.changeset/clean-cups-sort.md
packages/media/src/lib/media-embed/parseTwitterUrl.ts

**Checklist**
Currently, the logic for parsing Twitter URLs does not work in x. So I modified the existing logic. 
You can test it through the URL below.
https://x.com/pudgypenguins/status/1789664435079975016

fix: parseTwitterUrl logic

---

.changeset/beige-peaches-divide.md
packages/caption/src/react/components/CaptionTextarea.tsx

**Checklist**
hello. When using Caption, there was an issue where each Korean character was cut off when entering Korean characters. A video is attached for explanation.
I thought it was an IME issue and modified the code.
And the result is as shown in the video below.
I didn't know how to test the plate example within the package, so I brought the source locally, modified it, and checked its operation.
I am willing to continue contributing to your project. It would be good if the contributing guidelines included guidelines on how to test immediately after changing a component or plugin.
If you don't like the source code, you can modify it at will.

fix: caption text area korean ime issue

---

.changeset/fresh-carrots-smile.md
packages/find-replace/src/lib/__tests__/decorateSearchHighlight/search/empty.spec.ts
packages/find-replace/src/lib/__tests__/decorateSearchHighlight/search/text.spec.ts
packages/find-replace/src/lib/decorateFindReplace.ts
yarn.lock

**Checklist**
- [] [ui changelog](apps/www/content/docs/components/changelog.mdx)

fix: #3813

---

apps/www/content/docs/api/core/plate.mdx

I noticed that some of the documentation was outdated for `onValueChange`
**Checklist**

fix: correct documentation for onValueChange

---

.changeset/pink-pillows-end.md
packages/math/src/react/hooks/useEquationInput.ts

fix for #3851 
I tried setting the caret position manually through reference of this [fix](https://stackoverflow.com/questions/46000544/react-controlled-input-cursor-jumps), but it seems that input of foreign character (e.g. Chinese) through a virtual keyboard still has the same issue.
It seems that the original logic is just to reset the value to the previous when it closes on dismiss, so i used just store a value in ref on open and set it back on close
**Checklist**

fix: correct setvalue in equation input behavior

---

.changeset/few-knives-refuse.md
packages/code-block/src/lib/insertDataCodeBlock.ts
packages/code-block/src/lib/withCodeBlock.ts

When pasting from vscode, automatically turn it into a code block with the correct language
**Checklist**

add vscode data paste handle

---

.changeset/cool-sloths-protect.md
packages/core/src/lib/plugins/html/utils/deserializeHtml.ts
packages/core/src/lib/utils/normalizeDescendantsToDocumentFragment.spec.tsx
packages/core/src/lib/utils/normalizeDescendantsToDocumentFragment.ts
yarn.lock

**Checklist**
Parametrize the default element used when deserializing HTML

Add option to change the default plugin to use when deserializing html

---

.changeset/wet-doors-perform.md
packages/dnd/src/hooks/useDropNode.ts
packages/dnd/src/transforms/onDropNode.ts
packages/dnd/src/transforms/onHoverNode.ts

Fix dnd from file system

---

.changeset/curly-hornets-judge.md
packages/core/src/lib/utils/getInjectMatch.ts

It should exit if the injection is intended for elements (`isElement`) and if the current node is NOT an element.
**Checklist**

Fix props injection condition check for elements

---

.changeset/tidy-jars-poke.md
packages/link/src/react/components/useLinkToolbarButton.ts

**Checklist**
Before, if the user clicked the link button in the toolbar when the editor was not focused, the floating toolbar popup would show up near or off the edge of the editor.
Now, clicking the link button will first auto-focus on the editor before opening up the floating link popup. That way the floating popup always appears in the correct position.
While I am not sure, this fix sounds like it may fix issue #3812. I tried to reproduce the bug described in this issue, however the symptoms I was experiencing were slightly different. I noticed the floating popover was misplaced after the first click of the link button, whereas they reported the issue after the second click. This may fix both issues though.

fix: focus the editor before opening the floating link toolbar

---

.changeset/kind-kiwis-know.md
packages/list/src/react/TodoListPlugin.tsx

Hello! I'm using `TodoListPlugin` and noticed that `TodoListPlugin.key` is typed as `any` whereas I think it should be `'action_item'` as string literal. Every other plugin I've checked has a specific string literal type for `key` so I think it's just a little mistake. Thanks :)
**Checklist**

Set `TodoListPlugin` typescript types

---

.changeset/lemon-keys-eat.md
packages/core/src/react/stores/plate/useEditorPlugin.ts

Before, if there are two tables in one document, selecting multiple table cells will cause page crash, like #4077. Now it will work normally.
The problem is that `useEditorPlugin` doesn't return a stable value. In `useSelectedCells`, the `setOption` returned by `useEditorPlugin` will change in every re-render. While the `useSelectedCells` called by the first table sets `selectedCells` to a non-null value, the `useSelectedCells` called by the second table will set `selectedCells` back to null, and it repeats infinitely.
```tsx
// for the second table, `selected = false`, so it will set `selectedCells` to null when `setOption` changes
React.useEffect(() => {
if (!selected || readOnly) {
setOption('selectedCells', null);
setOption('selectedTables', null);
}
}, [selected, editor, readOnly, …
```

fix: return value of useEditorPlugin changes when rerender

---

apps/www/content/docs/en/components/changelog.mdx
apps/www/src/registry/default/plate-ui/image-preview.tsx
apps/www/src/registry/default/plate-ui/media-popover.tsx
templates/plate-playground-template/src/components/plate-ui/image-preview.tsx
templates/plate-playground-template/src/components/plate-ui/media-popover.tsx

Before, when image preview is open, right click on mask will open block menu, but the menu doesn't work. And media popover will be on top of the mask.
Now, right click on mask will open native context menu, and user can direct copy the image. Media popover will hide when image preview is open.
**Checklist**

fix: prevent block menu on image preivew mask

---

.changeset/gold-gorillas-report.md
apps/www/src/registry/default/components/editor/plugins/skip-mark-plugin.ts
packages/basic-marks/src/lib/BaseSkipMarkPlugin.spec.tsx
packages/basic-marks/src/lib/BaseSkipMarkPlugin.ts

Fix mention plugin conflict with skip mark plugin

---

apps/www/content/docs/en/components/changelog.mdx
apps/www/src/registry/default/plate-ui/block-context-menu.tsx
templates/plate-playground-template/src/components/plate-ui/block-context-menu.tsx

This PR introduces a check for the readOnly state to prevent the block context menu from appearing when the editor is in read-only mode. Previously, the context menu would still be triggered even when editing was disabled, which could lead to unintended UI interactions.
**Changes:**
- Introduced usePlateState("readOnly") to track the read-only state.
- Updated the onContextMenu event handler inside <ContextMenuTrigger> to prevent opening the context menu when readOnly is true.
**Why?**
This ensures a better UX by avoiding unnecessary context menu interactions in scenarios where content editing is not allowed.
**Testing:**
- Verified that the context menu does not appear in read-only mode.
- Confirmed that the menu works as expected when editing is enabled.
**Checklist**

Add readOnly state check to disable block context menu in read-only mode

---

.changeset/large-maps-smile.md
apps/www/src/registry/default/blocks/slate-to-html/page.tsx
apps/www/src/registry/default/components/editor/slate-to-html.tsx
packages/core/src/react/components/PlateContent.tsx

As per discussion: https://github.com/udecode/plate/discussions/4181, this PR makes sure the aboveEditable components only wrap the editable area by moving out the beforeEditable and afterEditable components.
**Checklist**

refactor: move out beforeEditable and afterEditable from aboveEditable render

---

.changeset/kind-parrots-impress.md
packages/markdown/src/lib/rules/defaultRules.ts
packages/markdown/src/lib/serializer/standardList.spec.tsx

Currently searialization of list lead to spaces per list entry. this is because the spread property is not set for list during serialization. 
This currently leads to:
```
1. test
3. test
- test
```
This pr reduces the noise by explicitly setting the spread oparator to false
```
1. test
3. test
- test
```
**Checklist**

adds explicit spread false to lists to have a less noisy serialization

---

.changeset/thin-garlics-pump.md
packages/link/src/lib/utils/getLinkAttributes.ts

I believe this fixes #3156. At the very least it fixes the following case:
```tsx
LinkPlugin.extend({
options: {
defaultLinkAttributes: {
target: '_blank',
},
}
});                                                                                                                            
```
Following the documentation startup instructions and using this resulted in anchors that had no `target` attribute. This patch fixed the issue.

Fix LinkPlugin having a `target` attribute. #3156

---

apps/www/src/registry/ui/table-node.tsx
docs/components/changelog.mdx

The table element's content was previously configured to remount inside a Radix popover (for the floating toolbar) when it became selected. Due to [changes to the timing](https://github.com/ianstormtaylor/slate/pull/5871/files#r2111732434) of `slate-react`'s `useSelected` hook, this was causing the cursor to appear in the wrong position in some circumstances (see the recording below). It was also causing severe performance problems when selecting and deselecting the table.
https://github.com/user-attachments/assets/2839bc1e-5bbb-44f5-8bad-292e89c40fab
This PR configures the table element to always render the content inside the popover root regardless of selection state (but not when the editor is read-only). As before, the floating toolbar is only visible when the cursor is collapsed …

Fix cursor regression and performance issue affecting tables

---

.changeset/blue-mugs-doubt.md
packages/core/src/react/editor/PlateEditor.ts

Omit duplicate type definition to avoid wrong union types

---

.changeset/beige-days-raise.md
packages/core/src/lib/static/components/slate-nodes.tsx
packages/core/src/react/components/plate-nodes.tsx

**Checklist**
NonBreakingSpace causes text to jump when added/removed.

Fix jumpy non breaking space height

---

docs/installation.mdx

Replacing "multip1le" with "multiple".
**Checklist**

fix(docs): correct typo in get started installation page

---

.changeset/flat-apes-build.md
apps/www/src/registry/ui/block-draggable.tsx
docs/components/changelog.mdx
packages/selection/src/react/BlockSelectionPlugin.tsx
packages/selection/src/react/hooks/useBlockSelectable.ts

Add `addOnContextMenu`

---

apps/www/src/registry/components/editor/plugins/list-classic-kit.tsx
docs/components/changelog.mdx

The missing `listPlugin` broke the behaviour of lists (no indent, no new item added on new line, ...) due to missing editor override and extensions.

fix(registry): include `ListPlugin` in `list-classic-kit`

---

.changeset/odd-spies-carry.md
packages/dnd/src/transforms/onDropNode.ts

**Checklist**
When dropping files into the editor, sometimes the `target` (the path where the drop happened) argument was `undefined`. This PR fixes this problem.

Fix drop target path

---

.changeset/strong-walls-invite.md
packages/core/src/react/components/plate-nodes.tsx

**Checklist**
Looks like I missed a little something in my first PR: https://github.com/udecode/plate/pull/4531
Fixed it here

Accept components with props of type PlateElementProps

---

.changeset/khaki-insects-remain.md
packages/dnd/src/DndPlugin.tsx

**Checklist**
This PR will hide the drop line, when leaving the document while dragging or dropping besides a plate editor.
Before the drop line got stuck in those scenarios.

Hide drop line on cancel drag

---

.changeset/swift-moons-fetch.md
packages/dnd/src/transforms/onDropNode.spec.ts
packages/dnd/src/transforms/onDropNode.ts
packages/dnd/src/transforms/onHoverNode.spec.ts
packages/dnd/src/types.ts
packages/dnd/src/utils/getHoverDirection.spec.ts

**Checklist**
Enabled dnd between different editors. Works only for single element drags so far (no multi selection dnd).
Disclaimer: This might only work if you use the same / one `DndProvider` for your whole app (and not one per plate.js editor). Or in other words: This only works between editors, which share the same `DndProvider`.

Enable dnd between editors

---

.changeset/neat-cooks-turn.md
packages/dnd/src/DndPlugin.tsx

Fix: Drop line is not visible when hovering white space inside the editor

---

.changeset/hot-students-sort.md
packages/markdown/src/lib/MarkdownPlugin.ts
packages/markdown/src/lib/serializer/serializeMd.spec.tsx
packages/markdown/src/lib/serializer/serializeMd.ts
packages/markdown/src/lib/serializer/utils/getMergedOptionsSerialize.ts

Fixes #4615. Forgot to add it to plugin config and correctly merge the options. Also added a test.

Fix `remarkStringifyOptions` not taken into account

---

.changeset/fair-squids-join.md
packages/floating/src/hooks/useFloatingToolbar.ts

The floating toolbar was causing infinite re-renders under certain conditions, leading to performance issues and potential browser hangs. This occurred when users interacted with text selections while the toolbar was visible.
The third useEffect in useFloatingToolbar had open in its dependency array while also calling setOpen inside the effect:
```typescript
React.useEffect(() => {
if (
!selectionExpanded ||
!selectionText ||
(mousedown && !open) ||  // ← Reads 'open'
hideToolbar ||
(readOnly && !showWhenReadOnly)
) {
setOpen(false);  // ← Writes 'open'
} else if (
selectionText &&
selectionExpanded &&
(!waitForCollapsedSelection || readOnly)
) {
setOpen(true);   // ← Writes 'open'
}
}, [
// ... other deps
open,  // ← Creates feedback loop!
// ...
]);
``` 
Removed open from the dependency …

useFloatingToolbar Hook Error
